/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

extern void AddDrawCallback(void *, void *) __asm__("FUN_001f4600");

#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_002FD198), where it is exact; names translated to the US level program. */

extern void func_00233AB8(void) __asm__("FUN_L07_002ba260");

void FUN_L07_002fbdb8(char *arg) {
    arg[0x30] = 8;
    *(short *)(arg + 0xA6) = 0x215;
    AddDrawCallback((void *)func_00233AB8, arg);
}
#include "qcopy.h"

/* spawns a moby of class 0x370 at a position moving along a direction */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030C918), where it is exact; names translated to the US level program. */

typedef struct {
    char _pad00[0x10];
    unsigned char nframes; /* 0x10 */
} AnimSeq;

typedef struct {
    char _pad00[0x48];
    AnimSeq *seqs[1]; /* 0x48 */
} AnimClass;

typedef struct {
    char _pad00[0x24];
    AnimClass *pClass; /* 0x24 */
    char _pad28[0x50 - 0x28];
    unsigned char frame;     /* 0x50 */
    unsigned char nextFrame; /* 0x51 */
    unsigned char seq;       /* 0x52 */
    unsigned char prevSeq;   /* 0x53 */
    char _pad54[0x5C - 0x54];
    float unk5C; /* 0x5C */
    char _pad60[0x68 - 0x60];
    float *frameData; /* 0x68 */
    char _pad6C[4];
    unsigned char unk70; /* 0x70 */
} MobyAnim;

extern char *func_0020D348_m(int);
extern float FUN_001f9b20(void *);
extern float FUN_001f9e90(float, float);
extern int FUN_001f96f8(int);
extern void FUN_001f9c48(void *, void *, float);
extern void FUN_L00_00250df8(void *);
extern void FUN_L00_00259888(char *arg, int a, int b, void *src, float scale);
void blend_moby_animation_u(MobyAnim *moby, int new_seq, int frame_index, int blend_frames) __asm__("FUN_00212f90");

unsigned char *FUN_L07_0030b538(void *pos, float *dir, int a, int b) {
    unsigned char *m = func_0020D348_m(0x370);
    if (m) {
        char *d;
        float V[4];
        m[0x30] = 0xFF;
        *(short *)(m + 0x32) = 0x7F;
        m[0x31] = 1;
        *(int *)(m + 0x40) = 0;
        d = *(char **)(m + 0x78);
        *(float *)(m + 0x44) = -FUN_001f9e90(FUN_001f9b20(dir), dir[2]);
        *(float *)(m + 0x48) = FUN_001f9e90(dir[0], dir[1]);
        qcopy(m + 0x10, pos);
        qcopy(d + 0x40, pos);
        qcopy(d + 0x30, dir);
        qcopy(V, d + 0x30);
        V[2] = 0.0f;
        FUN_001f9c48(V, V, 1.0f);
        V[2] = 1.0f;
        FUN_L00_00259888(d, (int)m, 0x10001, V, 1.0f);
        d[0x18] = 1;
        d[0x19] = 1;
        blend_moby_animation_u(m, 1, 0, FUN_001f96f8(5));
        *(short *)(m + 0x34) = 0x208;
        *(int *)(d + 0x50) = a;
        *(int *)(d + 0x54) = b;
        m[0x23] = 0x10;
        FUN_L00_00250df8(m);
    }
    return m;
}
/* spawns a moby with random velocity and copies position */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030CE70), where it is exact; names translated to the US level program. */

extern float D_0015ED6C;
extern float FUN_L00_00257c48(float lo, float hi);
extern float random_angle_radians(void) __asm__("FUN_00213308");
extern char *func_0020D348_m(int) __asm__("FUN_0020c4f8");

char *FUN_L07_0030ba90(char *pos, char *vec, int c, short d) {
    char *m = func_0020D348_m(0x372);
    char *p;
    if (m) {
        p = *(char **)(m + 0x78);
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(unsigned short *)(m + 0x32) = 0xFF;
        m[0x31] = 1;
        *(float *)(m + 0x40) = random_angle_radians();
        *(float *)(m + 0x44) = random_angle_radians();
        *(float *)(m + 0x48) = random_angle_radians();
        *(float *)(p + 0x18) = FUN_L00_00257c48(100.0f, 300.0f) * 0.017453292f * D_0015ED6C;
        *(float *)(p + 0x1C) = FUN_L00_00257c48(100.0f, 300.0f) * 0.017453292f * D_0015ED6C;
        qcopy(m + 0x10, pos);
        qcopy(p, vec);
        *(int *)(p + 0x10) = c;
        *(int *)(p + 0x14) = d;
        FUN_L00_00250df8(m);
    }
    return m;
}
extern void AddDrawCallback(void *, void *) __asm__("FUN_001f4600");

#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030E820), where it is exact; names translated to the US level program. */

extern char D_L07_00166E40[];
extern void l07_moby_draw_callback(void) __asm__("FUN_L07_0030d420");
extern int is_point_inside_clip_volume() __asm__("FUN_00214720");
extern char D_L07_00208560[];
extern void FUN_L02_002a40d0(void *, float);

void FUN_L07_0030d440(unsigned char *moby) {
    switch (moby[0x20]) {
    case 0:
        FUN_L02_002a40d0(D_L07_00208560, 0.66666669f);
        moby[0x20] = 1;
        moby[0x30] = 0xFF;
        break;
    case 1:
        if (!is_point_inside_clip_volume(D_L07_00166E40, **(int **)(moby + 0x78))) {
            AddDrawCallback((void *)l07_moby_draw_callback, moby);
        }
        break;
    }
}
/* Slows and steers a moby toward another when it is below and close in height. */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030F4C0), where it is exact; names translated to the US level program. */

extern float FUN_001f9b80(void *, void *);
extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_001f9bf8(void *, void *, float);
extern void FUN_L00_00259bc8(char *m, float t, int a, int b, void *pos, void *vel);
float AbsoluteFloat(float input) __asm__("func_001F99C0");

void FUN_L07_0030e0e0(char *a, char *b, char *c) {
    float v[4];
    float w[4];
    if (*(float *)(a + 0x18) < *(float *)(b + 0x18) + *(float *)(c + 0x10) * 0.3f) {
        float d = FUN_001f9b80(b + 0x10, a + 0x10);
        if (AbsoluteFloat(d - *(float *)(c + 8)) < 0.3f) {
            FUN_001f9a28(v, a + 0x10, b + 0x10);
            FUN_001f9bf8(w, v, *(float *)(c + 8) - 0.05f);
            FUN_001f9bf8(v, v, 1.0f);
            v[2] = 1.0f;
            FUN_L00_00259bc8(a, *(float *)(c + 0x1c), (int)b, 0x10001, w, v);
        }
    }
}
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030F5D8), where it is exact; names translated to the US level program. */

extern char *D_L07_0015FFE4;
extern char D_0013E533[];
extern int FUN_L07_0030e0e0_c() __asm__("FUN_L07_0030e0e0");
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern void FUN_L07_0030dcf0(void);
void enqueue_callback_list_1(s32 arg0, s32 arg1) __asm__("FUN_001f4600");
void mark_moby_for_removal_u(struct Obj *obj) __asm__("FUN_0020c828");
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L07_0030e1f8(unsigned char *m) {
    char *d = *(char **)(m + 0x78);
    float r;
    char *p;
    *(float *)(d + 8) = *(float *)(d + 8) + *(float *)(d + 0xC);
    *(float *)(m + 0x2C) = *(float *)(d + 8);
    r = (*(float *)(d + 8) - *(float *)d) / (*(float *)(d + 4) - *(float *)d);
    if (r < 0.2f) {
        m[0x23] = func_001FA898_r(r * 5.0f * 127.0f);
    } else if (r > 0.8f) {
        m[0x23] = func_001FA898_r((1.0f - r) * 5.0f * 127.0f);
    } else {
        m[0x23] = 0x80;
    }
    if (r >= 1.0f) {
        mark_moby_for_removal_u(m);
        return;
    }
    enqueue_callback_list_1((void *)FUN_L07_0030dcf0, m);
    FUN_L07_0030e0e0_c(*(void **)(D_0013E533 + 0x2E9D), m, d);
    for (p = D_L07_0015FFE4; p; p = *(char **)(p + 0x28)) {
        FUN_L07_0030e0e0_c(p, m, d);
    }
}
/* Spawn the class 0x419 effect moby at a position with a data block, and start its particle. */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030F750), where it is exact; names translated to the US level program. */

extern char *FUN_L00_0026daa0(char *src, int col, int w, int v, float x);

char *FUN_L07_0030e370(char *pos, char *vec, int arg) {
    char *m = func_0020D348_m(0x419);
    if (m != 0) {
        char *data;
        *(short *)(m + 0x32) = *(unsigned char *)(m + 0x30) = 0xFF;
        m[0x31] = 1;
        data = *(char **)(m + 0x78);
        *(float *)(m + 0x40) = random_angle_radians();
        *(float *)(m + 0x44) = random_angle_radians();
        *(float *)(m + 0x48) = random_angle_radians();
        qcopy(m + 0x10, pos);
        qcopy(data, vec);
        *(int *)(data + 0x10) = arg;
        m[0x23] = 0x30;
        *(unsigned short *)(m + 0x34) |= 0x200;
        FUN_L00_00250df8(m);
        FUN_L00_0026daa0(m, 0x800040FF, 0x80, -1, 500000.0f);
    }
    return m;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030FFA8), where it is exact; names translated to the US level program. */

extern float FUN_L00_00259710(void *);

int FUN_L07_0030ebc8(char *moby, char *data) {
    float distance = FUN_L00_00259710(moby + 0x10);
    float delta;
    *(float *)(data + 0x130) = distance;
    delta = **(float **)(data + 0x12C) - distance;
    *(float *)(data + 0x138) = distance + delta * 0.5f;
    if (delta < 0.41f)
        return 2;
    if (delta > 0.68f)
        return 0;
    return 1;
}
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_00310038), where it is exact; names translated to the US level program. */

void blend_moby_animation_u(MobyAnim *moby, int new_seq, int frame_index, int blend_frames) __asm__("FUN_00212f90");

void FUN_L07_0030ec58(char *arg) {
    switch (((unsigned char *)arg)[0xBC]) {
    case 0:
        if (((unsigned char *)arg)[0x53] != 0) {
            blend_moby_animation_u(arg, 0, 0, 10);
        }
        arg[0x20] = 1;
        break;
    case 1:
        if (((unsigned char *)arg)[0x53] != 3) {
            blend_moby_animation_u(arg, 3, 0, 10);
        }
        arg[0x20] = 7;
        break;
    case 2:
        if (((unsigned char *)arg)[0x53] != 9) {
            blend_moby_animation_u(arg, 9, 0, 10);
        }
        arg[0x20] = 0xF;
        break;
    }
}
/* Step a moby's velocity toward a target: gravity when above a height, then ease and clamp. */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_003104D8), where it is exact; names translated to the US level program. */

extern float advance_accelerated_scalar(float *, float *, float, float, float,
                                        float) __asm__("FUN_00213f38");
extern int FUN_L00_00258ad0(int a, int b, int g, int e, float c, float d);
extern void FUN_001f9a68(void *, void *, float);

void FUN_L07_0030f0f8(char *a, char *b, float f12, float f13, float f14) {
    float v[4];
    char *q;
    if (**(float **)(b + 0x12C) - 0.3f < *(float *)(a + 0x18)) {
        *(float *)(b + 0xD8) -= D_0015ED6C * 9.8f;
    }
    qcopy(v, a + 0x10);
    advance_accelerated_scalar(v + 2, (float *)(b + 0xD8), *(float *)(b + 0x138), f12, f13, f14);
    q = b + 0xD0;
    if (FUN_L00_00258ad0((int)a, (int)q, 0x400, 0x10, 1.0f, 0.0f)) {
        FUN_001f9a68(q, q, 0.5f);
    }
}
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_003105C0), where it is exact; names translated to the US level program. */

extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern float fast_difference_between_rotations(float, float) __asm__("FUN_001fa688");

int FUN_L07_0030f1e0(char *moby, char *obj, float a, float lo, float up, float hi, float down,
                     float vmax, float vmin) {
    float speed = FUN_001f9b20(obj + 0xD0);
    int r = 0;
    float d = fast_difference_between_rotations(*(float *)(moby + 0x48), a);
    if (d < lo) {
        speed += up;
        r = 1;
    } else if (hi < d) {
        speed -= down;
    }
    if (vmax < speed) {
        speed = vmax;
    } else if (speed < vmin) {
        speed = vmin;
    }
    *(float *)(obj + 0xD0) = FUN_001f9dc8(*(float *)(moby + 0x48)) * speed;
    *(float *)(obj + 0xD4) = FUN_001f9de0(*(float *)(moby + 0x48)) * speed;
    return r;
}
extern int coll_sphere(float, void *, int, void *) __asm__("FUN_L00_001f0d60");

/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_003108B0), where it is exact; names translated to the US level program. */

extern int D_L07_00173ED8 __attribute__((section(".data")));
extern void FUN_L00_0024f7c8(void *, int, void *);

int FUN_L07_0030f4d0(void *moby, int id, float scale) {
    char temp[16];
    FUN_L00_0024f7c8(moby, 0, temp);
    if (coll_sphere(scale, temp, 0x21, moby) && D_L07_00173ED8 == id) {
        return 1;
    }
    return 0;
}
extern float FastVecDist(void *, void *) __asm__("FUN_001f9b48");

/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_003134B8), where it is exact; names translated to the US level program. */

void FUN_L07_003120d8(char *moby) {
    float distance = FastVecDist(moby + 0x10, D_L07_00166E40);
    char *state;
    if (distance > 80.0f)
        distance = 80.0f;
    state = D_L07_00166E40 - 0x140;
    *(int *)(state + 0x168) = 0x14;
    *(float *)(state + 0x160) = ((80.0f - distance) / 80.0f) * 0.1f;
}
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_00313530), where it is exact; names translated to the US level program. */

extern char D_L07_00180340[];
extern f32 ConvertIntegerToFloat(s32) __asm__("func_001FA6C0");
extern int FUN_001f9770(void *);
extern int FUN_001fa6e0(int, int, float);
extern void FUN_L00_0023e838(int);

void FUN_L07_00312150(char *a) {
    int h;
    float f;
    int c;
    float *p;
    if (FUN_001f9770(a + 0x284)) {
        if (*(short *)(a + 0x280) != -1) {
            FUN_L00_0023e838(*(short *)(a + 0x280));
            *(short *)(a + 0x280) = -1;
            *(short *)(a + 0x282) = -1;
        }
    } else if (*(short *)(a + 0x280) != -1) {
        h = (*(short *)(a + 0x286) * 7) / 8;
        if (h < *(short *)(a + 0x284)) {
            f = ConvertIntegerToFloat(*(short *)(a + 0x284) - h);
            f /= ConvertIntegerToFloat(*(short *)(a + 0x286) - h);
            c = FUN_001fa6e0(0, *(int *)(a + 0x288), 1.0f - f);
        } else {
            f = ConvertIntegerToFloat(*(short *)(a + 0x284));
            f /= ConvertIntegerToFloat(h);
            c = FUN_001fa6e0(*(int *)(a + 0x288), *(int *)(a + 0x28C), 1.0f - f);
        }
        p = (float *)(D_L07_00180340 + *(short *)(a + 0x280) * 32);
        p[0] = ConvertIntegerToFloat(c & 0xFF) * 0.0078125f;
        p[1] = ConvertIntegerToFloat((c >> 8) & 0xFF) * 0.0078125f;
        p[2] = ConvertIntegerToFloat((c >> 16) & 0xFF) * 0.0078125f;
    }
}
/* steps a hit-effect emitter: orient, spawn a puff, and reseed the timer */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_00313690), where it is exact; names translated to the US level program. */

extern int FUN_001f9740(int *counter);
extern int FUN_0022da68(int, int, int);
extern int FUN_L07_0030e370_c() __asm__("FUN_L07_0030e370");
extern void FUN_L00_001ff600(float, void *, void *);
extern void FUN_L07_00311eb8(float, void *, void *, int, void *, short, unsigned int, int);

int FUN_L07_003122b0(void *mp, char *obj, float *vec) {
    unsigned char *moby = mp;
    float A[4];
    float B[4];
    if (FUN_001f9740((int *)(obj + 0x160))) {
        FUN_L00_0024f7c8(moby, *(int *)(obj + 0x164) & 1, A);
        FUN_001f9a28(B, vec, A);
        FUN_L00_001ff600(10.7f, B, B);
        B[2] += 0.5f;
        if (B[2] > 0.0f)
            B[2] = 0.0f;
        FUN_001f9bf8(B, B, D_0015ED6C * 9.0f);
        FUN_L07_0030e370_c(A, B, moby);
        FUN_0022da68(0, 0, (int)moby);
        FUN_L07_00311eb8(10.0f, moby, obj, 0, A, FUN_001f96f8(0x1E), 0x800060FF, 0);
        *(int *)(obj + 0x160) = FUN_001f96f8(9);
        if (++*(int *)(obj + 0x164) >= 0x15) {
            *(short *)(obj + 0x198) = FUN_001f96f8(0x23);
            *(int *)(obj + 0x160) = FUN_001f96f8(0x1E);
            return 1;
        }
    }
    return moby[0x20];
}

#define F(p, o) (*(float *)((p) + (o)))

/* Moves a moby along a path, easing between nodes and tracking the hero. */
extern char *D_L07_001B0530[];
extern float FUN_001f96b0(float);
extern int FUN_L00_0028d8c0(void *, int);
extern int FUN_L01_00277fb8(void *);
extern s32 allocate_voice_for_target_entry(s32, s32, void *) __asm__("func_0022DA68");
extern s32 scale_game_frames(s32) __asm__("func_001F96F8");
extern void FUN_L00_002223f8(int, int);
extern void FUN_L00_00227638(void);
extern void FUN_L00_00260738(void *, void *, void *, void *);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void release_voice_slot(s32) __asm__("FUN_0022d798");
extern void scale_vector_xyz(void *out, void *a, f32 s) __asm__("FUN_001f9a68");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
float AbsoluteFloat(float input) __asm__("func_001F99C0");
extern char D_0013F3D0[];
extern char D_0013E550[];

#define F(p, o) (*(float *)((p) + (o)))

void FUN_L07_002cd2b0(unsigned char *moby) {
    char *data = *(char **)(moby + 0x78);
    char *hero;
    char *path;
    float orig[4], delta[4], tmp[4];
    if (*(int *)(data + 0xB4) == -1) {
        return;
    }
    path = D_L07_001B0530[*(int *)(data + 0xB4)];
    qcopy(orig, moby + 0x10);
    FUN_001f9770(data + 0xBA);
    if (moby[0x20] == 0) {
        float f;
        char *pts;
        data[0x28] = 4;
        *(short *)(data + 0x3E) = 5;
        *(int *)(data + 0x20) = 0;
        *(short *)(data + 0x24) = 0;
        f = 0.0f;
        if ((moby[0xBC] = data[0xA0]) == 0) {
            f = 1.0f;
        }
        F(data, 0xA4) = f;
        pts = path + 0x10;
        qcopy((moby + 0x10), func_001FA898_r(f) ? pts + (*(int *)path - 1) * 16 : pts);
        *(short *)(data + 0xBA) = 0;
        *(int *)(data + 0xA8) = 0;
        *(int *)(data + 0xBC) = 0;
        moby[0x20] = 1;
        moby[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        *(int *)(data + 0xC4) = -1;
    }
    switch (moby[0xBC]) {
    case 0: {
        char *cls = *(char **)(moby + 0x24);
        float t = F(moby, 0x2C) - F(cls, 0x24) / 60.0f;
        F(moby, 0x2C) = t;
        if (t < 0.0f) {
            F(moby, 0x2C) = F(cls, 0x24);
            qcopy((moby + 0x10), path + 0x10);
            moby[0xBC] = 1;
            F(data, 0xA4) = 0.0f;
        }
        break;
    }
    case 1:
        if (*(short *)(data + 0xB8) != 0) {
            if (FUN_L01_00277fb8(moby)) {
                if (*(int *)(data + 0xC8) == 0) {
                    if (FUN_L01_00277fb8(moby)) {
                        FUN_L00_002223f8(0x72, 1);
                    }
                }
                moby[0xBC] = 2;
                F(data, 0xAC) = 1.0f / FUN_001f96b0(F(data, 0xB0) * 60.0f);
                *(short *)(data + 0xB8) = 0;
            }
        }
        break;
    case 2:
        if (*(short *)(data + 0xBA) != 0 ||
            (F(data, 0xBC) < 0.0f &&
             FUN_001f9b80((moby + 0x10), hero = ((char *)&D_0013F3D0)) < 2.0f &&
             AbsoluteFloat(F(hero -= 0x80, 0x88) - F(moby, 0x18)) < 4.0f &&
             F(moby, 0x18) - F(hero, 0x88) > 1.0f)) {
            int r;
            if (*(short *)(data + 0xBA) == 0) {
                *(short *)(data + 0xBA) = scale_game_frames(30);
            }
            r = *(int *)(data + 0xC4);
            *(int *)(data + 0xA8) = 0;
            if (r != -1) {
                unsigned char *s = (unsigned char *)((char *)&D_0013E550) + r * 0x70;
                if (*(unsigned char **)(s + 0x88) == moby && s[0x74] != 0) {
                    release_voice_slot(r);
                }
            }
            *(int *)(data + 0xC4) = -1;
        } else {
            int i;
            float f20, t;
            char *q;
            if (!FUN_L00_0028d8c0(moby, *(int *)(data + 0xC4))) {
                *(int *)(data + 0xC4) = allocate_voice_for_target_entry(0, 4, (int)moby);
            }
            F(data, 0xA8) += F(data, 0xAC) * D_0015ED6C;
            if (AbsoluteFloat(F(data, 0xA8)) > AbsoluteFloat(F(data, 0xAC))) {
                F(data, 0xA8) = F(data, 0xAC);
            }
            F(data, 0xA4) = F(data, 0xA4) + F(data, 0xA8);
            if (0.5f < AbsoluteFloat(F(data, 0xA4) - 0.5f)) {
                int r;
                if (*(int *)(data + 0xC8) == 0 && FUN_L01_00277fb8(moby)) {
                    FUN_L00_00227638();
                }
                if (0.0f < F(data, 0xAC)) {
                    moby[0xBC] = 0;
                    F(data, 0xA4) = 1.0f;
                } else {
                    moby[0xBC] = 1;
                    F(data, 0xA4) = 0.0f;
                }
                *(int *)(data + 0xA8) = 0;
                *(short *)(data + 0xBA) = scale_game_frames(15);
                r = *(int *)(data + 0xC4);
                if (r != -1) {
                    unsigned char *s = (unsigned char *)((char *)&D_0013E550) + r * 0x70;
                    if (*(unsigned char **)(s + 0x88) == moby && s[0x74] != 0) {
                        release_voice_slot(r);
                    }
                }
                *(int *)(data + 0xC4) = -1;
            }
            f20 = ConvertIntegerToFloat(*(int *)path - 1);
            i = func_001FA898_r(f20 * F(data, 0xA4));
            f20 = ConvertIntegerToFloat(*(int *)path - 1);
            t = ConvertIntegerToFloat(i);
            f20 *= F(data, 0xA4);
            f20 -= t;
            if (i == *(int *)path - 1) {
                qcopy((moby + 0x10), path + 0x10 + i * 16);
            } else {
                q = path + 0x10 + i * 16;
                subtract_vector_xyz(tmp, path + 0x20 + i * 16, q);
                scale_vector_xyz(tmp, tmp, f20);
                add_vector_xyz((moby + 0x10), tmp, q);
            }
            F(data, 0xBC) = F(moby, 0x18) - orig[2];
        }
        break;
    }
    subtract_vector_xyz(delta, (moby + 0x10), orig);
    FUN_L00_00260738(data + 0x60, delta, moby + 0x40, moby + 0x40);
    if (!FUN_L01_00277fb8(moby)) {
        if (2.0f < FUN_001f9b80((moby + 0x10), ((char *)&D_0013F3D0))) {
            if (*(short *)(data + 0xBA) == 0) {
                *(short *)(data + 0xB8) = 1;
            }
        }
    }
}
/* Moves a moby along a path between its two ends, hidden while its gate byte is set. */
extern char *D_L07_001B0530[];
extern float FUN_001f96b0(float);
extern int FUN_L00_0028d8c0(void *, int);
extern int FUN_L01_00277fb8(void *);
extern s32 allocate_voice_for_target_entry(s32, s32, void *) __asm__("func_0022DA68");
extern s32 scale_game_frames(s32) __asm__("func_001F96F8");
extern unsigned char D_L07_0015FC88[] __attribute__((section(".sdata")));
extern void FUN_L00_002223f8(int, int);
extern void FUN_L00_00227638(void);
extern void FUN_L00_00260738(void *, void *, void *, void *);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void release_voice_slot(s32) __asm__("FUN_0022d798");
extern void scale_vector_xyz(void *out, void *a, f32 s) __asm__("FUN_001f9a68");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
float AbsoluteFloat(float input) __asm__("func_001F99C0");
extern char D_0013F3D0[];
extern char D_0013E550[];

void FUN_L07_002cdb28(unsigned char *moby) {
    char *data = *(char **)(moby + 0x78);
    char *hero;
    char *path;
    float orig[4], delta[4], tmp[4];
    if (D_L07_0015FC88[moby[0xB0]] != 0xFF) {
        *(int *)(moby + 0x94) = 0;
        *(unsigned short *)(moby + 0x34) |= 0x41;
        return;
    }
    if (*(int *)(data + 0xB4) == -1) {
        return;
    }
    path = D_L07_001B0530[*(int *)(data + 0xB4)];
    qcopy(orig, moby + 0x10);
    FUN_001f9770(data + 0xBA);
    if (moby[0x20] == 0) {
        float f;
        char *pts;
        data[0x28] = 4;
        *(short *)(data + 0x3E) = 5;
        *(int *)(data + 0x20) = 0;
        *(short *)(data + 0x24) = 0;
        f = 0.0f;
        if ((moby[0xBC] = data[0xA0]) == 0) {
            f = 1.0f;
        }
        *(float *)(data + 0xA4) = f;
        pts = path + 0x10;
        qcopy((moby + 0x10), func_001FA898_r(f) ? pts + (*(int *)path - 1) * 16 : pts);
        *(short *)(data + 0xBA) = 0;
        *(int *)(data + 0xA8) = 0;
        *(int *)(data + 0xBC) = 0;
        moby[0x20] = 1;
        moby[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        *(int *)(data + 0xC4) = -1;
        *(unsigned short *)(moby + 0x34) &= 0xFFBE;
        *(int *)(moby + 0x94) = *(int *)(*(char **)(moby + 0x24) + 0x10);
    }
    switch (moby[0xBC]) {
    case 0: {
        char *cls = *(char **)(moby + 0x24);
        float t = *(float *)(moby + 0x2C) - *(float *)(cls + 0x24) / 60.0f;
        *(float *)(moby + 0x2C) = t;
        if (t < 0.0f) {
            *(float *)(moby + 0x2C) = *(float *)(cls + 0x24);
            qcopy((moby + 0x10), path + 0x10);
            moby[0xBC] = 1;
            *(float *)(data + 0xA4) = 0.0f;
        }
        break;
    }
    case 1:
        if (*(short *)(data + 0xB8) != 0) {
            if (FUN_L01_00277fb8(moby)) {
                if (*(int *)(data + 0xC8) == 0) {
                    if (FUN_L01_00277fb8(moby)) {
                        FUN_L00_002223f8(0x72, 1);
                    }
                }
                moby[0xBC] = 2;
                *(float *)(data + 0xAC) = 1.0f / FUN_001f96b0(*(float *)(data + 0xB0) * 60.0f);
                *(short *)(data + 0xB8) = 0;
            }
        }
        break;
    case 2:
        if (*(short *)(data + 0xBA) != 0 ||
            (*(float *)(data + 0xBC) < 0.0f &&
             FUN_001f9b80((moby + 0x10), hero = ((char *)&D_0013F3D0)) < 2.0f &&
             AbsoluteFloat(*(float *)((hero -= 0x80) + 0x88) - *(float *)(moby + 0x18)) < 4.0f &&
             *(float *)(moby + 0x18) - *(float *)(hero + 0x88) > 1.0f)) {
            int r;
            if (*(short *)(data + 0xBA) == 0) {
                *(short *)(data + 0xBA) = scale_game_frames(30);
            }
            r = *(int *)(data + 0xC4);
            *(int *)(data + 0xA8) = 0;
            if (r != -1) {
                unsigned char *s = (unsigned char *)((char *)&D_0013E550) + r * 0x70;
                if (*(unsigned char **)(s + 0x88) == moby && s[0x74] != 0) {
                    release_voice_slot(r);
                }
            }
            *(int *)(data + 0xC4) = -1;
        } else {
            int i;
            float f20, t;
            char *q;
            if (!FUN_L00_0028d8c0(moby, *(int *)(data + 0xC4))) {
                *(int *)(data + 0xC4) = allocate_voice_for_target_entry(0, 4, (int)moby);
            }
            *(float *)(data + 0xA8) += *(float *)(data + 0xAC) * D_0015ED6C;
            if (AbsoluteFloat(*(float *)(data + 0xA8)) > AbsoluteFloat(*(float *)(data + 0xAC))) {
                *(float *)(data + 0xA8) = *(float *)(data + 0xAC);
            }
            *(float *)(data + 0xA4) = *(float *)(data + 0xA4) + *(float *)(data + 0xA8);
            if (0.5f < AbsoluteFloat(*(float *)(data + 0xA4) - 0.5f)) {
                int r;
                if (*(int *)(data + 0xC8) == 0 && FUN_L01_00277fb8(moby)) {
                    FUN_L00_00227638();
                }
                if (0.0f < *(float *)(data + 0xAC)) {
                    moby[0xBC] = 3;
                    *(float *)(data + 0xA4) = 1.0f;
                } else {
                    moby[0xBC] = 1;
                    *(float *)(data + 0xA4) = 0.0f;
                }
                *(int *)(data + 0xA8) = 0;
                *(short *)(data + 0xBA) = scale_game_frames(15);
                r = *(int *)(data + 0xC4);
                if (r != -1) {
                    unsigned char *s = (unsigned char *)((char *)&D_0013E550) + r * 0x70;
                    if (*(unsigned char **)(s + 0x88) == moby && s[0x74] != 0) {
                        release_voice_slot(r);
                    }
                }
                *(int *)(data + 0xC4) = -1;
            }
            f20 = ConvertIntegerToFloat(*(int *)path - 1);
            i = func_001FA898_r(f20 * *(float *)(data + 0xA4));
            f20 = ConvertIntegerToFloat(*(int *)path - 1);
            t = ConvertIntegerToFloat(i);
            f20 *= *(float *)(data + 0xA4);
            f20 -= t;
            if (i == *(int *)path - 1) {
                qcopy((moby + 0x10), path + 0x10 + i * 16);
            } else {
                q = path + 0x10 + i * 16;
                subtract_vector_xyz(tmp, path + 0x20 + i * 16, q);
                scale_vector_xyz(tmp, tmp, f20);
                add_vector_xyz((moby + 0x10), tmp, q);
            }
            *(float *)(data + 0xBC) = *(float *)(moby + 0x18) - orig[2];
        }
        break;
    case 3:
        if (!FUN_L01_00277fb8(moby)) {
            moby[0xBC] = 0;
        }
        break;
    }
    subtract_vector_xyz(delta, (moby + 0x10), orig);
    FUN_L00_00260738(data + 0x60, delta, moby + 0x40, moby + 0x40);
    if (!FUN_L01_00277fb8(moby)) {
        if (2.0f < FUN_001f9b80((moby + 0x10), ((char *)&D_0013F3D0))) {
            if (*(short *)(data + 0xBA) == 0) {
                *(short *)(data + 0xB8) = 1;
            }
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_002f5ba0.s", FUN_L07_002f5ba0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030af40.s", FUN_L07_0030af40);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030b000.s", FUN_L07_0030b000);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030b6a8.s", FUN_L07_0030b6a8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030bbc8.s", FUN_L07_0030bbc8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030c508.s", FUN_L07_0030c508);
/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */

/* records, for entry arg, which of the 48 entries sit one grid step away */
/* Same routine as FUN_L05_0030d6a0, with this level's table and entry count. */

typedef struct {
    float x;
    float y;
    int pad;
    unsigned char n[0x14];
    char rest[0x1170];
} Ent;

extern Ent D_L07_001DCE40[];
float AbsoluteFloat(float input) __asm__("func_001F99C0");

void FUN_L07_0030cd48(int arg) {
    int i;
    D_L07_001DCE40[arg].n[0] = 0xFF;
    D_L07_001DCE40[arg].n[2] = 0xFF;
    D_L07_001DCE40[arg].n[1] = 0xFF;
    D_L07_001DCE40[arg].n[3] = 0xFF;
    D_L07_001DCE40[arg].n[4] = 0xFF;
    D_L07_001DCE40[arg].n[5] = 0xFF;
    D_L07_001DCE40[arg].n[6] = 0xFF;
    D_L07_001DCE40[arg].n[7] = 0xFF;
    for (i = 0; i < 36; i++) {
        if (arg != i) {
            Ent *t = D_L07_001DCE40;
            Ent *e = &t[arg];
            float x = e->x - t[i].x;
            float y = e->y - t[i].y;
            if (AbsoluteFloat(x) < 0.1f) {
                if (AbsoluteFloat(y - 16.0f) < 0.1f)
                    e->n[0] = i;
                if (AbsoluteFloat(y + 16.0f) < 0.1f)
                    e->n[2] = i;
            } else if (AbsoluteFloat(y) < 0.1f) {
                if (AbsoluteFloat(x - 16.0f) < 0.1f)
                    e->n[1] = i;
                if (AbsoluteFloat(x + 16.0f) < 0.1f)
                    e->n[3] = i;
            } else {
                if (AbsoluteFloat(x + 16.0f) < 0.1f) {
                    if (AbsoluteFloat(y - 16.0f) < 0.1f)
                        e->n[5] = i;
                    if (AbsoluteFloat(y + 16.0f) < 0.1f)
                        e->n[7] = i;
                } else if (AbsoluteFloat(x - 16.0f) < 0.1f) {
                    if (AbsoluteFloat(y - 16.0f) < 0.1f)
                        e->n[4] = i;
                    if (AbsoluteFloat(y + 16.0f) < 0.1f)
                        e->n[6] = i;
                }
            }
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030cf90.s", FUN_L07_0030cf90);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030d4d8.s", FUN_L07_0030d4d8);
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030EF90), where it is exact; names translated to the US level program. */

extern s32 scale_game_frames(s32) __asm__("func_001F96F8");

unsigned char *FUN_L07_0030dbb0(int a, void *pos, int b, float f0, float f1, float f2, float f3,
                                float f4) {
    unsigned char *moby = (unsigned char *)func_0020D348_m(0x416);
    if (moby != 0) {
        char *data;
        char *g;
        char *h;
        data = *(char **)(moby + 0x78);
        moby[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        qcopy(moby + 0x10, pos);
        *(int *)(data + 0x14) = a;
        *(float *)(data + 4) = f1;
        *(float *)(data + 0x10) = f2;
        *(float *)(data + 0xC) = f3;
        *(float *)data = f0;
        *(float *)(data + 8) = f0;
        *(int *)(data + 0x18) = b;
        *(float *)(data + 0x1C) = f4;
        *(unsigned short *)(moby + 0x34) |= 0x200;
        g = D_L07_00166E40;
        h = g - 0x140;
        *(float *)(h + 0x160) = 0.3f - FUN_001f9b80(moby + 0x10, g) / 100.0f;
        *(int *)(h + 0x168) = scale_game_frames(0x14);
        FUN_L00_00250df8(moby);
        FUN_0022da68(0, 0, (int)moby);
    }
    return moby;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030dcf0.s", FUN_L07_0030dcf0);

#define NOT_SDA

#define MACRO_ADDR

#include "qcopy.h"

/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030F838), where it is exact; names translated to the US level program. */

extern float D_0015ED6C;
extern float D_0015ED70;
extern int D_L07_0015F5CC;
extern int D_L07_00173ED8;
extern int FUN_001efa68(void *, void *, int, int, int);
extern int FUN_L00_001f0d60(float, void *, int, void *);
extern int FUN_L00_0025e450();
extern void FUN_L07_0029b8d8(char *, int, float, float);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
s32 allocate_voice_for_target_entry(s32 entry_index, s32 flags,
                                    void *target) __asm__("FUN_0022da68");
void mark_moby_for_removal(void *obj) __asm__("FUN_0020c828");
extern char *D_L07_ed0_e[] __asm__("D_L07_00173ED0");
extern int func_L00_001F10E0_f(float, void *, int, int) __asm__("FUN_L00_001f0d60");
extern void func_L00_0025F4A8_alt(void *, void *, void *, float, float, int, int, int, float, float,
                                  float, float, int, float, int, int, int,
                                  int) __asm__("FUN_L00_0025e450");

void FUN_L07_0030e458(char *m) {
    char *d = *(char **)(m + 0x78);
    float prev[4];
    qcopy(prev, m + 0x10);
    add_vector_xyz(m + 0x10, m + 0x10, d);
    {
        float g = D_0015ED70 * 9.8f;
        float r = D_0015ED6C * 6.2831855f;
        *(float *)(d + 8) -= g;
        *(float *)(m + 0x48) += r;
    }
    if (*(float *)(m + 0x2C) < *(float *)(*(char **)(m + 0x24) + 0x24) * 2.8f) {
        *(float *)(m + 0x2C) *= 1.2f;
    }
    if (D_L07_0015F5CC % 3 == 0) {
        FUN_L07_0029b8d8(m, 0, 400000.0f, 5.0f);
    }
    if (FUN_001efa68(prev, m + 0x10, 0, *(int *)(d + 0x10), 0) != 0 ||
        func_L00_001F10E0_f(0.1f, m + 0x10, 0, *(int *)(d + 0x10)) != 0) {
        char *o = D_L07_ed0_e[2];
        if (o == 0 || (*(short *)(o + 0xA6) != 0x415 && *(short *)(o + 0xA6) != 0x419 &&
                       *(short *)(o + 0xA6) != 0x452)) {
            if (((unsigned char *)m)[0x31] != 0) {
                func_L00_0025F4A8_alt(m, d, 0, 2.0f, 1.0f, 0, 3, 5, 0.0f, 0.0f, 1000.0f, 1.2f, 0,
                                      10.0f, 0, 1, -1, 0);
            } else {
                allocate_voice_for_target_entry(0, 0, (int)m);
            }
            mark_moby_for_removal(m);
            return;
        }
    }
    if (*(float *)(m + 0x10) < 2.0f || 1021.0f < *(float *)(m + 0x10) ||
        *(float *)(m + 0x14) < 2.0f || 1021.0f < *(float *)(m + 0x14) ||
        *(float *)(m + 0x18) < 2.0f || 1021.0f < *(float *)(m + 0x18)) {
        mark_moby_for_removal(m);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030e720.s", FUN_L07_0030e720);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030e858.s", FUN_L07_0030e858);

#define NOT_SDA

#define MACRO_ADDR

/* Hit handler: reacts to the hit type, then takes damage and dies (state 0xE) when health runs out. */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030FD78), where it is exact; names translated to the US level program. */

extern char *FUN_L00_0025a420(void *, int, int);
extern int FUN_L00_0025a478(void *, void *, void *, int, int *, float *, int, int);
extern s32 scale_game_frames(s32) __asm__("func_001F96F8");
extern void FUN_L00_00257470(void *, int, int);
extern void FUN_L00_0025d458(void *, short *);
extern void FUN_L07_0030e720(void *, void *, void *);
extern void FUN_L07_0030e858(void *, void *, void *);
extern void blend_moby_animation(void *, int, int, int) __asm__("FUN_00212f90");

void FUN_L07_0030e998(char *m, char *x, float *hp) {
    char *info;
    int hit;
    int r;
    if (((unsigned char *)m)[0x20] == 0xE)
        return;
    info = FUN_L00_0025a420(m, 0x330000, 0);
    r = FUN_L00_0025a478(m, info, hp, 0, &hit, 0, 0, 4);
    if (((unsigned char *)m)[0xBC] != 0) {
        switch (r) {
        case 0:
            break;
        case 1:
        case 2:
            *hp = 0.0f;
            break;
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
            FUN_L07_0030e858(m, x + 0x70, info + 0x10);
            m[0x20] = 0xC;
            break;
        case 9:
        case 10:
            if (((unsigned char *)m)[0x53] != 4) {
                blend_moby_animation(m, 4, 4, 4);
            }
            m[0x20] = 0xD;
            break;
        case 11:
            break;
        }
        if (hit >= 2) {
            if (*hp <= *(float *)(info + 0x2C)) {
                *hp = 0.0f;
                *(unsigned short *)(m + 0x34) &= 0xEFFF;
                FUN_L07_0030e720(m, x + 0x70, info + 0x10);
                FUN_L00_00257470(m, 0, -1);
                x[0x67] = 0x78;
                FUN_L00_0025d458(m, (short *)(x + 0x60));
                m[0x20] = 0xE;
            } else {
                *hp -= *(float *)(info + 0x2C);
                ((unsigned char *)x)[0x67] = 0xFA;
                *(short *)(x + 0x26) = scale_game_frames(0x3C);
                FUN_L00_0025d458(m, (short *)(x + 0x60));
            }
        }
    }
    ((unsigned char *)m)[0xA4] = 0xFF;
}
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_0030FF18), where it is exact; names translated to the US level program. */

extern float FUN_001f9b48(void *, void *);

void FUN_L07_0030eb38(char *data) {
    int i, count;
    if (data != 0) {
        count = *(int *)data;
        i = 0;
        if (count > 0) {
            do {
                int o = i * 16;
                int next = (i + 1) % count;
                *(float *)(data + o + 0x1C) =
                    FUN_001f9b48(data + (o + 0x10), data + (next * 16 + 0x10));
                i++;
                count = *(int *)data;
            } while (i < count);
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030ed30.s", FUN_L07_0030ed30);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030eee8.s", FUN_L07_0030eee8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030f308.s", FUN_L07_0030f308);
/* Finds another moby whose state lies within the inclusive range. */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_00310920), where it is exact; names translated to the US level program. */

extern int FUN_L00_002591d0(int *, int, int, int);
extern int FUN_L00_002592b8(int *, int, int, int);

int FUN_L07_0030f540(unsigned char *moby, int lower, int upper) {
    unsigned char *other = 0;
    if (!FUN_L00_002591d0((int *)&other, moby[0x21], 0, 0)) {
        if (other) {
            do {
                if (other != moby) {
                    int state = other[0x20];
                    if (state >= lower) {
                        if (state <= upper) {
                            goto found;
                        }
                    }
                }
                if (FUN_L00_002592b8((int *)&other, (int)other, 0, 0)) break;
            } while (other);
        }
    }
    return 0;
found:
    return 1;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0030f5f0.s", FUN_L07_0030f5f0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_003112c8.s", FUN_L07_003112c8);
/* Falling leaf: drops off its branch after a random delay, swaying, then falls faster and vanishes near the ground. */
/* Ported from rac1-decomp (src/overlays/l07_umbris/vendor_002CE470.c: func_L07_00312FA8), where it is exact; names translated to the US level program. */

extern f32 fast_cos(f32) __asm__("func_001F9DC8");
extern f32 fast_sin(f32) __asm__("func_001F9DE0");
extern float D_0015ED60;
extern float D_0015ED70;
extern float FUN_L00_0025e310(float);
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern void FUN_L00_002502f0(void *, int, int, int);
extern void subtract_vector_xyz_c(void *, void *, void *) __asm__("FUN_001f9a28");
s32 allocate_voice_for_target_entry_c(s32 entry_index, s32 flags,
                                      void *target) __asm__("FUN_0022da68");
void mark_moby_for_removal_c(void *obj) __asm__("FUN_0020c828");

void FUN_L07_00311bc8(char *m) {
    char *d;
    float prev[4];
    float v[4];
    float t;
    float g;
    if (m == 0)
        return;
    d = *(char **)(m + 0x78);
    if (d == 0)
        return;
    qcopy(prev, m + 0x10);
    switch (((unsigned char *)m)[0x20]) {
    case 0:
        *(int *)(d + 0x20) = 0;
        *(short *)(d + 0x24) = 0;
        d[0x28] = 4;
        *(short *)(d + 0x3E) = 0xD;
        FUN_L00_002502f0(m, 0x50, 0x40, 0x10);
        *(float *)(m + 0x40) += random_float_between_alt(-0.034906585f, 0.034906585f);
        *(float *)(m + 0x44) += random_float_between_alt(-0.034906585f, 0.034906585f);
        *(float *)(m + 0x18) += random_float_between_alt(-0.02f, 0.02f);
        m[0x20] = 1;
        break;
    case 1:
        if (FUN_L01_00277fb8(m)) {
            *(float *)(d + 0xA8) = *(float *)(m + 0x40);
            *(float *)(d + 0xAC) = *(float *)(m + 0x44);
            *(short *)(d + 0xA0) = scale_game_frames(0x1E);
            if (*(short *)(d + 0xA2) != -1)
                allocate_voice_for_target_entry_c(*(short *)(d + 0xA2), 0, (int)m);
            m[0x20] = 2;
        }
        break;
    case 2:
        *(float *)(m + 0x40) =
            fast_sin(FUN_L00_0025e310(ConvertIntegerToFloat(*(short *)(d + 0xA0)) * 0.75f)) *
            0.017453292f;
        {
            float c =
                fast_cos(FUN_L00_0025e310(ConvertIntegerToFloat(*(short *)(d + 0xA0)) * 0.89f));
            float e = D_0015ED60;
            *(float *)(m + 0x44) = c * 0.017453292f;
            *(float *)(m + 0x18) -= e * 0.002f;
        }
        if (FUN_001f9770(d + 0xA0)) {
            *(float *)(d + 0xA4) = D_0015ED60 * 0.002f;
            m[0x20] = 3;
        }
        break;
    case 3:
        t = (1.3962634f - *(float *)(m + 0x40)) * 0.05f;
        *(float *)(m + 0x40) += t;
        t = fast_sin(t);
        g = D_0015ED70 * 9.8f;
        *(float *)(m + 0x18) -= t + t;
        *(float *)(d + 0xA4) += g;
        *(float *)(m + 0x18) -= *(float *)(d + 0xA4);
        if (*(float *)(m + 0x18) < 2.0f) {
            mark_moby_for_removal_c(m);
            return;
        }
        break;
    case 4:
        break;
    }
    subtract_vector_xyz_c(v, m + 0x10, prev);
    FUN_L00_00260738(d + 0x60, v, m + 0x40, m + 0x40);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_00311eb8.s", FUN_L07_00311eb8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L07_00312420.s", FUN_L07_00312420);
