/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e3190.s", FUN_L16_002e3190);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e36e8.s", FUN_L16_002e36e8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e3770.s", FUN_L16_002e3770);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e37a0.s", FUN_L16_002e37a0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e3fa0.s", FUN_L16_002e3fa0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e43e0.s", FUN_L16_002e43e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e4900.s", FUN_L16_002e4900);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e4a58.s", FUN_L16_002e4a58);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e5010.s", FUN_L16_002e5010);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e5258.s", FUN_L16_002e5258);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e54a0.s", FUN_L16_002e54a0);
#define NOT_SDA

#define MACRO_ADDR

/* Start the vendor moby's turn and mark it active. */
/* Ported from rac1-decomp (PAL, src/overlays/l16/vendor_002A50F0.c: func_L16_002E6B48), where it is exact; names translated to the US level program. */

typedef struct {
    float value;
} Level16VendorTurnData;

typedef struct {
    char pad0[0x20];
    unsigned char state;
    char pad21[0x57];
    Level16VendorTurnData *data;
    char pad7C[0x40];
    unsigned char active;
} Level16VendorTurnMoby;

void FUN_L16_002e56e0(Level16VendorTurnMoby *moby) {
    moby->data->value = -3.1415925f;
    moby->active = 1;
    moby->state = 2;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e5e08.s", FUN_L16_002e5e08);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e6208.s", FUN_L16_002e6208);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e6428.s", FUN_L16_002e6428);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e6808.s", FUN_L16_002e6808);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e70c0.s", FUN_L16_002e70c0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e7168.s", FUN_L16_002e7168);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e7208.s", FUN_L16_002e7208);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e76b8.s", FUN_L16_002e76b8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e7a30.s", FUN_L16_002e7a30);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e7ba0.s", FUN_L16_002e7ba0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e7e00.s", FUN_L16_002e7e00);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e7f80.s", FUN_L16_002e7f80);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e84e8.s", FUN_L16_002e84e8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e88d0.s", FUN_L16_002e88d0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e8970.s", FUN_L16_002e8970);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e8b08.s", FUN_L16_002e8b08);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e8b98.s", FUN_L16_002e8b98);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e8d40.s", FUN_L16_002e8d40);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e8e80.s", FUN_L16_002e8e80);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e9270.s", FUN_L16_002e9270);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e93b0.s", FUN_L16_002e93b0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e98e0.s", FUN_L16_002e98e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e9ce0.s", FUN_L16_002e9ce0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002ea128.s", FUN_L16_002ea128);
