/* Level overlay code after ui/help; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002097a0.s", FUN_L16_002097a0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_0020f8b0.s", FUN_L16_0020f8b0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_0020ffb0.s", FUN_L16_0020ffb0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_00210b60.s", FUN_L16_00210b60);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_00211098.s", FUN_L16_00211098);
