/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002a3f38.s", FUN_L16_002a3f38);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c3d38.s", FUN_L16_002c3d38);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c44f0.s", FUN_L16_002c44f0);
#define NOT_SDA

#define MACRO_ADDR

/* Check whether this vendor moby is in state six. */
/* Ported from rac1-decomp (PAL, src/overlays/l16/vendor_002A50F0.c: func_L16_002C5A08), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x20];
    unsigned char state;
} Level16VendorMoby;

int FUN_L16_002c4710(Level16VendorMoby *moby) {
    return moby->state == 6;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c5eb0.s", FUN_L16_002c5eb0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c6268.s", FUN_L16_002c6268);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c9480.s", FUN_L16_002c9480);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c9568.s", FUN_L16_002c9568);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c9650.s", FUN_L16_002c9650);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c9878.s", FUN_L16_002c9878);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c9a50.s", FUN_L16_002c9a50);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c9c38.s", FUN_L16_002c9c38);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002c9cd0.s", FUN_L16_002c9cd0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cddb8.s", FUN_L16_002cddb8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002ce9f0.s", FUN_L16_002ce9f0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002ceca8.s", FUN_L16_002ceca8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002ced20.s", FUN_L16_002ced20);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cee70.s", FUN_L16_002cee70);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cef60.s", FUN_L16_002cef60);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf198.s", FUN_L16_002cf198);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf4a8.s", FUN_L16_002cf4a8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf5c8.s", FUN_L16_002cf5c8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf678.s", FUN_L16_002cf678);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf738.s", FUN_L16_002cf738);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf760.s", FUN_L16_002cf760);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf798.s", FUN_L16_002cf798);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf7a8.s", FUN_L16_002cf7a8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf850.s", FUN_L16_002cf850);
#include "qcopy.h"

/* Copy the selected 16-byte vendor vector. */
/* Ported from rac1-decomp (PAL, src/overlays/l16_kalebo3/vendor_002A50F0.c: func_L16_002D0D98), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x2C0];
    char *vectors;
} Level16VendorVectorData;

typedef struct {
    char pad0[0x78];
    Level16VendorVectorData *data;
} Level16VendorVectorMoby;

void FUN_L16_002cf9d0(Level16VendorVectorMoby *moby, int index, void *out) {
    qcopy(out, moby->data->vectors + index * 16 + 16);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cf9f8.s", FUN_L16_002cf9f8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002cff48.s", FUN_L16_002cff48);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d0058.s", FUN_L16_002d0058);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d04a0.s", FUN_L16_002d04a0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d59e0.s", FUN_L16_002d59e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d5ad0.s", FUN_L16_002d5ad0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d5bc8.s", FUN_L16_002d5bc8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d5cb8.s", FUN_L16_002d5cb8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d5db0.s", FUN_L16_002d5db0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d5e80.s", FUN_L16_002d5e80);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d5ef8.s", FUN_L16_002d5ef8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d6260.s", FUN_L16_002d6260);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002d6740.s", FUN_L16_002d6740);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002de3b8.s", FUN_L16_002de3b8);
/* Ported from rac1-decomp (PAL, src/overlays/l16_kalebo3/vendor_002A50F0.c: func_L16_002E2248), where it is exact; names translated to the US level program. */

extern void FUN_0022da68(int, int, void *);

void FUN_L16_002e0de0(unsigned char *moby) {
    int state = 1;
    if (moby[0x20] == state) {
        FUN_0022da68(0, 0, moby);
        state = 7;
        moby[0x20] = state;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e0e28.s", FUN_L16_002e0e28);
