/* Level overlay code after audio/sound; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L13_00298220.s", FUN_L13_00298220);
