/* Level overlay code after rendering; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

#include "sda.h"

#include "qcopy.h"

/* Allocates and fills a particle-process record attached to a moby. */
/* Ported from rac1-decomp (src/overlays/l13_gemlik/partupd_002811B0.c: func_L13_002811B0), where it is exact; names translated to the US level program. */

extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern unsigned char *D_L13_001B2490_x __asm__("D_L13_001B2490") __attribute__((section(".data")));
extern unsigned char *FUN_L00_002678b8(int);
extern void FUN_L00_0024f7c8(void *, int, void *);
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

unsigned char *FUN_L13_00280400(char *moby, unsigned char a, int b, int c, unsigned char d, float x,
                                float y, float z) {
    unsigned char *e = FUN_L00_002678b8(0x44);
    if (e != 0) {
        char *p;
        int v;
        unsigned short t;
        unsigned char *s;
        *(int *)(e + 4) = b;
        *(int *)(e + 0xC) = c;
        p = (char *)e + 0x10;
        v = func_001FA898_r(0.4f);
        e[9] = (((short)*(unsigned short *)(moby + 0x32) >> 5) << 4) + v;
        e[3] = 0x48;
        e[1] = 3;
        e[2] = *D_L13_001B2490_x;
        FUN_L00_0024f7c8(moby, a, p);
        qcopy(e + 0x20, p);
        *(float *)(e + 0x2C) = y;
        *(float *)(e + 0x1C) = x;
        *(char **)(e + 0x30) = moby;
        s = e + 0x30;
        t = *(unsigned short *)(moby + 0xA6);
        *(short *)(s + 6) = t;
        s[4] = a;
        *(float *)(s + 8) = x;
        *(float *)(s + 0xC) = z;
        s[5] = d;
    }
    return e;
}
