/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"
#include "qcopy.h"

/* Oltanis (level 14) vendor code.  Both bodies below were written from the
 * retail disassembly and reproduce it byte for byte on the game compiler
 * route (cc1 sce-991111b + GNU as, -O2 -G2). */

extern int D_001413DC;
extern u8 *D_L14_00167500;

/* 0x003135B8, 80 bytes.  When the level record's field at 0x86 is 7, seed the
 * sub-record reached through +0x70 with the caller's argument and two float
 * constants, and set both floats on the record itself. */
void FUN_L14_003135b8(u8 *arg0)
{
    u8 *g = D_L14_00167500;
    u8 *q;
    u8 *p;

    if (*(s16 *)(g + 0x86) != 7) {
        return;
    }
    q = *(u8 **)(g + 0x70) + 0x40;
    *(s32 *)(q + 0x40) = 1;
    *(s32 *)(q + 0x44) = (s32)arg0;
    *(f32 *)(q + 0x4C) = 2.0f;
    p = *(u8 **)(g + 0x70);
    *(f32 *)(p + 0xA0) = 7.0f;
    *(f32 *)(p + 0xB0) = 2.0f;
}

/* 0x003167E0, 36 bytes.  While the executable's mode word is not 0xF, mark the
 * object's field at 0x7E as 3. */
void FUN_L14_003167e0(u8 *arg0)
{
    if (D_001413DC != 0x0F) {
        *(s16 *)(arg0 + 0x7E) = 3;
    }
}


extern u8 *FUN_0020c4f8(s32);
extern void FUN_L00_00250df8(u8 *);

/* Allocate 0x574 bytes, copy the two 16-byte records out of the caller, stamp
 * the header fields and hand it to the level's post-create hook.  Returns the
 * allocation, null when it failed.  The two 16-byte copies go through $2 with
 * each address in its own register -- the qcopy idiom, see include/qcopy.h. */
u8 *FUN_L14_00306158(u8 *self)
{
    u8 *o = FUN_0020c4f8(0x574);

    if (o != 0) {
        qcopy(o + 0x10, self + 0x10);
        qcopy(o + 0x40, self + 0x40);
        o[0x30] = 0x40;
        o[0x20] = 0;
        *(s16 *)(o + 0x32) = 0x40;
        o[0x31] = 1;
        FUN_L00_00250df8(o);
    }
    return o;
}

INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00300e00.s", FUN_L14_00300e00);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003014e0.s", FUN_L14_003014e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305408.s", FUN_L14_00305408);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305600.s", FUN_L14_00305600);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305680.s", FUN_L14_00305680);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305758.s", FUN_L14_00305758);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305b18.s", FUN_L14_00305b18);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305d28.s", FUN_L14_00305d28);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003061d8.s", FUN_L14_003061d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003061f8.s", FUN_L14_003061f8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_0030621c.s", FUN_L14_0030621c);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00306b78.s", FUN_L14_00306b78);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00306ee0.s", FUN_L14_00306ee0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00307510.s", FUN_L14_00307510);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00307620.s", FUN_L14_00307620);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00307a80.s", FUN_L14_00307a80);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003087c0.s", FUN_L14_003087c0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00314e18.s", FUN_L14_00314e18);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00314f00.s", FUN_L14_00314f00);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00315290.s", FUN_L14_00315290);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00315920.s", FUN_L14_00315920);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003159d8.s", FUN_L14_003159d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00315d48.s", FUN_L14_00315d48);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00316748.s", FUN_L14_00316748);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003167c4.s", FUN_L14_003167c4);
