/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L17_002ea418.s", FUN_L17_002ea418);
INCLUDE_ASM("config/us/overlays/asm/FUN_L17_002f0040.s", FUN_L17_002f0040);
INCLUDE_ASM("config/us/overlays/asm/FUN_L17_002f0448.s", FUN_L17_002f0448);
