/* Level overlay code after runtime/startup; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/globals.h"
#include "asm.h"

#define NOT_SDA

#define MACRO_ADDR

/* In level 3, while the timer of state 5 is between 900 and 1100 ticks, throws four sparks off the moby. */
/* Ported from rac1-decomp (src/overlays/l03_kerwan/initonce_0022D028.c: func_L03_0022D028), where it is exact; names translated to the US level program. */

extern char D_L03_0016C960[];
extern float random_angle_radians(void) __asm__("FUN_00213308");
extern float random_float_between(float a, float b) __asm__("FUN_002132a8");
extern int FUN_L00_00257b90(int, int);
extern s32 scale_game_frames(s32) __asm__("func_001F96F8");
extern void FUN_L00_0024f7c8(void *, int, void *);
extern void FUN_L00_0026ced0(void *, void *, int, int, float, int);
extern void clear_vector(void *);
void build_spherical_offset(f32 *out, f32 scale, f32 a, f32 b) __asm__("FUN_00214db0");

void FUN_L03_0022c728(void) {
    char *g;
    char *m;
    float w[4];
    float v[4];
    int i;
    if (current_level_index != 3)
        return;
    g = D_L03_0016C960;
    if (*(int *)(g + 0x30) != 5)
        return;
    if (scale_game_frames(900) >= *(int *)(g + 0x34))
        return;
    if (*(int *)(g + 0x34) >= scale_game_frames(1100))
        return;
    m = *(char **)(g + 0x184);
    if (m == 0)
        return;
    for (i = 0; i < 4; i++) {
        float a, b;
        clear_vector(v);
        FUN_L00_0024f7c8(m, i % 2, w);
        a = random_angle_radians();
        b = random_angle_radians();
        build_spherical_offset(v, random_float_between(frame_time * 0.7f, frame_time * 2.2f), a, b);
        FUN_L00_0026ced0(w, v, 0x80808080, 0x808080, 147000.0f,
                         FUN_L00_00257b90(scale_game_frames(12), scale_game_frames(35)));
    }
}
