#ifndef LOMBYTE_RNC_RENDERING_GEOMETRY_TRANSFORM_SCALED_VERTEX_BATCH_H
#define LOMBYTE_RNC_RENDERING_GEOMETRY_TRANSFORM_SCALED_VERTEX_BATCH_H

#include "types.h"

struct VertexBatch {
    u8 pad_0[0x2C];
    s32 unk2C;
};

#endif /* LOMBYTE_RNC_RENDERING_GEOMETRY_TRANSFORM_SCALED_VERTEX_BATCH_H */
