#ifndef LOMBYTE_RNC_GAMEPLAY_STATE_PROCESS_GLOBAL_STATE_FLAGS_H
#define LOMBYTE_RNC_GAMEPLAY_STATE_PROCESS_GLOBAL_STATE_FLAGS_H

#include "types.h"

struct Globals_0013D408 {
    u8 pad_0[0x1D];
    u8 unk1D;
    u8 pad_1E[0x3];
};

#endif /* LOMBYTE_RNC_GAMEPLAY_STATE_PROCESS_GLOBAL_STATE_FLAGS_H */
