#ifndef LOMBYTE_RNC_GAMEPLAY_STATE_TRANSITION_DEFAULT_DRAW_H
#define LOMBYTE_RNC_GAMEPLAY_STATE_TRANSITION_DEFAULT_DRAW_H

#include "types.h"

struct Globals_0016045C {
    u8 pad_0[0x4];
    s16 unk4;
    u8 pad_6[0x2];
};

#endif /* LOMBYTE_RNC_GAMEPLAY_STATE_TRANSITION_DEFAULT_DRAW_H */
