/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/audio/music/music_stream_state.h"
#include "asm.h"

typedef struct {
    s32 state;
    u8 pad[0x20];
    s32 cur;
    s32 idx;
} S00203908;
typedef struct {
    u16 id;
    u16 pad;
    s32 v;
} P00203908;
extern S00203908 D_L00_00179410_00203908 __asm__("D_L00_00179410");
extern P00203908 D_00141968_00203908[] __asm__("D_00141968");
void FUN_001fed30_00203908(s32) __asm__("FUN_001fed30");
/* Starts help entry b with message a when no help is showing; pushes a to the help history. */
s32 FUN_L00_00203908(s32 a, s32 b) {
    S00203908 *s = &D_L00_00179410_00203908;
    if (s->state == 0 && s->cur == -1 && music_stream_state.secondary.handle == 0 &&
        music_stream_state.queued_secondary_track == s->cur && D_00141968_00203908[b].id != 0xFFFF) {
        s->idx = b;
        s->cur = a;
        FUN_001fed30_00203908(a);
        return 1;
    }
    return 0;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_00203E98.c: func_L00_00203FB8), where it is exact; names translated to the US level program. */

extern char *D_L00_0015F660;
extern char D_L00_00179410[];
extern unsigned char D_0014161B[];

/* When D_L00_00179410 is active, may set the 0x5A state to 5, then clears and resets the record. */
void FUN_L00_002039a0(void) {
    if (*(int *)(D_L00_00179410) != 0) {
        int v = *(int *)((char *)(*(int *)(D_L00_00179410 + 0x20) << 4) + (int)D_L00_0015F660 + 8);
        if (v != -1) {
            char *g = (char *)D_0014161B + 0x100B5;
            if (v == *(short *)(g + 0x54) - 0x7530) {
                if ((unsigned)(*(unsigned short *)(g + 0x5A) - 6) >= 2)
                    *(short *)(g + 0x5A) = 5;
            }
        }
        *(int *)(D_L00_00179410) = 0;
        *(int *)(D_L00_00179410 + 0x24) = -1;
        *(int *)(D_L00_00179410 + 0x20) = -1;
        *(int *)(D_L00_00179410 + 4) = 0;
    }
}
typedef struct {
    s32 a;
    u32 b;
} P;
extern P D_00141968[];
/* Clears the top bit of each of the 0x94 help records. */
void FUN_L00_00203a28(void) {
    s32 i;
    for (i = 0; i < 0x94; i++)
        D_00141968[i].b &= 0x7FFFFFFF;
}
