#ifndef LOMBYTE_RNC_VIDEO_DECODER_READ_CD_STREAM_SECTORS_H
#define LOMBYTE_RNC_VIDEO_DECODER_READ_CD_STREAM_SECTORS_H

#include "types.h"

struct CdStream {
    u8 pad_0[0x4];
    s32 unk4;
};

#endif /* LOMBYTE_RNC_VIDEO_DECODER_READ_CD_STREAM_SECTORS_H */
