#ifndef LOMBYTE_RNC_VIDEO_DECODER_RUN_VIDEO_DECODER_H
#define LOMBYTE_RNC_VIDEO_DECODER_RUN_VIDEO_DECODER_H

#include "types.h"

struct VideoDec {
    u8 pad_0[0xD9174];
    s32 unkD9174;
};

#endif /* LOMBYTE_RNC_VIDEO_DECODER_RUN_VIDEO_DECODER_H */
