#ifndef LOMBYTE_RNC_VIDEO_DECODER_VIDEO_DEC_MAIN_H
#define LOMBYTE_RNC_VIDEO_DECODER_VIDEO_DEC_MAIN_H

#include "types.h"

struct VideoDec {
    u8 pad_0[0xD9174];
    s32 unkD9174;
};

#endif /* LOMBYTE_RNC_VIDEO_DECODER_VIDEO_DEC_MAIN_H */
