/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

#define NOT_SDA

#define MACRO_ADDR

/* records, for entry arg, which of the 48 entries sit one grid step away */
/* Ported from rac1-decomp (PAL, src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_0030EB68), where it is exact; names translated to the US level program. */

typedef struct {
    float x;
    float y;
    int pad;
    char n[0x14];
    char rest[0x1170];
} Ent;

extern Ent D_L05_001D6880[];
float AbsoluteFloat(float input) __asm__("func_001F99C0");

void FUN_L05_0030d6a0(int arg) {
    int i;
    Ent *t = D_L05_001D6880;
    for (i = 0; i < 48; i++) {
        if (arg != i) {
            Ent *e = &t[arg];
            float x = e->x - t[i].x;
            float y = e->y - t[i].y;
            if (AbsoluteFloat(x) < 0.1f) {
                if (AbsoluteFloat(y - 16.0f) < 0.1f) e->n[0] = i;
                if (AbsoluteFloat(y + 16.0f) < 0.1f) e->n[2] = i;
            } else if (AbsoluteFloat(y) < 0.1f) {
                if (AbsoluteFloat(x - 16.0f) < 0.1f) e->n[1] = i;
                if (AbsoluteFloat(x + 16.0f) < 0.1f) e->n[3] = i;
            } else {
                if (AbsoluteFloat(x - 16.0f) < 0.1f) {
                    if (AbsoluteFloat(x - 16.0f) < 0.1f) e->n[5] = i;
                    if (AbsoluteFloat(x + 16.0f) < 0.1f) e->n[7] = i;
                } else if (AbsoluteFloat(x + 16.0f) < 0.1f) {
                    if (AbsoluteFloat(x - 16.0f) < 0.1f) e->n[4] = i;
                    if (AbsoluteFloat(x + 16.0f) < 0.1f) e->n[6] = i;
                }
            }
        }
    }
}
#include "qcopy.h"

/* Ported from rac1-decomp (PAL, src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_0030F130), where it is exact; names translated to the US level program. */

extern char D_0013E550[];
extern char D_L05_001671C0[];
extern float FUN_001f9b48(void *, void *);
extern int D_L05_0015F5CC;
extern int FUN_0022da68();
extern short D_L05_0015FFD8_d __asm__("D_L05_0015FFD8") __attribute__((sda));
extern short D_L05_00161D38_d __asm__("D_L05_00161D38") __attribute__((sda));
extern void FUN_L05_0030de90(void);
void enqueue_callback_list_1(int arg0, int arg1) __asm__("FUN_001f4600");
extern int func_0022ED80_i(int, int, void *) __asm__("FUN_0022da68");

void FUN_L05_0030dc68(char *m) {
    char *data = *(char **)(m + 0x78);
    int state = *(unsigned char *)(m + 0x20);
    char *base;
    char *tab;
    char *pos;
    char *q;
    char *o;
    float d;
    int idx;
    switch (state) {
    case 0:
        *(unsigned short *)(m + 0x34) |= 1;
        *(unsigned char *)(m + 0x20) = 1;
        *(unsigned char *)(m + 0x31) = 0;
        **(int **)(data + 4) = -1;
        break;
    case 1:
        if (*(int *)&D_L05_00161D38_d != D_L05_0015F5CC) {
            *(int *)&D_L05_00161D38_d = D_L05_0015F5CC;
            enqueue_callback_list_1(FUN_L05_0030de90, m);
        }
        pos = m + 0x10;
        tab = D_L05_001671C0;
        if (FUN_001f9b48(pos, tab) < 64.0f) {
            idx = **(int **)(data + 4);
            if (idx >= 0) {
                base = D_0013E550;
                o = *(char **)(base + idx * 0x70 + 0x88);
                if (o != 0) {
                    if (*(short *)(o + 0xA6) == 0x346) {
                        if (o != m) {
                            if (*(unsigned char *)(o + 0x20) == state) {
                                d = FUN_001f9b48(pos, tab);
                                if (!(d < FUN_001f9b48(o + 0x10, tab))) goto after;
                            }
                            q = base + 0x90;
                            *(char **)(base + **(int **)(data + 4) * 0x70 + 0x88) = m;
                            qcopy(**(int **)(data + 4) * 0x70 + q, pos);
                        }
                        goto after;
                    }
                }
            }
            **(int **)(data + 4) = func_0022ED80_i(0, 4, m);
        }
    after:
        if (*(int *)data >= 0) {
            if ((*(unsigned char **)&D_L05_0015FFD8_d)[*(int *)data * 256 + 0xBC] != 0) {
                func_0022ED80_i(1, 0, m);
                *(int *)(m + 0x94) = 0;
                *(unsigned char *)(m + 0x20) = 2;
            }
        }
        break;
    case 2:
        if (*(int *)(m + 0x94) != 0) *(int *)(m + 0x94) = 0;
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030de90.s", FUN_L05_0030de90);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030e1f8.s", FUN_L05_0030e1f8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030e508.s", FUN_L05_0030e508);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030e7f8.s", FUN_L05_0030e7f8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030f218.s", FUN_L05_0030f218);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030f408.s", FUN_L05_0030f408);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030f5c8.s", FUN_L05_0030f5c8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00314eb0.s", FUN_L05_00314eb0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003150f0.s", FUN_L05_003150f0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003156d0.s", FUN_L05_003156d0);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_003173A8), where it is exact; names translated to the US level program. */

extern short D_L05_00161EC0_d __asm__("D_L05_00161EC0") __attribute__((sda));
extern short D_L05_00161EC4_d __asm__("D_L05_00161EC4") __attribute__((sda));
extern short D_L05_00161EC8_d __asm__("D_L05_00161EC8") __attribute__((sda));
extern void FUN_001f99f8(void *);
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9bf8(void *, void *, float);

void FUN_L05_00315ee0(char *a, char *b, char *c) {
    float t;
    FUN_001f9bf8(b, a + 0xC0, *(float *)&D_L05_00161EC8_d);
    FUN_001f9a10(b, b, a + 0x10);
    *(float *)(b + 8) = *(float *)(b + 8) + *(float *)&D_L05_00161EC0_d;
    FUN_001f99f8(c);
    t = *(float *)&D_L05_00161EC4_d;
    *(float *)(c + 8) = *(float *)(a + 0x48);
    *(float *)(c + 4) = t * 0.017453292f;
}
/* Ported from rac1-decomp (PAL, src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_00317438), where it is exact; names translated to the US level program. */

extern char *D_L05_001B0930[];
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern float FUN_001fa580(float, float);

void FUN_L05_00315f70(char *moby) {
    int i = 0;
    char *data = *(char **)(moby + 0x78);
    char *tab = D_L05_001B0930[*(int *)(data + 0x68)];
    float ang = 0.0f;
    float step = 6.28318f / (float)(*(int *)tab - 1);
    for (; i < *(int *)tab; i++) {
        char *v = tab + 0x10 + i * 16;
        *(float *)v = FUN_001f9dc8(ang) * 3.5f;
        *(float *)(v + 4) = FUN_001f9de0(ang) * 3.5f;
        *(int *)(v + 8) = 0;
        FUN_001f9a10(v, v, moby + 0x10);
        ang = FUN_001fa580(ang, step);
    }
}
/* Ported from rac1-decomp (PAL, src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_00317538), where it is exact; names translated to the US level program. */

extern char D_L05_001671C0[];
extern char D_L05_00211B20[];
extern int is_point_inside_clip_volume_alt(void *, int) __asm__("FUN_00214720");
extern void FUN_L03_00291918(char *);

void FUN_L05_00316070(char *moby) {
    int *p = *(int **)(moby + 0x78);
    int i;
    int none = 1;
    for (i = 0; i < 8; p++, i++) {
        if (*p == -1) continue;
        if (is_point_inside_clip_volume_alt(D_L05_001671C0, *p) != 0) {
            none = 0;
            break;
        }
    }
    if (none) FUN_L03_00291918(D_L05_00211B20);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00316110.s", FUN_L05_00316110);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00316258.s", FUN_L05_00316258);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003166a0.s", FUN_L05_003166a0);
#include "sda.h"

/* Applies breast growth (D_L05_00161ED0) and big-head manipulators to
 * matching-class cutscene instances of the hoverboard girl. */
/* Ported from rac1-decomp (PAL, src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_00317E58), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x44];
    short n;
    char pad1[0x132];
    char *m[1];
} G;

extern G D_L05_0016CC60;
extern int D_L05_0015F5C4 MACRO_ADDR;
extern short D_L05_00161ED0_d __asm__("D_L05_00161ED0") __attribute__((sda));
extern unsigned char D_0015EDB0[] MACRO_ADDR;
extern unsigned char D_L05_0017C8A0[];
extern void FUN_L05_00316810(char *, int);
extern void attach_manipulator(void *arg0, s32 arg1, void *arg2) __asm__("FUN_0020cb10");

void FUN_L05_00316990(char *arg) {
    if (D_L05_0015F5C4 == 2 && (D_0015EDB0[0] != 0 || *(int *)&D_L05_00161ED0_d != 0)) {
        int i;
        for (i = 0; i < D_L05_0016CC60.n; i++) {
            char *moby = D_L05_0016CC60.m[i];
            if (*(short *)(moby + 0xA6) == *(short *)(arg + 0xA6)) {
                if (D_0015EDB0[0] != 0) {
                    unsigned char *q = D_L05_0017C8A0;
                    if (q[1] == 0) {
                        attach_manipulator(moby, 0, q);
                        *(float *)(q + 0x20) = 2.75f;
                        *(float *)(q + 0x24) = 2.75f;
                        *(float *)(q + 0x28) = 2.75f;
                    }
                }
                if (*(int *)&D_L05_00161ED0_d != 0) {
                    FUN_L05_00316810(moby, *(int *)(arg + 0x78));
                }
            }
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00317470.s", FUN_L05_00317470);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003180a0.s", FUN_L05_003180a0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00318a68.s", FUN_L05_00318a68);
/* Ported from rac1-decomp (PAL, src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_0031A0A8), where it is exact; names translated to the US level program. */

extern float D_0015ED6C;
extern float random_angle_radians_alt(void) __asm__("FUN_00213308");
extern int D_L05_0015F5C4;
extern short D_L05_00161F08_d __asm__("D_L05_00161F08") __attribute__((sda));

void FUN_L05_00318b98(unsigned char *moby) {
    float v;
    char *data = *(char **)(moby + 0x78);
    int g;
    *(float *)(moby + 0x2C) = *(float *)(*(char **)(moby + 0x24) + 0x24) * *(float *)&D_L05_00161F08_d;
    switch (moby[0x20]) {
    case 0:
        moby[0x20] = 1;
        *(float *)data = random_angle_radians_alt();
        *(float *)(data + 4) = *(float *)(moby + 0x18);
        break;
    case 1:
        g = D_L05_0015F5C4;
        if (g == 2) {
            moby[0x31] = 0;
            *(unsigned short *)(moby + 0x34) |= 1;
        } else {
            moby[0x31] = 1;
            *(unsigned short *)(moby + 0x34) &= 0xFFFE;
        }
        v = FUN_001fa580(*(float *)data, D_0015ED6C * 0.87266463f);
        *(float *)data = v;
        *(float *)(moby + 0x18) = *(float *)(data + 4) + FUN_001f9de0(v);
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00318c78.s", FUN_L05_00318c78);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00319208.s", FUN_L05_00319208);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003193a8.s", FUN_L05_003193a8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00319c28.s", FUN_L05_00319c28);
