/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003028c8.s", FUN_L12_003028c8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00302c58.s", FUN_L12_00302c58);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00302f30.s", FUN_L12_00302f30);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003032e8.s", FUN_L12_003032e8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00303370.s", FUN_L12_00303370);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00303540.s", FUN_L12_00303540);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00304218.s", FUN_L12_00304218);
extern int scale_ticks(int) __asm__("FUN_001f96f8");

#define NOT_SDA

#define MACRO_ADDR

/* Scale and play the vendor cue while its counter is below the limit. */
/* Ported from rac1-decomp (PAL, src/overlays/l12_hoven/vendor_002EDAA0.c: func_L12_00306178), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0xAC];
    short value;
} Level12VendorCounterData;

typedef struct {
    char pad0[0x78];
    Level12VendorCounterData *data;
} Level12VendorCounterMoby;

void FUN_L12_00304d98(Level12VendorCounterMoby *moby) {
    Level12VendorCounterData *data = moby->data;
    int count = scale_ticks(0x50);
    int value = data->value;
    if (value < count) {
        emit_rgba_draw_packet(0xAA, 0, 0, (count - value) * 0x50 / count);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00304e00.s", FUN_L12_00304e00);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003054b0.s", FUN_L12_003054b0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00306350.s", FUN_L12_00306350);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003064e8.s", FUN_L12_003064e8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00306828.s", FUN_L12_00306828);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003069d0.s", FUN_L12_003069d0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003076e0.s", FUN_L12_003076e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00307840.s", FUN_L12_00307840);
#include "qcopy.h"

/* per-frame update of a moby's timer and approach state */
/* Ported from rac1-decomp (PAL, src/overlays/l12_hoven/vendor_002EDAA0.c: func_L12_00308E98), where it is exact; names translated to the US level program. */

extern char D_0013E533[];
extern int FUN_001f96f8(int);
extern int FUN_001f9770(void *);
extern int FUN_L00_0025fcb8(char *, char *, float);
float AbsoluteFloat(float input) __asm__("func_001F99C0");

void FUN_L12_00307ab8(char *m) {
    char *d = *(char **)(m + 0x78);
    char *pad;
    if (*(unsigned char *)(m + 0x20) != 0) {
        if (*(int *)(d + 0x38) != 0) {
            *(short *)(d + 0xFE) = FUN_001f96f8(0xB4);
        }
        *(int *)(d + 0x38) = 0;
        if (FUN_001f9770(d + 0xFE)) {
            *(float *)(d + 0xF8) = *(float *)(d + 0xF4);
        } else {
            *(float *)(d + 0xF8) = *(float *)(d + 0xF4) + 5.0f;
        }
        if (FUN_L00_0025fcb8(m, d + 0x70, *(float *)(d + 0xF8)) != 2) {
            if (AbsoluteFloat(*(float *)(m + 0x18) - *(float *)(d + 0x78)) > 3.0f) {
                *(int *)(d + 0xB4) = 2;
            }
        }
        if (*(int *)(d + 0xB0) == 0) {
            pad = D_0013E533 + 0xE1D;
            *(int *)(d + 0xB0) = *(int *)(pad + 0x2080);
            qcopy(d + 0x70, pad + 0x80);
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003081b0.s", FUN_L12_003081b0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_00308350.s", FUN_L12_00308350);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003093c8.s", FUN_L12_003093c8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_003094a0.s", FUN_L12_003094a0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_0030be68.s", FUN_L12_0030be68);
INCLUDE_ASM("config/us/overlays/asm/FUN_L12_0030bff0.s", FUN_L12_0030bff0);
