/* Level overlay code after audio/music; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L00_001fb7e0.s", FUN_L00_001fb7e0);
