/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e22d8.s", FUN_L16_002e22d8);
#include "qcopy.h"

extern float D_L16_00161D78_sda __asm__("D_L16_00161D78") __attribute__((sda));
extern char *D_L16_0015FFD8_sda __asm__("D_L16_0015FFD8") __attribute__((sda));
extern u8 D_001413F4[];
extern s32 D_001413DC[];
extern char *D_L16_001B0930[];
extern u8 D_0013E550[];
extern u8 D_0013F350[];
extern float D_0015ED6C_e __asm__("D_0015ED6C");

typedef struct { char pad[0x74]; u8 active; char pad75[0x13]; char *owner; } L16Slot_e;

extern int FUN_L00_0028d8c0(void *, int);
extern int FUN_0022da68_i(int, int, void *) __asm__("FUN_0022da68");
extern void FUN_0022d798(int);
extern char *FUN_L00_0025a420(void *, int, int);
extern int FUN_L00_0025a478(void *, char *, void *, int, int *, float *, int, int);
extern float FUN_L00_00257c48(float, float);
extern void FUN_0020c828(char *);
extern int FUN_001f96f8(int);
extern void FUN_L00_0025d458(void *, void *);
extern void FUN_L00_0025d538(void *, void *);
extern void FUN_L00_0025ff38(float, void *, void *, int, int, void *, int);

typedef struct { s32 status; float amount; } L16Hit_e;

/* Update interaction ownership, damage responses and pursuit tracking. */
void FUN_L16_002e2b60(char *m) {
    L16Hit_e hit;
    char *d = *(char **)(m + 0x78);
    float zero;
    char *record;
    int response;

    *(float *)(m + 0x2C) = *(float *)(*(char **)(m + 0x24) + 0x24) * D_L16_00161D78_sda;
    if ((unsigned int)(*(unsigned char *)(m + 0x20) - 2) < 4) {
        if (!FUN_L00_0028d8c0(m, *(int *)(d + 0x190))) *(int *)(d + 0x190) = FUN_0022da68_i(0, 4, m);
    } else if (FUN_L00_0028d8c0(m, *(int *)(d + 0x190))) {
        int slot = *(int *)(d + 0x190);
        if (slot != -1) {
            L16Slot_e *s = (L16Slot_e *)(D_0013E550 + slot * 0x70);
            if (s->owner == m && s->active != 0) FUN_0022d798(slot);
        }
        *(int *)(d + 0x190) = -1;
    }
    hit.amount = zero = 0.0f;
    record = FUN_L00_0025a420(m, 0x330000, 0);
    response = FUN_L00_0025a478(m, record, d + 0x20, 0, &hit.status, &hit.amount, 0, 4);
    if (hit.status != 1 && *(unsigned char *)(m + 0x20) != 8) {
        *(float *)(d + 0x20) -= hit.amount;
        if (*(float *)(d + 0x20) <= zero || (D_001413F4[0] == 2 && hit.amount >= 2.0f)) response = 1;
        if (response > 0) {
            if (response >= 3) {
                if (response < 9) {
                    FUN_0022da68_i(3, 0, m);
                    *(unsigned char *)(d + 0x67) = 120;
                    *(float *)(d + 0x188) = FUN_L00_00257c48(30.0f, 50.0f) * 0.017453292f * D_0015ED6C_e;
                }
            } else {
                FUN_0022da68_i(3, 0, m);
                if (D_001413F4[0] != 2) FUN_0022da68_i(2, 0, m);
                {
                    int *child = (int *)(d + 0xC0), count = 3;
                    do {
                        char *pool = D_L16_0015FFD8_sda;
                        if (*child >= 0) FUN_0020c828(pool + (*child << 8));
                        child++;
                    } while (--count >= 0);
                }
                *(unsigned char *)(m + 0x20) = 8;
                *(int *)(d + 0x160) = FUN_001f96f8(90);
                *(unsigned char *)(d + 0x67) = 120;
            }
        }
        FUN_L00_0025d458(m, d + 0x60);
    }
    *(unsigned char *)(m + 0xA4) = 255;
    FUN_L00_0025d538(m, d + 0x60);
    if (*(int *)(d + 0xD0) != -1 && D_001413DC[0] != 22) {
        char *path = D_L16_001B0930[*(int *)(d + 0xD0)];
        FUN_L00_0025ff38(128.0f, m, d + 0x70, 0, 0, path + 0x10, *(int *)path);
    } else *(int *)(d + 0xB4) = 2;
    if (*(int *)(d + 0xB0) == 0) {
        char *player = D_0013F350;
        *(int *)(d + 0xB0) = *(int *)(player + 0x2080);
        qcopy(d + 0x70, player + 0x80);
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Advance a path segment and ease the remaining travel distance. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A1B58.c: func_L16_002E42F0), where it is exact; names translated to the US level program. */

extern f32 advance_accelerated_scalar_q(f32 *, f32 *, f32, f32, f32, f32) __asm__("FUN_00213f38");
extern float D_0015ED6C_q __asm__("D_0015ED6C");
extern float D_L16_00161D84_q __asm__("D_L16_00161D84") __attribute__((sda));
extern float FUN_001f9b48_q(void *) __asm__("FUN_001f9b48");
extern s32 truncate_float_to_s32_q(f32) __asm__("FUN_001fa6d0");
extern short D_0015ED70, D_L16_00161E40_q __asm__("D_L16_00161E40");
extern short D_L16_00161E44, D_L16_00161D80_q __asm__("D_L16_00161D80") __attribute__((sda));
extern void sample_camera_path_q(void *, s32, void *, void *, s32, f32) __asm__("FUN_00214e58");
extern void func_00215CA8_path42_q(float,void*,int,void*,void*,int) __asm__("FUN_00214e58");
extern float func_001F9D10_path42_q(void*,void*) __asm__("FUN_001f9b48");
extern float func_00214D88_path42_q(float,float,float,float,float*,float*) __asm__("FUN_00213f38");

int FUN_L16_002e2e88(char *m, char *path) {
    char *d = *(char **)(m+0x78);
    float progress = (float)*(int *)(d+0x168) + *(float *)(d+0x16C) + *(float *)(d+0x170) / *(float *)(d+0x174);
    int index = truncate_float_to_s32_q(progress);
    float speed;
    float distance, rate;
    char *position;
    *(int *)(d+0x168)=index;
    *(float *)(d+0x16C)=progress-(float)index;
    if(index<*(int *)path-1) {
    position=m+0x10;
    func_00215CA8_path42_q(progress,path,0,position,m+0x40,0);
    *(float *)(d+0x194)=*(float *)(m+0x18);
    speed=0.0f;
    distance=func_001F9D10_path42_q(position,path+(*(int *)path<<4));
    rate=D_L16_00161D84_q**(float *)&D_0015ED70;
    func_00214D88_path42_q(distance,rate,rate,*(float *)&D_L16_00161D80_q*D_0015ED6C_q,&speed,(float *)(d+0x170));
    return 0;
    }
    return 1;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e2fa0.s", FUN_L16_002e2fa0);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A1B58.c: func_L16_002E44B8), where it is exact; names translated to the US level program. */

extern float D_0015ED64;
extern void FUN_L00_002628d8(char *, char *, int, float, float);

void FUN_L16_002e3050(char *moby)
{
    float ticks = D_0015ED64;
    float a = ticks * 0.03f;
    float b = ticks * 0.3f;
    char *data = *(char **)(moby + 0x78);
    *(float *)(data + 0x144) = *(float *)(data + 0x17C);
    FUN_L00_002628d8(moby, data + 0xE0, 2, a, b);
}
/* Updates a moby effect and advances it when its linked object is ready. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A1B58.c: func_L16_002E6B70), where it is exact; names translated to the US level program. */

extern float D_0015ED6C;
extern float FUN_001fa580(float, float);
extern int FUN_L00_0028d8c0(void *, int);
extern int FUN_L16_002e5cd0(int);
extern short D_L16_00161E00_d __asm__("D_L16_00161E00") __attribute__((sda));
extern short D_L16_00161E04_d __asm__("D_L16_00161E04") __attribute__((sda));
extern short D_L16_00161E08_d __asm__("D_L16_00161E08") __attribute__((sda));
extern void FUN_0022da68(int, int, int);
extern void FUN_L16_002e58d8(void);
extern void FUN_L16_002e5d30_c(int) __asm__("FUN_L16_002e5d30");
extern void enqueue_callback_list_1_alt(void (*)(void), void *) __asm__("FUN_001f4600");
extern int func_0022ED80_6B70(int, int, void *) __asm__("FUN_0022da68");

void FUN_L16_002e5708(unsigned char *m) {
    char *d = *(char **)(m + 0x78);
    float cycle;
    int i;
    float *p;
    switch (m[0x20]) {
    case 0:
        m[0x20] = 1;
        m[0x30] = 0xFF;
        break;
    case 1:
        cycle = *(float *)(d + 0xC) + *(float *)&D_L16_00161E04_d * D_0015ED6C;
        *(float *)(d + 0xC) = cycle;
        if (cycle > 1.0f) *(float *)(d + 0xC) = cycle - 1.0f;
        if (FUN_L00_0028d8c0(m, *(int *)(d + 0x24)) == 0) {
            *(int *)(d + 0x24) = func_0022ED80_6B70(0, 4, m);
        }
        *(float *)(d + 8) = FUN_001fa580(*(float *)(d + 8),
                            *(float *)&D_L16_00161E00_d * 0.017453292f * D_0015ED6C);
        p = (float *)(d + 0x10);
        for (i = 0; i < 4; i++) {
            p[i] = FUN_001fa580(p[i],
                   ((float *)&D_L16_00161E08_d)[i] * 0.017453292f * D_0015ED6C);
        }
        if (m[0x31]) enqueue_callback_list_1_alt(FUN_L16_002e58d8, m);
        if (*(int *)(d + 0x20) != -1 && FUN_L16_002e5cd0(*(int *)(d + 0x20))) {
            *(int *)(m + 0x94) = 0;
            m[0x20] = 2;
            FUN_L16_002e5d30_c(*(int *)(d + 0x20));
        }
        break;
    case 2:
        if (!FUN_L16_002e5cd0(*(int *)(d + 0x20))) {
            m[0x20] = 1;
            *(int *)(m + 0x94) = *(int *)(*(char **)(m + 0x24) + 0x10);
        }
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e58d8.s", FUN_L16_002e58d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L16_002e5cd0.s", FUN_L16_002e5cd0);
/* picks the nearest moby in a list (skipping class 0x5A3) and acts on it */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A1B58.c: func_L16_002E7198), where it is exact; names translated to the US level program. */

/* D_L16_0015FFD8 is declared sda above (FUN_L16_002e2b60 loads it off $gp), but
   here retail loads it absolute: reach it from a neighbour, past whose size the
   assembler no longer uses $gp. */
extern float D_L16_00161D78_far __asm__("D_L16_00161D78");
#define D_L16_0015FFD8 (((char **)&D_L16_00161D78_far)[-(0x161D78 - 0x15FFD8) / 4])
extern char D_0013E533[];
extern float FUN_001f9b48(void *);
extern short *D_L16_001ABCC0[];
extern void FUN_0022da68(int, int, int);
extern float func_001F9D10_2E7198(void *, void *) __asm__("FUN_001f9b48");

void FUN_L16_002e5d30(int idx) {
    short *p = D_L16_001ABCC0[idx];
    char *best = 0;
    float bestd = 50000.0f;
    if (p != 0) {
        do {
            char *m = D_L16_0015FFD8 + ((*(unsigned short *)p & 0x7FFF) << 8);
            if (*(short *)(m + 0xA6) != 0x5A3) {
                float d = func_001F9D10_2E7198(D_0013E533 + 0xE9D, m + 0x10);
                if (d < bestd) {
                    bestd = d;
                    best = m;
                }
            }
        } while (*p++ >= 0);
        if (best != 0) {
            FUN_0022da68(0, 0, (int)best);
        }
    }
}
extern void FUN_L16_002e9ce0(void);
void enqueue_callback_list_1(int arg0, int arg1) __asm__("FUN_001f4600");

void FUN_L16_002e9df0(unsigned char *moby) {
    switch (moby[0x20]) {
    case 0:
        moby[0x20] = 1;
        break;
    case 1:
        enqueue_callback_list_1((int)FUN_L16_002e9ce0, (int)moby);
        break;
    }
}
