/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002e8628.s", FUN_L03_002e8628);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002e8730.s", FUN_L03_002e8730);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002e8870.s", FUN_L03_002e8870);
