/* Level overlay code after gameplay/camera; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

void FUN_00214db0(void *);
void FUN_001f9a10(void *, void *, void *);
void FUN_L00_00262cf0(void *a, void *b) { char buf[16]; FUN_00214db0(buf); FUN_001f9a10(a, buf, b); }
typedef struct { s32 v[19]; } T;
extern T D_L00_001E9060;
s32 FUN_001f96f8(s32);
void FUN_L00_00263d40(s32, s32);
void FUN_L00_00262d38(s32 i) {
    T t = D_L00_001E9060;
    if (i < 0) i = 0;
    if (i > 18) i = 18;
    FUN_L00_00263d40(t.v[i], FUN_001f96f8(0x49C));
}
