/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0031abe0.s", FUN_L05_0031abe0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0031c8e0.s", FUN_L05_0031c8e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0031cf58.s", FUN_L05_0031cf58);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0031d160.s", FUN_L05_0031d160);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00329358.s", FUN_L05_00329358);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003294c0.s", FUN_L05_003294c0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00329538.s", FUN_L05_00329538);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00329540.s", FUN_L05_00329540);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003296e0.s", FUN_L05_003296e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003298d8.s", FUN_L05_003298d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00329ce8.s", FUN_L05_00329ce8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0032a6e0.s", FUN_L05_0032a6e0);
