/* Level overlay code after math/conversion; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002509f8.s", FUN_L03_002509f8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_00250ae8.s", FUN_L03_00250ae8);
