/* Level overlay code after rendering; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00269290.s", FUN_L00_00269290);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002694f8.s", FUN_L00_002694f8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00269958.s", FUN_L00_00269958);
typedef struct { f32 v[4]; s32 x10; s32 x14; s16 x18; s16 x1a; s32 x1c; } S00269a70;
typedef struct { u8 p0[4]; s32 x4; u8 x8; u8 p9; s16 xa; f32 xc; u8 p10[0x10]; S00269a70 s; } O00269a70;
extern f32 D_0015ED60;
f32 FUN_001fa6c0(s32);
void FUN_001f9a68(void *, void *, f32);
void FUN_001f9a10(void *, void *, void *);
s32 FUN_L00_002371e0(s32, s32, f32);
s32 FUN_001f9770(void *);
void FUN_L00_00267a08(void *);
void FUN_L00_00269a70(O00269a70 *o) {
    S00269a70 *s = &o->s;
    o->xc = FUN_001fa6c0(s->x18 * (s->x1c - o->xa) / s->x1c + s->x1a) * 1000.0f;
    FUN_001f9a68(s, s, D_0015ED60 * -0.019999980926513672f + 1.0f);
    FUN_001f9a10(o->p10, o->p10, s);
    o->x8++;
    o->x4 = FUN_L00_002371e0(s->x14, s->x10, o->xa / FUN_001fa6c0(s->x1c));
    if (FUN_001f9770(&o->xa)) FUN_L00_00267a08(o);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00269b70.s", FUN_L00_00269b70);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/partupd_0026A130.c: func_L00_0026AB10), where it is exact; names translated to the US level program. */

extern int FUN_001f96f8(int);
extern int FUN_001f9740(void *);
extern void FUN_L00_00267a08(void *);

void FUN_L00_00269c70(char *m) {
    float *p;
    p = (float *)(m + 0x20);
    if (FUN_001f9740(p)) {
        FUN_L00_00267a08(m);
        return;
    }
    *(float *)(m + 0xC) += p[1];
    if (FUN_001f96f8(6) > *(int *)(m + 0x20)) {

        *(int *)(m + 4) = (*(int *)(m + 4) & 0xFFFFFF) | ((*(int *)(m + 0x20) * 127 / FUN_001f96f8(6)) << 24);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00269d20.s", FUN_L00_00269d20);
#include "eetypes.h"
#include "qcopy.h"
extern unsigned char *D_L00_001B20A0_0026a4c8 __asm__("D_L00_001B20A0") __attribute__((section(".data")));
unsigned char *FUN_L00_002678b8_0026a4c8(int) __asm__("FUN_L00_002678b8");
int FUN_001fa6d0_0026a4c8(float) __asm__("FUN_001fa6d0");
float FUN_001fa6c0_0026a4c8(int) __asm__("FUN_001fa6c0");
void FUN_L00_0026a4c8(u128 *a, u128 *b, int c, int d, int n, float f) { if (n) { unsigned char *m = FUN_L00_002678b8_0026a4c8(8); if (m) { int *e; qcopy(m + 0x10, a); e = (int *)(m + 0x20); *(int *)(m + 4) = c; m[9] = FUN_001fa6d0_0026a4c8(4.0f) - 0x60; m[3] = 0x48; m[1] = 0; *(int *)(m + 0xc) = 0; m[8] = 0; m[2] = *D_L00_001B20A0_0026a4c8; qcopy(e, b); *(short *)(m + 0xa) = n; e[6] = n; *(float *)&e[7] = f / FUN_001fa6c0_0026a4c8(n); e[4] = c; e[5] = d; } } }
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026a5b8.s", FUN_L00_0026a5b8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026a6f0.s", FUN_L00_0026a6f0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026a880.s", FUN_L00_0026a880);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026a9f0.s", FUN_L00_0026a9f0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026ac78.s", FUN_L00_0026ac78);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026b230.s", FUN_L00_0026b230);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026b500.s", FUN_L00_0026b500);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026b790.s", FUN_L00_0026b790);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026b910.s", FUN_L00_0026b910);
extern char D_L00_00166DC0_0026ba68[] __asm__("D_L00_00166DC0");
void FUN_001f9a28_0026ba68(void *, void *, void *) __asm__("FUN_001f9a28");
void FUN_L00_001ff500_0026ba68(void *, void *, float) __asm__("FUN_L00_001ff500");
void FUN_001f9a10_0026ba68(void *, void *, void *) __asm__("FUN_001f9a10");
int FUN_001f9770_0026ba68(void *) __asm__("FUN_001f9770");
void FUN_L00_00267a08_0026ba68(unsigned char *) __asm__("FUN_L00_00267a08");
int FUN_001f96f8_0026ba68(int) __asm__("FUN_001f96f8");
int FUN_001fa6d0_0026ba68(float) __asm__("FUN_001fa6d0");
void FUN_L00_0026ba68(unsigned char *p) { u128 t; int *e = (int *)(p + 0x20); p[8] += p[0x20]; if (e[1] == 0) { u128 *d = (u128 *)(p + 0x10); qcopy(d, (char *)e[2] + 0x10); FUN_001f9a28_0026ba68(&t, D_L00_00166DC0_0026ba68, d); FUN_L00_001ff500_0026ba68(&t, &t, 0.01f); FUN_001f9a10_0026ba68(d, d, &t); } else if (FUN_001f9770_0026ba68(p + 0xa)) FUN_L00_00267a08_0026ba68(p); else *(int *)(p + 4) = (FUN_001fa6d0_0026ba68(*(short *)(p + 0xa) * (127.0f / FUN_001f96f8_0026ba68(6))) << 24) | 0xffffff; }
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026bb70.s", FUN_L00_0026bb70);
typedef union { u128 q; float f[4]; } V26bca8;
extern float D_0015ED70_26bca8 __asm__("D_0015ED70");
extern int D_L00_0015F5CC_26bca8 __asm__("D_L00_0015F5CC");
int FUN_001f9770_26bca8(void *) __asm__("FUN_001f9770");
void FUN_L00_00267a08_26bca8(void *) __asm__("FUN_L00_00267a08");
float FUN_001fa6c0_26bca8(int) __asm__("FUN_001fa6c0");
int FUN_L00_002371e0_26bca8(int, int, float) __asm__("FUN_L00_002371e0");
void FUN_001f9a10_26bca8(void *, void *, void *) __asm__("FUN_001f9a10");
void FUN_001f9a68_26bca8(void *, void *, float) __asm__("FUN_001f9a68");
float FUN_002132a8_26bca8(float, float) __asm__("FUN_002132a8");
float FUN_001f9af0_26bca8(void *) __asm__("FUN_001f9af0");
void FUN_L00_001ff500_26bca8(void *, void *, float) __asm__("FUN_L00_001ff500");
int FUN_L00_00257b90_26bca8(int, int) __asm__("FUN_L00_00257b90");
int FUN_001f96f8_26bca8(int) __asm__("FUN_001f96f8");
void FUN_L00_0026bb70_26bca8(void *, void *, int, int, int, float, int, int, int) __asm__("FUN_L00_0026bb70");
void FUN_L00_0026bca8(unsigned char *m) {
    V26bca8 u, t, w;
    unsigned char *o = m + 0x20;
    unsigned char *p;
    float a, b;
    if (FUN_001f9770_26bca8(m + 0xA)) {
        FUN_L00_00267a08_26bca8(m);
        return;
    }
    p = m + 0x10;
    a = FUN_001fa6c0_26bca8(*(short *)(m + 0xA));
    b = FUN_001fa6c0_26bca8(*(short *)(o + 0x18));
    a *= *(float *)(o + 0x1C);
    a /= b;
    *(float *)(m + 0xC) = a;
    a = FUN_001fa6c0_26bca8(*(short *)(m + 0xA));
    *(int *)(m + 4) = FUN_L00_002371e0_26bca8(*(int *)(o + 0x14), *(int *)(o + 0x10), a / FUN_001fa6c0_26bca8(*(short *)(o + 0x18)));
    FUN_001f9a10_26bca8(p, p, o);
    *(float *)(o + 8) -= D_0015ED70_26bca8 * 14.6f;
    qcopy(&u, p);
    if (*(short *)(o + 0x1A) && (D_L00_0015F5CC_26bca8 & 1)) {
        w.q = 0;
        w.f[0] = FUN_002132a8_26bca8(-1.0f, 1.0f);
        w.f[1] = FUN_002132a8_26bca8(-1.0f, 1.0f);
        w.f[2] = FUN_002132a8_26bca8(-1.0f, 1.0f);
        t.q = w.q;
        b = FUN_001f9af0_26bca8(o);
        FUN_L00_001ff500_26bca8(&t, &t, b * FUN_002132a8_26bca8(0.15f, 0.25f));
        FUN_001f9a10_26bca8(&t, &t, o);
        FUN_001f9a68_26bca8(&t, &t, FUN_002132a8_26bca8(0.75f, 0.95f));
        FUN_L00_0026bb70_26bca8(p, &t, *(int *)(m + 4), *(int *)(o + 0x14), FUN_001f96f8_26bca8(FUN_L00_00257b90_26bca8(0xF, 0x1E)), *(float *)(m + 0xC), 0, m[2], m[3]);
    } else {
        FUN_001f9a68_26bca8(o, o, 0.96f);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026bed0.s", FUN_L00_0026bed0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026c088.s", FUN_L00_0026c088);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026c3d0.s", FUN_L00_0026c3d0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026c558.s", FUN_L00_0026c558);
#include "sda.h"
#include "qcopy.h"
typedef struct { u8 x0; u8 x1; u8 x2; u8 x3; u32 x4; u8 x8; u8 x9; u8 pa[2]; u32 xc; f32 a[4]; f32 b[4]; f32 c[4]; } E0026c6e8;
extern u8 *D_L00_001B20CC NOT_SDA;
E0026c6e8 *FUN_L00_002678b8(s32);
s32 FUN_00213260(s32);
s32 FUN_001fa6d0(f32);
void FUN_001f9a28(void *, void *, void *);
void FUN_L00_0026c6e8(void *pos, void *vel) {
    E0026c6e8 *e = FUN_L00_002678b8(0x13);
    u32 v;
    if (e == 0) return;
    v = (FUN_00213260(6) * 6 + 0x40) | 0x78404000;
    e->x4 = v;
    e->xc = v;
    e->x9 = FUN_001fa6d0(2.0f) + 0x20;
    e->x3 = 0x48;
    e->x1 = 3;
    e->x2 = *D_L00_001B20CC;
    qcopy(e->a, pos);
    qcopy(e->c, vel);
    FUN_001f9a28(e->b, pos, e->c);
    FUN_001f9a28(e->b, e->b, e->c);
    e->a[3] = 0.09f;
    e->b[3] = 0.5f;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/partupd_0026A130.c: func_L00_0026D690), where it is exact; names translated to the US level program. */

extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_L00_00267a08(void *);

void FUN_L00_0026c7f0(char *a) {
    int t;
    FUN_001f9a10(a + 0x10, a + 0x10, a + 0x30);
    FUN_001f9a10(a + 0x20, a + 0x20, a + 0x30);
    t = *(int *)(a + 4) + 0xFA000000;
    *(int *)(a + 4) = t;
    *(int *)(a + 0xC) = t;
    if (t < 0) FUN_L00_00267a08(a);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026c860.s", FUN_L00_0026c860);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026cbb0.s", FUN_L00_0026cbb0);
typedef struct { f32 v[4]; s32 x10; s32 x14; s16 x18; s16 x1a; f32 x1c; } S_0026ccb0_0026ccb0;
typedef struct { u8 p0[4]; s32 x4; u8 x8; u8 p9; s16 xa; f32 xc; u128 p10; S_0026ccb0_0026ccb0 s; } O_0026ccb0_0026ccb0;
typedef struct { f32 x, y, z, w_0026ccb0; } V_0026ccb0_0026ccb0;
extern f32 D_0015ED64_0026ccb0 __asm__("D_0015ED64");
extern s32 D_L00_0015F5CC_0026ccb0 __asm__("D_L00_0015F5CC");
f32 FUN_001fa6c0_0026ccb0(s32) __asm__("FUN_001fa6c0");
void FUN_001f9a68_0026ccb0(void *, void *, f32) __asm__("FUN_001f9a68");
void FUN_001f9a10_0026ccb0(void *, void *, void *) __asm__("FUN_001f9a10");
s32 FUN_L00_002371e0_0026ccb0(s32, s32, f32) __asm__("FUN_L00_002371e0");
s32 FUN_001f9770_0026ccb0(void *) __asm__("FUN_001f9770");
void FUN_L00_00267a08_0026ccb0(void *) __asm__("FUN_L00_00267a08");
float FUN_002132a8_0026ccb0(float, float) __asm__("FUN_002132a8");
float FUN_001f9af0_0026ccb0(void *) __asm__("FUN_001f9af0");
void FUN_L00_001ff500_0026ccb0(void *, void *, float) __asm__("FUN_L00_001ff500");
int FUN_001f96f8_0026ccb0(int) __asm__("FUN_001f96f8");
int FUN_L00_00257b90_0026ccb0(int, int) __asm__("FUN_L00_00257b90");
void FUN_L00_0026cbb0_0026ccb0(void *, void *, s32, s32, f32, int, int) __asm__("FUN_L00_0026cbb0");
void FUN_L00_0026ccb0(O_0026ccb0_0026ccb0 *o) {
    S_0026ccb0_0026ccb0 *s = &o->s;
    u128 *p;
    V_0026ccb0_0026ccb0 a, b, r;
    V_0026ccb0_0026ccb0 *q;
    f32 f;
    if (FUN_001f9770_0026ccb0(&o->xa)) {
        FUN_L00_00267a08_0026ccb0(o);
    } else {
    p = &o->p10;
    o->xc = FUN_001fa6c0_0026ccb0(o->xa) * s->x1c / FUN_001fa6c0_0026ccb0(s->x18);
    o->x4 = FUN_L00_002371e0_0026ccb0(s->x14, s->x10, FUN_001fa6c0_0026ccb0(o->xa) / FUN_001fa6c0_0026ccb0(s->x18));
    FUN_001f9a10_0026ccb0(p, p, s);
    s->v[2] -= D_0015ED64_0026ccb0 * 0.001f;
    qcopy(&a, p);
    if (s->x1a != 0 && (D_L00_0015F5CC_0026ccb0 & 1)) {
        *(u128 *)&r = 0;
        r.x = FUN_002132a8_0026ccb0(-1.0f, 1.0f);
        r.y = FUN_002132a8_0026ccb0(-1.0f, 1.0f);
        r.z = FUN_002132a8_0026ccb0(-1.0f, 1.0f);
        *(u128 *)&b = *(u128 *)&r;
        f = FUN_001f9af0_0026ccb0(s);
        q = &b;
        FUN_L00_001ff500_0026ccb0(q, q, f * FUN_002132a8_0026ccb0(0.21f, 0.25f));
        FUN_001f9a10_0026ccb0(q, q, s);
        FUN_001f9a68_0026ccb0(q, q, FUN_002132a8_0026ccb0(0.75f, 0.95f));
        FUN_L00_0026cbb0_0026ccb0(p, q, o->x4, s->x14, o->xc, FUN_001f96f8_0026ccb0(FUN_L00_00257b90_0026ccb0(15, 20)), 0);
    } else {
        FUN_001f9a68_0026ccb0(s, s, 0.96f);
    }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026ced0.s", FUN_L00_0026ced0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026d000.s", FUN_L00_0026d000);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026d1b0.s", FUN_L00_0026d1b0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026d470.s", FUN_L00_0026d470);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026d598.s", FUN_L00_0026d598);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026d700.s", FUN_L00_0026d700);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026daa0.s", FUN_L00_0026daa0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026dbe0.s", FUN_L00_0026dbe0);
static __inline__ void qcopy_0026dd20(void *dst, void *src)
{
    __asm__ __volatile__("lq $2,0x0(%1)\n\tsq $2,0x0(%0)" : : "r"(dst), "r"(src) : "$2", "memory");
}
extern unsigned char *D_L00_001B20EC_0026dd20[] __asm__("D_L00_001B20EC");
char *FUN_L00_002678b8_0026dd20(int) __asm__("FUN_L00_002678b8");
int FUN_001160d8_0026dd20(void) __asm__("FUN_001160d8");
int FUN_001fa6d0_0026dd20(float) __asm__("FUN_001fa6d0");
char *FUN_L00_0026dd20(void *pos, void *dir, int a, int b, float f) {
    char *o = FUN_L00_002678b8_0026dd20(0x1B);
    if (o) {
        char *q = o + 0x20;
        qcopy_0026dd20(o + 0x10, pos);
        o[8] = FUN_001160d8_0026dd20();
        *(int *)(o + 4) = a;
        o[9] = FUN_001fa6d0_0026dd20(4.0f) + 0x40;
        o[3] = 0x48;
        *(float *)(o + 0xC) = f;
        o[1] = 0;
        o[2] = D_L00_001B20EC_0026dd20[0][0];
        *(int *)(q + 0x18) = o[7];
        qcopy_0026dd20(q, dir);
        *(int *)(q + 0x10) = b;
        *(int *)(q + 0x14) = b;
    }
    return o;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/partupd_0026A130.c: func_L00_0026ECA0), where it is exact; names translated to the US level program. */

extern int FUN_001f9740(void *);
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_L00_00267a08(void *);

void FUN_L00_0026de00(char *a) {
    char *b = a + 0x20;
    FUN_001f9a10(a + 0x10, a + 0x10, b);
    *(unsigned *)(a + 4) = (*(unsigned *)(a + 4) & 0xFFFFFF) + (((*(int *)(b + 0x18) * *(int *)(b + 0x10)) / *(int *)(b + 0x14)) << 24);
    if (FUN_001f9740(a + 0x30)) FUN_L00_00267a08(a);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026de90.s", FUN_L00_0026de90);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026e150.s", FUN_L00_0026e150);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026e3a8.s", FUN_L00_0026e3a8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026e670.s", FUN_L00_0026e670);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026eb88.s", FUN_L00_0026eb88);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026ed28.s", FUN_L00_0026ed28);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026ee48.s", FUN_L00_0026ee48);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/partupd_0026A130.c: func_L00_0026FEE8), where it is exact; names translated to the US level program. */

extern int FUN_001f9770(void *);
extern void FUN_L00_00267a08(void *);

void FUN_L00_0026f048(char *a) {
    if (FUN_001f9770(a + 10) != 0) {
        FUN_L00_00267a08(a);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026f080.s", FUN_L00_0026f080);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026f280.s", FUN_L00_0026f280);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026f548.s", FUN_L00_0026f548);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026f660.s", FUN_L00_0026f660);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026f898.s", FUN_L00_0026f898);
typedef float V4[4] __attribute__((aligned(16)));
extern char D_L00_00166DC0[];
int FUN_001f9770(void *);
void FUN_L00_00267a08(void *);
void FUN_001f9a28(void *, void *, void *);
float FUN_001f9af0(void *);
void FUN_L00_001ff500(void *, void *, float);
void FUN_001f9a68(void *, void *, float);
void FUN_001f9a10(void *, void *, void *);
int FUN_L00_002371e0(int, int, float);
void FUN_L00_0026fa00(char *p) {
    V4 d;
    int *q = (int *)(p + 0x20);
    int n, k;
    if (FUN_001f9770(p + 0xA)) {
        FUN_L00_00267a08(p);
        return;
    }
    FUN_001f9a28(d, D_L00_00166DC0, q);
    if (5.0f < FUN_001f9af0(d)) FUN_L00_001ff500(d, d, 1.25f);
    else FUN_001f9a68(d, d, 0.25f);
    FUN_001f9a10(p + 0x10, q, d);
    n = q[5];
    k = *(short *)(p + 0xA) - n;
    k = k < 0 ? -k : k;
    *(int *)(p + 4) = FUN_L00_002371e0(0, q[4], (float)(n - k) / (float)n);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026fb00.s", FUN_L00_0026fb00);
typedef struct { f32 v[4]; } V0026fc38 __attribute__((aligned(16)));
typedef struct { s32 x0; u8 *x4; s32 x8; } S0026fc38;
typedef struct { u8 p0[2]; u8 x2; u8 p3; s32 x4; u8 x8; u8 p9; s16 xa; f32 xc; u8 p10[0x10]; S0026fc38 s; } O0026fc38;
extern f32 D_L00_00160200_0026fc38 __asm__("D_L00_00160200") __attribute__((sda));
extern s32 D_L00_00160204_0026fc38 __asm__("D_L00_00160204") __attribute__((sda));
extern f32 D_L00_00160208_0026fc38 __asm__("D_L00_00160208") __attribute__((sda));
extern u8 D_L00_0016020C_0026fc38 __asm__("D_L00_0016020C") __attribute__((sda));
extern u8 D_L00_00166DC0_0026fc38[] __asm__("D_L00_00166DC0");
extern u8 *D_L00_001B211C_0026fc38 __asm__("D_L00_001B211C") __attribute__((section(".data")));
void FUN_001f9a28_0026fc38(void *, void *, void *) __asm__("FUN_001f9a28");
void FUN_L00_001ff500_0026fc38(void *, void *, f32) __asm__("FUN_L00_001ff500");
void FUN_001f9a10_0026fc38(void *, void *, void *) __asm__("FUN_001f9a10");
s32 FUN_001fa6d0_0026fc38(f32) __asm__("FUN_001fa6d0");
void FUN_L00_00267a08_0026fc38(void *) __asm__("FUN_L00_00267a08");
void FUN_L00_0026fc38(O0026fc38 *o) {
    V0026fc38 t;
    S0026fc38 *s = &o->s;
    o->xc = D_L00_00160200_0026fc38;
    o->x4 = D_L00_00160204_0026fc38;
    o->x8 += D_L00_0016020C_0026fc38;
    FUN_001f9a28_0026fc38(&t, s->x4 + 0x10, D_L00_00166DC0_0026fc38);
    FUN_L00_001ff500_0026fc38(&t, &t, D_L00_00160208_0026fc38);
    FUN_001f9a10_0026fc38(o->p10, s->x4 + 0x10, &t);
    o->x2 = D_L00_001B211C_0026fc38[FUN_001fa6d0_0026fc38((f32)(s->x8 / 2))];
    s->x8++;
    if (s->x8 >= 0x1F) s->x8 = 0;
    if (o->xa == 0) FUN_L00_00267a08_0026fc38(o);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026fd28.s", FUN_L00_0026fd28);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0026ff10.s", FUN_L00_0026ff10);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00270708.s", FUN_L00_00270708);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/partupd_0026A130.c: func_L00_002715B0), where it is exact; names translated to the US level program. */

extern int FUN_001f9770(void *);
extern void FUN_L00_00267a08(void *);

void FUN_L00_00270710(char *a) {
    if (*(short *)(a + 0xA) != -1) {
        if (FUN_001f9770(a + 0xA) != 0) {
            FUN_L00_00267a08(a);
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00270758.s", FUN_L00_00270758);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00270948.s", FUN_L00_00270948);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002710a0.s", FUN_L00_002710a0);
