/* Level overlay code after start; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

typedef struct {
    s16 f00;
    u8 f02;
    u8 f03;
    s16 f04;
    u16 f06;
    s16 f08;
    s16 f0a;
    s16 f0c;
    u8 f0e;
    u8 f0f;
} L00Entry;

extern L00Entry D_L00_00166000[8];
extern f32 FUN_001fa6c0(s32);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern f32 FUN_001f9dc8(f32);

/* FUN_L00_001eaa08 is the executable function of the same bytes (src/gameplay). */

