/* Level overlay code after storage/stash; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00293ed0.s", FUN_L00_00293ed0);
