/* Level overlay code after ui/help; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L15_001ff938.s", FUN_L15_001ff938);
#define NOT_SDA

#define MACRO_ADDR

/* Show the indexed help prompt when its flag and message are active. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/help_001FFED0.c: func_L15_00200D20), where it is exact; names translated to the US level program. */

extern unsigned char D_0013E05A[];
extern unsigned char D_0013E533[];
extern void FUN_L00_00207330(int, int);

void FUN_L15_00200788(void) {
    unsigned char *base = D_0013E533 + 0xE1D;
    int index = *(int *)(base + 0x10B8);
    if (index >= 0 && *(D_0013E05A + 0x4C6 + index) != 0) {
        int first = *(int *)(base + 0x1090);
        if (first != 0) {
            FUN_L00_00207330(first, *(int *)(base + 0x2080));
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002007d8.s", FUN_L15_002007d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_00208ca8.s", FUN_L15_00208ca8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_00209450.s", FUN_L15_00209450);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0020a328.s", FUN_L15_0020a328);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_00215e58.s", FUN_L15_00215e58);
/* Select the message associated with the current help mode. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/help_001FFED0.c: func_L15_0021B2C8), where it is exact; names translated to the US level program. */

extern void FUN_L15_00216c38(int, int);

void FUN_L15_0021ab60(void) {
    switch (D_0013E533[0x2EC1]) {
    case 0: FUN_L15_00216c38(0, 1); break;
    case 2: FUN_L15_00216c38(0x5A, 1); break;
    case 3: FUN_L15_00216c38(0x53, 1); break;
    }
}
