/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0029f990.s", FUN_L00_0029f990);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0029fcd0.s", FUN_L00_0029fcd0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0029ff58.s", FUN_L00_0029ff58);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a02b0.s", FUN_L00_002a02b0);
