/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

#define NOT_SDA

#define MACRO_ADDR

#include "qcopy.h"

/* Builds two direction vectors from a table and relative to a moby, then hands them to the L04 effect spawner. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002B0068.c: func_L04_002C5938), where it is exact; names translated to the US level program. */

extern char D_L04_001D2C90[];
extern short D_L04_001618B0_d __asm__("D_L04_001618B0") __attribute__((sda));
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9cf8(void *, void *, void *);
extern void FUN_L04_002c41e0(void *, void *, void *, int, float, float);

void FUN_L04_002c45b8(char *a, int i, int j, int k) {
    float v0[4], v10[4];
    char *pi, *pj;
    pi = D_L04_001D2C90 + i * 16;
    qcopy(v0, pi);
    v0[3] = 1.0f;
    FUN_001f9cf8(v0, v0, a + 0xC0);
    FUN_001f9a10(v0, v0, a + 0x10);
    pj = D_L04_001D2C90 + j * 16;
    qcopy(v10, pj);
    v10[3] = 1.0f;
    FUN_001f9cf8(v10, v10, a + 0xC0);
    FUN_001f9a10(v10, v10, a + 0x10);
    FUN_L04_002c41e0(a, v0, v10, k, *(float *)(pi + 0xC) * *(float *)&D_L04_001618B0_d, *(float *)(pj + 0xC) * *(float *)&D_L04_001618B0_d);
}
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002B0068.c: func_L04_002C5A50), where it is exact; names translated to the US level program. */

extern short D_L04_001618C0_d __asm__("D_L04_001618C0") __attribute__((sda));
extern short D_L04_001618C4_d __asm__("D_L04_001618C4") __attribute__((sda));
extern short D_L04_001618C8_d __asm__("D_L04_001618C8") __attribute__((sda));
extern short D_L04_001618CC_d __asm__("D_L04_001618CC") __attribute__((sda));
extern short D_L04_001618D0_d __asm__("D_L04_001618D0") __attribute__((sda));
extern short D_L04_001618D4_d __asm__("D_L04_001618D4") __attribute__((sda));
extern short D_L04_001618D8_d __asm__("D_L04_001618D8") __attribute__((sda));
extern short D_L04_001618DC_d __asm__("D_L04_001618DC") __attribute__((sda));
extern void FUN_L04_002c45b8(char *a, int i, int j, int k);

void FUN_L04_002c46d0(char *a)
{
    FUN_L04_002c45b8(a, 0, 1, *(int *)&D_L04_001618C0_d);
    FUN_L04_002c45b8(a, 2, 3, *(int *)&D_L04_001618C4_d);
    FUN_L04_002c45b8(a, 4, 5, *(int *)&D_L04_001618C8_d);
    FUN_L04_002c45b8(a, 5, 6, *(int *)&D_L04_001618CC_d);
    FUN_L04_002c45b8(a, 6, 7, *(int *)&D_L04_001618D0_d);
    FUN_L04_002c45b8(a, 8, 9, *(int *)&D_L04_001618C8_d);
    FUN_L04_002c45b8(a, 9, 10, *(int *)&D_L04_001618CC_d);
    FUN_L04_002c45b8(a, 10, 11, *(int *)&D_L04_001618D0_d);
    FUN_L04_002c45b8(a, 12, 13, *(int *)&D_L04_001618D4_d);
    FUN_L04_002c45b8(a, 14, 15, *(int *)&D_L04_001618D4_d);
    FUN_L04_002c45b8(a, 16, 17, *(int *)&D_L04_001618D8_d);
    FUN_L04_002c45b8(a, 20, 21, *(int *)&D_L04_001618D8_d);
    FUN_L04_002c45b8(a, 18, 19, *(int *)&D_L04_001618DC_d);
    FUN_L04_002c45b8(a, 22, 23, *(int *)&D_L04_001618DC_d);
}

INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002aee30.s", FUN_L04_002aee30);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002af058.s", FUN_L04_002af058);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002ce080.s", FUN_L04_002ce080);
