/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002aa670.s", FUN_L00_002aa670);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002ac910.s", FUN_L00_002ac910);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002acad8.s", FUN_L00_002acad8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002acbf0.s", FUN_L00_002acbf0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002ace70.s", FUN_L00_002ace70);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002acfd8.s", FUN_L00_002acfd8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002ad410.s", FUN_L00_002ad410);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002adb30.s", FUN_L00_002adb30);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002af450.s", FUN_L00_002af450);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002af5b8.s", FUN_L00_002af5b8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002af8b0.s", FUN_L00_002af8b0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002afa48.s", FUN_L00_002afa48);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002afc70.s", FUN_L00_002afc70);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002aff50.s", FUN_L00_002aff50);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002affa8.s", FUN_L00_002affa8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002b03a0.s", FUN_L00_002b03a0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002b1af0.s", FUN_L00_002b1af0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002b1de0.s", FUN_L00_002b1de0);
