/* Level overlay code after gameplay/state; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L07_0028a440.s", FUN_L07_0028a440);
