/* Level overlay code after math/rotations; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

/* Splits value into its truncated whole part (stored to *whole) and returns the fraction. */
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00200228.s", FUN_L00_00200228);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00200260.s", FUN_L00_00200260);
