/* Level overlay code after ui/help; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L01_0023cf98.s", FUN_L01_0023cf98);
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_00240ed8.s", FUN_L01_00240ed8);
