/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"
#include "eetypes.h"
#include "qcopy.h"
#include "qzero.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002f9810.s", FUN_L01_002f9810);
typedef struct {
    f32 sway;
    f32 dir;
    s32 timer;
} SwayVars;

typedef struct {
    u8 pad0[0x10];
    u8 pos[0x10];
    u8 state;
    u8 pad21[0x27];
    f32 rotz;
    u8 pad4c[0x2C];
    SwayVars *pvars;
} SwayMoby;

typedef struct {
    s64 t;
    u8 pad8[8];
    void *moby;
    s32 flags;
    s32 x18;
    s32 x1c;
    s32 x20;
} CollQuery;

extern void FUN_L00_0025d1b8();
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern s32 FUN_001160d8(void);
extern void FUN_001f99f8(void *);
extern void FUN_L00_001f2868(void *, s32, void *, void *, f32);
extern s32 FUN_001f9740(void *);
extern s32 FUN_001f96f8(s32);
extern f32 FUN_001fa580(f32, f32);
extern f32 D_0015ED6C;

void FUN_L01_002f9bf0(SwayMoby *m) {
    SwayVars *v;
    CollQuery q;

    v = m->pvars;
    if (m->state == 0) {
        FUN_L00_0025d1b8(m);
        m->state = 1;
        v->sway = random_float_between(-1.0f, 1.0f);
        v->dir = (FUN_001160d8() & 1) ? 1.0f : -1.0f;
    }
    q.moby = m;
    q.flags = 0x10001;
    q.x1c = 0;
    FUN_001f99f8(&q);
    q.x20 = 0;
    FUN_L00_001f2868(m->pos, 0x10, m, &q, 1.2f);
    if (v->dir == v->sway) {
        if (FUN_001f9740(&v->timer)) {
            v->dir = -v->dir;
            v->timer = FUN_001f96f8(0x5A);
        }
    }
    v->sway += D_0015ED6C * 4.0f * v->dir;
    if (v->sway > 1.0f) {
        v->sway = 1.0f;
    }
    if (v->sway < -1.0f) {
        v->sway = -1.0f;
    }
    m->rotz = FUN_001fa580(m->rotz, D_0015ED6C * -12.566371f * v->sway);
}
typedef union { u128 q; f32 f[4]; } BurstVec;

typedef struct {
    u32 c[3];
} BurstColors;

typedef struct {
    u8 pad0[0xA6];
    s16 oclass;
} BurstClassMoby;

typedef struct {
    u8 pad0[0x20];
    BurstClassMoby *moby;
} BurstTarget;

typedef struct {
    u8 pad0[0x10];
    BurstVec pos;
    u8 pad20[0x84];
    u8 bA4;
    u8 padA5[0xD];
    s16 id;
} BurstMoby;

extern s32 D_0015ED84;
extern s32 D_0014C190[][64];
extern s32 D_L01_001BA950[];
typedef struct {
    u8 pad0[0x454];
    u8 collected[1];
} BurstLevelState;
extern BurstLevelState D_L01_001BB6B0;
extern BurstColors D_L01_00161C60;
extern void *FUN_L00_0025a420(void *, s32, s32);
extern void FUN_0020c828(void *);
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern s32 random_integer_below(s32) __asm__("FUN_00213260");
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern void FUN_001f9bf8(void *, void *, f32);
extern void FUN_001f9a10(void *, void *, void *);
extern int FUN_L00_00257b90(int lo, int hi);
extern void FUN_L01_002f8530(void *, void *, u32, s32, f32, f32, f32, f32, s32);

void FUN_L01_002f9d80(BurstMoby *self) {
    BurstTarget *t;
    BurstColors colors;
    BurstVec dir;
    BurstVec pos;
    f32 r;
    f32 ang;
    s32 i;

    t = FUN_L00_0025a420(self, 0x830000, 0);
    if (D_L01_001BB6B0.collected[self->id] != 0
        || (D_0014C190[D_0015ED84][self->id >> 5] >> (self->id & 0x1F)) & 1) {
        FUN_0020c828(self);
    }
    if (t != NULL && t->moby->oclass == 0x2AE) {
        for (i = 0; i < 20; i++) {
            colors = D_L01_00161C60;
            pos.q = 0;
            pos.f[0] = random_float_between(-D_0015ED6C, D_0015ED6C);
            pos.f[1] = random_float_between(-D_0015ED6C, D_0015ED6C);
            pos.f[2] = random_float_between(-D_0015ED6C, D_0015ED6C);
            dir.q = pos.q;
            r = random_float_between(2.0f, 3.0f);
            ang = random_angle_radians();
            pos.f[0] = FUN_001f9dc8(ang) * r;
            pos.f[1] = FUN_001f9de0(ang) * r;
            pos.f[2] = 0.0f;
            FUN_001f9bf8(&dir, &dir, random_float_between(D_0015ED6C * 5.0f, D_0015ED6C * 20.0f));
            FUN_001f9a10(&pos, &pos, &self->pos);
            FUN_L01_002f8530(&pos, &dir, colors.c[random_integer_below(3)], FUN_L00_00257b90(0xB4, 0x12C), 0.05f, 1.0f, 1.0f, 0.75f, 0);
        }
        D_0014C190[D_0015ED84][self->id >> 5] |= 1 << (self->id & 0x1F);
        D_L01_001BA950[self->id >> 5] |= 1 << (self->id & 0x1F);
        FUN_0020c828(self);
    } else {
        self->bA4 = 0xFF;
    }
}
typedef struct {
    u128 target;
    s32 owner;
    s32 color;
} BeamVars;

typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 pad20[0xC];
    f32 scale;
    u8 b30;
    u8 b31;
    s16 h32;
    u8 pad34[0xC];
    f32 rx;
    f32 ry;
    f32 rz;
    u8 pad4c[0x2C];
    BeamVars *pvars;
} BeamMoby;

extern void *spawn_beam_moby(s32 oclass) __asm__("FUN_0020c4f8");
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
void FUN_L00_002502f0(void *, s32, s32, s32);
void FUN_L00_0026daa0(void *, u32, s32, s32, f32);
extern void FUN_L00_00250df8();

BeamMoby *FUN_L01_002fa068(s32 owner, u128 *pos, u128 *target, s32 color) {
    u128 p;
    u128 t;
    BeamMoby *m;
    BeamVars *v;
    u128 *pp;
    u128 *tp;

    pp = &p;
    tp = &t;
    p = *pos;
    t = *target;
    m = spawn_beam_moby(0x2D2);
    if (m != 0) {
        v = m->pvars;
        v->owner = owner;
        m->b30 = 0x7F;
        m->h32 = 0x7F;
        m->b31 = 1;
        m->scale *= 0.5f;
        FUN_L00_002502f0(m, 0x7F, 0x7F, 0x7F);
        m->rx = random_angle_radians();
        m->ry = random_angle_radians();
        m->rz = random_angle_radians();
        qcopy(&m->pos, pp);
        qcopy(&v->target, tp);
        v->color = color;
        FUN_L00_0026daa0(m, 0x2F00007F, color, -1, 210000.0f);
        FUN_L00_0026daa0(m, 0x4F004F7F, v->color, -1, 115500.0f);
        FUN_L00_00250df8(m);
    }
    return m;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002fa1b0.s", FUN_L01_002fa1b0);
typedef union { u128 q; f32 f[4]; } Vec4;

typedef struct {
    u128 vel;
    void *coll;
    u8 sound[4];
} DropVars;

typedef struct {
    u8 pad0[0x10];
    Vec4 pos;
    u8 pad20[0x58];
    DropVars *vars;
    u8 pad7C[0x2A];
    u16 hA6;
} DropMoby;

typedef struct {
    u128 dir;
    DropMoby *owner;
    s32 flags;
    u8 b28;
    u8 b29;
    u16 id;
    f32 scale;
    s32 count;
} DropProbe;

extern f32 FUN_001f96b0(f32);
extern void FUN_001f9a10(void *, void *, void *);
extern f32 FUN_001f9b80(void *, void *);
extern s32 FUN_001efa68(void *, void *, s32, void *, void *);
extern s32 probe_world_sphere(f32, void *, s32, void *, void *) __asm__("FUN_L00_001f2868");
extern void FUN_L01_002fa1b0(void *, void *, s32, f32, f32);
void FUN_0020c828(void *);
extern u8 D_L01_00167240[];
extern u128 D_L01_001742E0;

void FUN_L01_002fa4c0(DropMoby *m) {
    DropVars *v;
    u128 *pos;
    Vec4 prev;
    DropProbe probe;
    u128 tmp;
    f32 a;
    f32 b;
    f32 zero;
    f32 one;
    f32 ten;
    f32 half;

    v = m->vars;
    pos = &m->pos.q;
    qcopy(&prev, pos);
    zero = 0.0f;
    one = 1.0f;
    ten = 10.0f;
    a = FUN_001f96b0(ten);
    b = FUN_001f96b0(ten);
    b = b * FUN_001f96b0(ten);
    ((f32 *)&v->vel)[2] -= (a * zero + one) * 2.0f / b;
    FUN_001f9a10(pos, pos, &v->vel);
    if (m->pos.f[0] < zero || m->pos.f[1] < zero || m->pos.f[2] < zero
        || FUN_001f9b80(pos, D_L01_00167240) > 64.0f) {
        FUN_0020c828(m);
        return;
    }
    probe.owner = m;
    probe.flags = 0x10001;
    probe.scale = one;
    probe.count = 1;
    qcopy(&probe.dir, &v->vel);
    ((f32 *)&probe.dir)[2] = one;
    ((f32 *)&probe.dir)[3] = 5627.9248f;
    probe.b28 = 1;
    probe.b29 = 1;
    probe.id = m->hA6;
    if (FUN_001f9740(v->sound) != 0) {
        tmp = m->pos.q;
        FUN_L01_002fa1b0(m, &tmp, 0, 0.5f, zero);
        FUN_0020c828(m);
    } else if (FUN_001efa68(&prev, pos, 0, v->coll, &probe) != 0) {
        qcopy(pos, &D_L01_001742E0);
        tmp = m->pos.q;
        FUN_L01_002fa1b0(m, &tmp, 0, 0.5f, zero);
        FUN_0020c828(m);
    } else {
        half = 0.5f;
        if (probe_world_sphere(half, pos, 0x10, v->coll, &probe) != 0) {
            tmp = m->pos.q;
            FUN_L01_002fa1b0(m, &tmp, 0, half, zero);
            FUN_0020c828(m);
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002fa800.s", FUN_L01_002fa800);
typedef struct {
    u8 pad0[0xA6];
    s16 type;
} Moby;

typedef struct {
    u8 pad0[0x44];
    s16 count;
    u8 pad46[0x178 - 0x46];
    Moby *list[1];
} MobyList;

typedef struct {
    u8 b0;
    u8 active;
    u8 pad2[0x1E];
    f32 x;
    f32 y;
    f32 z;
} Effect;

extern s32 D_L01_0015F5C4;
extern u8 D_0015EDB0;
extern MobyList D_L01_0016CCE0;
extern Effect D_L01_0017C8C0;
extern void FUN_0020cb10(void *, int, void *);

void FUN_L01_002fac80(void) {
    s32 i;

    if (D_L01_0015F5C4 == 2 && D_0015EDB0 != 0) {
        for (i = 0; i < D_L01_0016CCE0.count; i++) {
            if (D_L01_0016CCE0.list[i]->type == 0x32B && D_L01_0017C8C0.active == 0) {
                FUN_0020cb10(D_L01_0016CCE0.list[i], 0, &D_L01_0017C8C0);
                D_L01_0017C8C0.z = D_L01_0017C8C0.y = D_L01_0017C8C0.x = 2.75f;
            }
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002fad68.s", FUN_L01_002fad68);
typedef union { u128 q; f32 f[4]; } PendVec4;

typedef struct {
    u8 pad0[0x60];
    PendVec4 pivot;
    f32 swing;
    s32 sound;
} PendulumVars;

typedef struct {
    u8 pad0[0x10];
    PendVec4 pos;
    u8 state;
    u8 pad21[0x23];
    f32 rot_x;
    f32 rot_z;
    u8 pad4c[0x2C];
    PendulumVars *vars;
    u8 pad7c[0x34];
    u8 id;
    u8 padB1[0xB];
    u8 trigger;
} PendulumMoby;

extern s32 D_0015ED84 __attribute__((sda));
extern u8 D_0014C050[];
extern u8 D_0013E550[];
extern int FUN_L00_0028d8c0(void *, int);
extern void FUN_0022d798(int);
extern s32 FUN_0022da68(s32, s32, void *);
extern void FUN_001f9a10(void *, void *, void *);
extern f32 FUN_001f9dc8(f32);
extern f32 FUN_001f9de0(f32);

void FUN_L01_002fb8a8(PendulumMoby *self) {
    PendulumVars *v;
    PendVec4 arm;
    PendVec4 d;
    s32 h;
    u8 *voice;

    v = self->vars;
    switch (self->state) {
    case 0:
        qcopy(&v->pivot, &self->pos);
        v->swing = 1.0f;
        self->state = 1;
        v->sound = -1;
        break;
    case 1:
        if (self->trigger == 2 || D_0014C050[self->id + D_0015ED84 * 16] == 0xFF) {
            self->state = 2;
            self->trigger = 0;
        }
        break;
    case 2:
        v->swing -= D_0015ED6C * 0.5f;
        if (v->swing < 0.0f) {
            v->swing = 0.0f;
        }
        if (v->swing == 0.0f) {
            h = v->sound;
            if (h != -1) {
                voice = D_0013E550 + h * 0x70;
                if (*(void **)(voice + 0x88) == self && voice[0x74] != 0) {
                    FUN_0022d798(h);
                }
            }
            v->sound = -1;
            self->state = 1;
        } else if (!FUN_L00_0028d8c0(self, v->sound)) {
            v->sound = FUN_0022da68(0, 4, self);
        }
        break;
    }
    self->rot_x = v->swing * 0.62831855f;
    arm.q = 0;
    arm.f[2] = -11.0f;
    FUN_001f9a10(&arm, &arm, &v->pivot);
    d.f[0] = FUN_001f9dc8(self->rot_z) * 11.0f * FUN_001f9de0(self->rot_x);
    d.f[1] = FUN_001f9de0(self->rot_z) * 11.0f * FUN_001f9de0(self->rot_x);
    d.f[2] = FUN_001f9dc8(self->rot_x) * 11.0f;
    FUN_001f9a10(&self->pos, &arm, &d);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002fd0e8.s", FUN_L01_002fd0e8);
typedef struct {
    f32 x, y, z, w;
} SparkVec;

typedef struct {
    u8 pad0[0x24];
    f32 radius;
} SparkClass;

typedef struct {
    u8 pad0[0x10];
    SparkVec pos;
    u8 state;
    u8 pad21[3];
    SparkClass *pclass;
    u8 pad28[4];
    f32 scale;
} SparkMoby;

typedef struct {
    u8 pad0[0x2C];
    f32 f2c;
} SparkHit;

extern s32 D_L01_0015F580;
void *FUN_L00_0025a420(void *, s32, s32);
extern s32 FUN_0022da68(s32, s32, void *);
extern void FUN_L01_002787a0();
extern void *FUN_L00_00263fd8(void *, s32, void *, void *, s32, s32, void *, void *, f32, void *);
extern void FUN_L01_00278e20();
void FUN_0020c828(void *);
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern void FUN_001f9a10(void *, void *, void *);

void FUN_L01_002fd9a0(SparkMoby *m) {
    SparkHit *hit;
    s32 flag;
    s32 i;
    f32 ang;
    f32 s;
    SparkVec off;
    SparkVec rot;

    flag = 0;
    hit = FUN_L00_0025a420(m, 0x10000, 0);
    switch (m->state) {
    case 0:
        m->state = 1;
        break;
    case 1:
        if (hit != 0 && hit->f2c > 0.0f) {
            flag = 1;
        }
        if (flag) {
            m->state = 2;
        }
        break;
    case 2:
        FUN_0022da68(0, 0, m);
        FUN_L01_002787a0(m);
        s = m->scale / m->pclass->radius;
        for (i = 0; i < 4; i++) {
            ang = (f32)i * 1.5707964f;
            FUN_001f99f8(&rot);
            rot.z = FUN_001fa580(ang, 0.87266463f);
            off.x = FUN_001f9dc8(ang) * -0.57f * s;
            off.y = FUN_001f9de0(ang) * -0.57f * s;
            off.z = 0.0f;
            FUN_001f9a10(&off, &off, &m->pos);
            off.z += s * 1.2f;
            FUN_L00_00263fd8(m, 0x719, &off, &rot, 0, 0, &D_L01_0015F580, &D_L01_0015F580, 0.0f, &D_L01_0015F580);
        }
        FUN_L01_00278e20(m, 0x718);
        FUN_0020c828(m);
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002feb58.s", FUN_L01_002feb58);
typedef struct {
    Vec4 home;
    f32 t;
    f32 radius;
} HoverVars;

typedef struct {
    u8 pad0[0x10];
    Vec4 pos;
    u8 state;
    u8 pad21[0x27];
    f32 rot_z;
    u8 pad4C[0x2C];
    HoverVars *vars;
    u8 pad7C[0x2A];
    s16 oclass;
} HoverMoby;

extern f32 FUN_001f99c0(f32);
extern Vec4 D_0013F3D0;

void FUN_L01_002fed68(HoverMoby *m) {
    HoverVars *v;
    Vec4 *player;
    Vec4 off;
    f32 k;

    v = m->vars;
    switch (m->state) {
    case 0:
        qcopy(&v->home, &m->pos);
        v->t = 0.0f;
        m->state = 1;
        break;
    case 1:
        player = &D_0013F3D0;
        if (FUN_001f9b80(v, player) < v->radius && FUN_001f99c0(m->pos.f[2] - player->f[2]) < 2.0f) {
            m->state = 2;
            if (m->oclass == 0x300) {
                FUN_0022da68(0, 0, m);
            }
        }
        break;
    case 2:
        v->t += 1.0f / FUN_001f96b0(20.0f);
        if (v->t >= 1.0f) {
            v->t = 1.0f;
            m->state = 3;
        }
        break;
    case 3:
        k = 1.1f;
        if (FUN_001f9b80(v, &D_0013F3D0) > v->radius * k
            && FUN_001f9b80(v, D_L01_00167240) > v->radius * k) {
            m->state = 4;
            if (m->oclass == 0x300) {
                FUN_0022da68(0, 0, m);
            }
        }
        break;
    case 4:
        player = &D_0013F3D0;
        if (FUN_001f9b80(v, player) < v->radius && FUN_001f99c0(m->pos.f[2] - player->f[2]) < 2.0f) {
            m->state = 2;
        } else {
            v->t -= 1.0f / FUN_001f96b0(20.0f);
            if (v->t <= 0.0f) {
                v->t = 0.0f;
                m->state = 1;
            }
        }
        break;
    }
    off.f[0] = FUN_001f9dc8(m->rot_z) * v->t * (m->oclass == 0x300 ? 2.0f : -2.0f);
    off.f[1] = FUN_001f9de0(m->rot_z) * v->t * (m->oclass == 0x300 ? 2.0f : -2.0f);
    off.f[2] = 0.0f;
    m->pos.f[0] = v->home.f[0] + off.f[0];
    m->pos.f[1] = v->home.f[1] + off.f[1];
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002ff860.s", FUN_L01_002ff860);
typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 state;
    u8 pad21[0xF];
    u8 b30; u8 b31; s16 h32;
    u8 pad34[4];
    u64 d38;
    u128 rot;
    u8 pad50[0x28];
    s32 *pvars;
} SpawnedMoby;
extern void *create_moby(s32 oclass) __asm__("FUN_0020c4f8");
extern void FUN_L00_00250df8();

SpawnedMoby *FUN_L01_002ffa90(SpawnedMoby *src) {
    SpawnedMoby *m;
    s32 *pv;

    m = create_moby(0x30B);
    if (m != 0) {
        m->b30 = 0x20;
        m->h32 = 0xFF;
        m->b31 = 1;
        m->state = 0;
        pv = m->pvars;
        m->d38 = src->d38;
        qcopy(&m->pos, &src->pos);
        qcopy(&m->rot, &src->rot);
        *pv = -1;
        FUN_L00_00250df8(m, -1);
    }
    return m;
}

typedef struct {
    s32 sound;
} SmokeVars;

typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 pad20[0x58];
    SmokeVars *vars;
    u8 pad7c[0x44];
    u128 mtx[4];
} SmokeMoby;

extern int FUN_L00_0028d8c0(void *, int);
extern s32 FUN_0022da68(s32, s32, void *);
extern void FUN_001f9cf8(void *, void *, void *);
extern void FUN_001f9a10(void *, void *, void *);
extern int FUN_L00_00257b90(int lo, int hi);
extern void FUN_L00_0026ced0(void *, void *, u32, u32, f32, s32);

void FUN_L01_002ffb28(SmokeMoby *self) {
    SmokeVars *v;
    Vec4 pos;
    Vec4 vel;
    Vec4 tmp;
    f32 size;
    s32 i;

    v = self->vars;
    if (FUN_L00_0028d8c0(self, v->sound) == 0) {
        v->sound = FUN_0022da68(0, 4, self);
    }
    for (i = 0; i < 2; i++) {
        pos.q = 0;
        tmp.q = 0;
        pos.f[0] = -0.2f;
        pos.f[2] = 1.2f;
        tmp.f[0] = random_float_between(0.8f, 1.2f) * (D_0015ED6C * 3.0f);
        tmp.f[2] = random_float_between(0.8f, 1.2f) * (D_0015ED6C + D_0015ED6C);
        vel.q = tmp.q;
        FUN_001f9cf8(&vel, &vel, self->mtx);
        FUN_001f9a10(&pos, &pos, &self->pos);
        size = random_float_between(125000.0f, 175000.0f);
        FUN_L00_0026ced0(&pos, &vel, 0x207F7F7F, 0x272727, size, FUN_001f96f8(FUN_L00_00257b90(0x2D, 0x3C)));
    }
}
typedef struct {
    u8 pad0[0x8];
    f32 f8;
    u8 padC[4];
    f32 f10;
    s32 timer;
    u8 pad18[4];
    f32 spin;
} OrbVars;
typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 pad20[0xC];
    f32 scale;
    u8 b30; u8 b31; s16 h32;
    u8 pad34[0xC];
    s32 w40;
    u8 pad44[4];
    f32 rotz;
    u8 pad4C[0x2C];
    OrbVars *pvars;
} OrbMoby;
extern void FUN_L00_0025d1b8(OrbMoby *);
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern f32 D_0015ED6C;
extern f32 D_0015ED70;

OrbMoby *FUN_L01_002ffcd0(u128 *pos, f32 scale) {
    OrbMoby *m;
    OrbVars *pv;

    m = create_moby(0x313);
    if (m != 0) {
        pv = m->pvars;
        FUN_L00_0025d1b8(m);
        m->w40 = 0;
        m->h32 = 0x40;
        m->b30 = 0xFF;
        m->scale = m->scale * scale;
        m->rotz = random_angle_radians();
        qcopy(&m->pos, pos);
        qzero(pv);
        pv->f8 = -D_0015ED6C;
        pv->timer = 0x78;
        pv->f10 = D_0015ED70 * 15.0f;
        pv->spin = random_float_between(0.0031415929f, 0.062831856f);
        FUN_L00_00250df8(m);
    }
    return m;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002ffdc0.s", FUN_L01_002ffdc0);
typedef struct {
    u8 pad0[0x10];
    s32 w10;
    u8 pad14[0x10];
    f32 f24;
} MobyClass;
typedef struct {
    u8 pad0[0x20];
    f32 f20;
    u8 pad24[0x14C];
    s32 w170;
    u8 pad174[0xB0];
    f32 f224;
    u8 pad228[0x28];
    f32 f250;
} ClonedVars;
typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 pad20[4];
    MobyClass *mclass;
    u8 pad28[4];
    f32 scale;
    u8 b30; u8 b31; s16 h32;
    u16 flags;
    u8 pad36[2];
    u64 d38;
    u128 rot;
    u8 pad50[0x28];
    void *pvars;
    u8 pad7C[0x18];
    s32 w94;
} ClonedMoby;
extern void FUN_L00_002591d0(ClonedMoby **, s32, s32, s32);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
typedef struct {
    s32 src_id;
    u8 pad4[4];
    s32 count;
} SpawnerVars;
typedef struct {
    u8 pad0[0x60];
    u8 path[0x18];
    s32 w78;
    s32 w7C;
    s32 w80;
    s32 w84;
    f32 f88;
    u8 pad8C[0x24];
    f32 fB0;
    f32 fB4;
    u8 padB8[0x198];
    f32 f250;
} CloneAiVars;
typedef struct {
    u8 pad0[0x10];
    f32 x;
    f32 y;
    u8 pad18[8];
    u8 state;
    u8 pad21[0x57];
    void *pvars;
} SpawnerMoby;
typedef struct {
    u8 pad0[0x80];
    f32 x;
    f32 y;
} PlayerPosView;
extern s32 FUN_L01_0026e008(s32, s32);
extern ClonedMoby *FUN_L01_00302328(ClonedMoby *);
extern f32 FUN_001f9e90(f32, f32);
extern f32 FUN_001fa580(f32, f32);
extern void FUN_L00_0025c558(void *, void *, s32, s32, s32, f32);
extern s32 D_L01_00161E90 __attribute__((sda));
extern PlayerPosView D_0013F350;

void FUN_L01_003021b8(SpawnerMoby *m) {
    SpawnerVars *v = m->pvars;
    SpawnerMoby *n;
    CloneAiVars *nv;
    f32 k;

    switch (m->state) {
    case 0:
        m->state = 1;
        break;
    case 1:
        if (v->src_id < 0) {
            break;
        }
        if (FUN_L01_0026e008(v->src_id, 0xC) != 0) {
            break;
        }
        if (v->count >= D_L01_00161E90) {
            break;
        }
        v->count++;
        n = (SpawnerMoby *)FUN_L01_00302328((ClonedMoby *)m);
        if (n != 0) {
            nv = n->pvars;
            k = 0.8f;
            nv->w84 = 8;
            nv->w80 = truncate_float_to_s32(nv->f250 * k * 1024.0f);
            nv->f88 = nv->f250 * k;
            nv->fB0 = 7.0f;
            nv->fB4 = 13.0f;
            nv->w78 = 0;
            nv->w7C = 0;
            FUN_L00_0025c558(n, nv->path, 5, 8, 0,
                FUN_001fa580(FUN_001f9e90(D_0013F350.x - m->x, D_0013F350.y - m->y),
                             3.1415927f));
            n->state = 9;
        }
        break;
    }
}

ClonedMoby *FUN_L01_00302328(ClonedMoby *src) {
    ClonedMoby *m;
    ClonedVars *v;

    m = 0;
    FUN_L00_002591d0(&m, *(s32 *)src->pvars, 0, 0);
    v = m->pvars;
    m->b30 = 0x80;
    m->h32 = 0x80;
    m->d38 = src->d38;
    m->b31 = 1;
    m->w94 = m->mclass->w10;
    m->flags |= 0x1020;
    m->scale = m->mclass->f24;
    {
        ClonedMoby *d = m;
        qcopy(&d->pos, &src->pos);
        qcopy(&d->rot, &src->rot);
    }
    v->f20 = 3.0f;
    v->f250 = 1.0f;
    v->w170 = truncate_float_to_s32(819.2f);
    v->f224 = 30.0f;
    FUN_L00_00250df8(m);
    return m;
}
void *FUN_L00_0025a420(void *, s32, s32);
void FUN_0020c828(void *);

void FUN_L01_00307c48(void *self) {
    u8 *p;

    p = FUN_L00_0025a420(self, 0x10000, 0);
    if (p != NULL && *(f32 *)(p + 0x2C) > 0.0f) {
        FUN_0020c828(self);
    }
}
