#ifndef LOMBYTE_RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_H
#define LOMBYTE_RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_H

#include "types.h"

struct Globals_001D5BF0 {
    u8 pad_0[0xCB];
    u8 unkCB;
    u8 pad_CC[0x3];
};

struct WordCell {
    s32 unk0;
};

#endif /* LOMBYTE_RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_H */
