#ifndef LOMBYTE_RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_H
#define LOMBYTE_RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_H

#include "types.h"

struct WordCell {
    s32 unk0;
};

#endif /* LOMBYTE_RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_H */
