#ifndef LOMBYTE_RNC_AUDIO_STREAMING_FINISH_AUDIO_STREAM_READ_H
#define LOMBYTE_RNC_AUDIO_STREAMING_FINISH_AUDIO_STREAM_READ_H

#include "types.h"

#include "rnc/audio/music/music_stream_state.h"

#endif /* LOMBYTE_RNC_AUDIO_STREAMING_FINISH_AUDIO_STREAM_READ_H */