#ifndef LOMBYTE_RNC_AUDIO_STREAMING_REQUEST_AUDIO_STREAM_BREAK_H
#define LOMBYTE_RNC_AUDIO_STREAMING_REQUEST_AUDIO_STREAM_BREAK_H

#include "types.h"

#include "rnc/audio/music/music_stream_state.h"

#endif /* LOMBYTE_RNC_AUDIO_STREAMING_REQUEST_AUDIO_STREAM_BREAK_H */