#ifndef LOMBYTE_RNC_AUDIO_STREAMING_UPDATE_AUDIO_STREAM_UNTIL_IDLE_H
#define LOMBYTE_RNC_AUDIO_STREAMING_UPDATE_AUDIO_STREAM_UNTIL_IDLE_H

#include "types.h"

#include "rnc/audio/music/music_stream_state.h"

#endif /* LOMBYTE_RNC_AUDIO_STREAMING_UPDATE_AUDIO_STREAM_UNTIL_IDLE_H */