/* Level overlay code after gameplay/state; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00261968.s", FUN_L00_00261968);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00261b48.s", FUN_L00_00261b48);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00261d78.s", FUN_L00_00261d78);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00262030.s", FUN_L00_00262030);
#include "rnc/math/vector.h"

/* A polyline of evenly spaced points. */
typedef struct {
    s32 count;          /* 0x00 */
    u8 pad4[0xC];
    Vec4 points[1];     /* 0x10 */
} PointPath;

extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern f32 s32_to_float(s32) __asm__("FUN_001fa6c0");
extern void subtract_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a28");
extern void scale_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");

/* Samples path at distance dist (points spacing apart): stores the segment, the distance into it and the point. */
void FUN_L00_00262360(PointPath *path, s32 *seg_out, f32 *along, Vec4 *out, f32 dist, f32 spacing) {
    Vec4 tmp;
    s32 seg;

    seg = truncate_float_to_s32(dist / spacing);
    *seg_out = seg;
    if (seg >= path->count - 1) {
        *seg_out = path->count - 1;
        *along = 0.0f;
        out->q = (path->points + *seg_out)->q;
        return;
    }
    if (seg < 0) {
        *seg_out = 0;
        *along = 0.0f;
        out->q = (path->points + *seg_out)->q;
        return;
    }
    *along = dist - s32_to_float(seg) * spacing;
    subtract_vector_xyz(&tmp, &path->points[*seg_out + 1], &path->points[*seg_out]);
    out->q = tmp.q;
    scale_vector_xyz(out, out, *along);
    add_vector_xyz(&tmp, out, &path->points[*seg_out]);
    out->q = tmp.q;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/mobyutil_00261B00.c: func_L00_002634F8), where it is exact; names translated to the US level program. */

extern void FUN_001fa050(void *, void *);
extern void FUN_001fa378(void *, void *, void *);
extern void FUN_00214598(void *, void *);

/* Multiplies the 001fa050 matrices of (x, y, z) and of a+0x40, stored back by FUN_00214598. */
void FUN_L00_00262480(char *a, float x, float y, float z) {
    float in[3];
    float t[16], u[16];
    in[0] = x;
    in[1] = y;
    in[2] = z;
    FUN_001fa050(t, in);
    FUN_001fa050(u, a + 0x40);
    FUN_001fa378(u, u, t);
    FUN_00214598(u, a + 0x40);
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/mobyutil_00261B00.c: func_L00_00263578), where it is exact; names translated to the US level program. */

/* Unless the flag at b+0x13C is set: sets it, stores a at 0x134, clears 0x130..0x138. */
void FUN_L00_00262500(int a, char *b) {
    if (*(int *)(b + 0x13C) == 0) {
        *(int *)(b + 0x134) = a;
        *(int *)(b + 0x13C) = 1;
        *(short *)(b + 0x132) = 0;
        *(int *)(b + 0x138) = 0;
        *(short *)(b + 0x130) = 0;
    }
}
typedef struct {
    u8 p0[0x23];
    u8 x23;
    u8 p24[0xC];
    u8 x30;
    u8 x31;
    u16 x32;
    s16 x34;
    u8 p36[2];
    u64 x38;
    u8 p40[0x32];
    u8 x72;
    u8 p73[0x21];
    s32 x94;
    u8 p98[0xE];
    s16 xa6;
} E00262528;
typedef struct {
    u8 p0[0x100];
    s32 x100[4];
    s32 x110[4];
    E00262528 *x120[4];
    u8 p130[4];
    E00262528 *x134;
    s32 x138;
} O00262528;
E00262528 *create_moby(s32) __asm__("FUN_0020c4f8");
void FUN_L00_00262528(O00262528 *o, s32 a, s32 b) {
    E00262528 *e;
    if (o->x138 == 4)
        return;
    if (b >= 9)
        return;
    e = create_moby(o->x134->xa6);
    if (e == 0)
        return;
    e->x32 = o->x134->x32;
    e->x38 = o->x134->x38;
    e->x31 = 1;
    e->x34 = 0x80A;
    e->x30 = 0;
    e->x94 = 0;
    if (e->xa6 == 0)
        e->x72 = 0;
    e->x23 = a;
    o->x110[o->x138] = b;
    o->x100[o->x138] = a;
    o->x120[o->x138] = e;
    o->x138++;
}
#include "qcopy.h"
#include "rnc/overlay/quad.h"
typedef struct {
    OvlQuad a[8];
    OvlQuad b[8];
    unsigned char pad[0x10];
    int w[8];
    short head;
    short count;
    unsigned char *src;
    int n;
    int active;
} S_262608;
void FUN_L00_00262840_262608(S_262608 *) __asm__("FUN_L00_00262840");
void FUN_0020c880_262608(void *) __asm__("FUN_0020c880");
void FUN_L00_00250df8_262608(void *) __asm__("FUN_L00_00250df8");

void FUN_L00_00262608(S_262608 *s, int dec) {
    unsigned char *src;
    unsigned char *o;
    int h, i, k, done;
    unsigned char **pp;
    if (!s->active)
        return;
    src = s->src;
    if (!src || src[0x20] == 0xFE || src[0x20] == 0xFD) {
        FUN_L00_00262840_262608(s);
        return;
    }
    h = s->head;
    qcopy(&s->a[h], src + 0x10);
    qcopy(&s->b[h], src + 0x40);
    s->head = (h + 1) % 8;
    if (++s->count > 8)
        s->count = 8;
    for (i = 0; i < s->n; i++) {
        int t;
        if (s->count >= (t = s->w[i])) {
            o = (unsigned char *)*(int *)((char *)&s->w[i] + 0x10);
            k = (s->head - t + 8) % 8;
            o[0x52] = s->src[0x52];
            o[0x53] = s->src[0x53];
            o[0x50] = s->src[0x50];
            o[0x51] = s->src[0x51];
            *(float *)(o + 0x54) = *(float *)(s->src + 0x54);
            FUN_0020c880_262608(o);
            qcopy(o + 0x10, &s->a[k]);
            qcopy(o + 0x40, &s->b[k]);
            FUN_L00_00250df8_262608(o);
        }
    }
    if (dec) {
        done = 1;
        for (i = 0; i < s->n; i++) {
            unsigned char *q = (unsigned char *)*(int *)((char *)&s->w[i] + 0x10);
            if (q) {
                int v = q[0x23];
                int a = v;
                if (dec < v)
                    v = dec;
                a -= v;
                q[0x23] = a;
                if ((unsigned char)a)
                    done = 0;
            }
        }
        if (done)
            FUN_L00_00262840_262608(s);
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/mobyutil_00261B00.c: func_L00_002638B8), where it is exact; names translated to the US level program. */

void mark_moby_for_removal(struct Obj *obj) __asm__("FUN_0020c828");

/* When o+0x13C is set, marks each nonzero moby of the 0x120 list for removal; clears the flag. */
void FUN_L00_00262840(char *o) {
    int i;
    if (*(int *)(o + 0x13C) != 0) {
        for (i = 0; i < *(int *)(o + 0x138); i++) {
            int *p = (int *)(o + 0x120) + i;
            if (*p != 0) {
                mark_moby_for_removal(*p);
                *p = 0;
            }
        }
        *(int *)(o + 0x13C) = 0;
    }
}
void FUN_0020cb88_2628d8(void *, void *) __asm__("FUN_0020cb88");
void FUN_0020cb10_2628d8(void *, int, void *) __asm__("FUN_0020cb10");
float FUN_001f99c0_2628d8(float) __asm__("FUN_001f99c0");
float FUN_L00_0025bc98_2628d8(void *, void *, float, float, float, float,
                              int) __asm__("FUN_L00_0025bc98");
void FUN_L00_00259f50_2628d8(void *, void *) __asm__("FUN_L00_00259f50");
void FUN_001f99f8_2628d8(void *) __asm__("FUN_001f99f8");

void FUN_L00_002628d8(void *m, unsigned char *p, int c, float fa, float fb) {
    unsigned char *o = *(unsigned char **)(p + 0x78);
    float f;
    if (!o) {
        *(void **)(p + 0x78) = m;
    } else if (o != m) {
        if (p[1] && o[0x20] < 0x7F)
            FUN_0020cb88_2628d8(o, p);
        p[1] = 0;
        *(void **)(p + 0x78) = m;
    }
    if (*(float *)(p + 0x60) == 0.0f && *(float *)(p + 0x64) == 0.0f &&
        *(float *)(p + 0x68) == 0.0f && *(float *)(p + 0x70) == 1.0f &&
        FUN_001f99c0_2628d8(*(float *)(p + 0x40)) < 0.005f &&
        FUN_001f99c0_2628d8(*(float *)(p + 0x44)) < 0.005f &&
        FUN_001f99c0_2628d8(*(float *)(p + 0x48)) < 0.005f) {
        if (p[1])
            FUN_0020cb88_2628d8(m, p);
        return;
    }
    FUN_L00_0025bc98_2628d8(p + 0x40, p + 0x50, *(float *)(p + 0x60), fa, fb, 0.0f, 0);
    FUN_L00_0025bc98_2628d8(p + 0x44, p + 0x54, *(float *)(p + 0x64), fa, fb, 0.0f, 0);
    FUN_L00_0025bc98_2628d8(p + 0x48, p + 0x58, *(float *)(p + 0x68), fa, fb, 0.0f, 0);
    if (!p[1])
        FUN_0020cb10_2628d8(m, c, p);
    FUN_L00_00259f50_2628d8(p + 0x10, p + 0x40);
    f = *(float *)(p + 0x70);
    *(float *)(p + 0x20) = f;
    *(float *)(p + 0x24) = f;
    *(float *)(p + 0x28) = f;
    FUN_001f99f8_2628d8(p + 0x60);
    *(float *)(p + 0x70) = 1.0f;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/mobyutil_00261B00.c: func_L00_00263B78), where it is exact; names translated to the US level program. */

extern float FUN_001f9de0(float);
extern float fast_add_rotations(float, float) __asm__("FUN_001fa580");

/* Advances angle *p by y and swaps the old x*sin offset in a+0x18 for the new one. */
void FUN_L00_00262b00(float x, float y, char *a, float *p, float *q) {
    float t;
    *p = fast_add_rotations(*p, y);
    *(float *)(a + 0x18) -= *q;
    t = FUN_001f9de0(*p) * x;
    *q = t;
    *(float *)(a + 0x18) += t;
}
/* Ported from rac1-decomp (src/overlays/shared/mobyutil_00261B00.c: func_L00_00263BF8), where it is exact; names translated to the US level program. */

extern float FUN_001f9dc8(float);

/* Sets o[16] and o[17] from r and the sines/cosines of the two angles, then advances the angles by l1 and l2. */
void FUN_L00_00262b80(float *o, float *a, float *b, float r, float l1, float l2) {
    o[0x10] = r * FUN_001f9de0(*a) * FUN_001f9de0(*b);
    o[0x11] = r * FUN_001f9de0(*a) * FUN_001f9dc8(*b);
    *a = fast_add_rotations(*a, l1);
    *b = fast_add_rotations(*b, l2);
}
