#ifndef RNC_AUDIO_STREAMING_START_AUDIO_STREAM_READ_TYPES_H
#define RNC_AUDIO_STREAMING_START_AUDIO_STREAM_READ_TYPES_H

#include "types.h"

struct M2c_D_001516D0 {
    u8 pad_0[0x8];
    s32 unk8;
    s32 unkC;
    s32 unk10;
    s32 unk14;
};

#endif /* RNC_AUDIO_STREAMING_START_AUDIO_STREAM_READ_TYPES_H */
