#ifndef RNC_AUDIO_STREAMING_CONTINUE_AUDIO_STREAM_IF_READY_TYPES_H
#define RNC_AUDIO_STREAMING_CONTINUE_AUDIO_STREAM_IF_READY_TYPES_H

#include "types.h"

struct M2c_D_001516D0 {
    u8 pad_0[0x50];
    s32 unk50;
    u8 pad_54[0x6];
    s32 unk5A;
};

#endif /* RNC_AUDIO_STREAMING_CONTINUE_AUDIO_STREAM_IF_READY_TYPES_H */
