#ifndef RNC_AUDIO_STREAMING_SUBMIT_AUDIO_STREAM_IO_REQUEST_TYPES_H
#define RNC_AUDIO_STREAMING_SUBMIT_AUDIO_STREAM_IO_REQUEST_TYPES_H

#include "types.h"

struct M2c_D_00151700 {
    s32 unk0;
};

#endif /* RNC_AUDIO_STREAMING_SUBMIT_AUDIO_STREAM_IO_REQUEST_TYPES_H */
