#ifndef RNC_AUDIO_STREAMING_SND_STREAM_SAFE_CD_GET_ERROR_TYPES_H
#define RNC_AUDIO_STREAMING_SND_STREAM_SAFE_CD_GET_ERROR_TYPES_H

#include "types.h"

struct M2c_D_00137B00 {
    u8 pad_0[0x10];
    s32 unk10;
};

#endif /* RNC_AUDIO_STREAMING_SND_STREAM_SAFE_CD_GET_ERROR_TYPES_H */
