#ifndef RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_TYPES_H
#define RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_TYPES_H

#include "types.h"

struct M2c_D_001D5BF0 {
    u8 pad_0[0xCB];
    u8 unkCB;
    u8 pad_CC[0x3];
};

struct M2c_var_16_10 {
    s32 unk0;
};

#endif /* RNC_AUDIO_STREAMING_COMPLETE_STREAM_BUFFER_TRANSFER_TYPES_H */
