#ifndef RNC_AUDIO_VOICES_ALLOCATE_VOICE_FOR_GROUP_ENTRY_TYPES_H
#define RNC_AUDIO_VOICES_ALLOCATE_VOICE_FOR_GROUP_ENTRY_TYPES_H

#include "types.h"

struct M2c_temp_3_32 {
    u8 pad_0[0x7E];
    s16 unk7E;
    u8 pad_80[0x8];
    s32 unk88;
};

#endif /* RNC_AUDIO_VOICES_ALLOCATE_VOICE_FOR_GROUP_ENTRY_TYPES_H */
