#ifndef RNC_AUDIO_STREAMING_GET_STREAM_BUFFER_SIZE_TYPES_H
#define RNC_AUDIO_STREAMING_GET_STREAM_BUFFER_SIZE_TYPES_H

#include "types.h"

struct M2c_var_3_7 {
    s32 unk0;
    s32 unk4;
};

#endif /* RNC_AUDIO_STREAMING_GET_STREAM_BUFFER_SIZE_TYPES_H */
