#ifndef RNC_AUDIO_STREAMING_CLEAR_RECORD_FLAG_BY_KEY_TYPES_H
#define RNC_AUDIO_STREAMING_CLEAR_RECORD_FLAG_BY_KEY_TYPES_H

#include "types.h"

struct M2c_var_5_9 {
    s32 unk0;
};

#endif /* RNC_AUDIO_STREAMING_CLEAR_RECORD_FLAG_BY_KEY_TYPES_H */
