#ifndef RNC_AUDIO_DECODER_TERMINATE_AUDIO_SYSTEM_TYPES_H
#define RNC_AUDIO_DECODER_TERMINATE_AUDIO_SYSTEM_TYPES_H

#include "types.h"

struct M2c_D_0016120C {
    u8 pad_0[0xD90F8];
    s32 unkD90F8;
    s32 unkD90FC;
};

#endif /* RNC_AUDIO_DECODER_TERMINATE_AUDIO_SYSTEM_TYPES_H */
