#ifndef RNC_AUDIO_BANKS_LOAD_AUDIO_BANK_BY_LOCATION_TYPES_H
#define RNC_AUDIO_BANKS_LOAD_AUDIO_BANK_BY_LOCATION_TYPES_H

#include "types.h"

struct M2c_D_0013E550 {
    u8 pad_0[0x44];
    s32 unk44;
};

#endif /* RNC_AUDIO_BANKS_LOAD_AUDIO_BANK_BY_LOCATION_TYPES_H */
