#ifndef RNC_GAMEPLAY_CAMERA_BACKUP_CURRENT_CAM_TYPES_H
#define RNC_GAMEPLAY_CAMERA_BACKUP_CURRENT_CAM_TYPES_H

#include "types.h"

struct M2c_D_00189210 {
    u8 pad_0[0x70];
    s32 unk70;
};

#endif /* RNC_GAMEPLAY_CAMERA_BACKUP_CURRENT_CAM_TYPES_H */
