#ifndef RNC_GAMEPLAY_ENTITIES_UPDATE_MOBY_TYPES_H
#define RNC_GAMEPLAY_ENTITIES_UPDATE_MOBY_TYPES_H

#include "types.h"

typedef struct ADXF_PTINFO { char _pad[8]; Sint32 nfile; } ADXF_PTINFO;

#endif /* RNC_GAMEPLAY_ENTITIES_UPDATE_MOBY_TYPES_H */
