#ifndef RNC_GAMEPLAY_ENTITIES_PROBE_GROUND_HEIGHT_TYPES_H
#define RNC_GAMEPLAY_ENTITIES_PROBE_GROUND_HEIGHT_TYPES_H

#include "types.h"

struct M2c_D_00194120 {
    u8 pad_0[0x8];
    f32 unk8;
};

#endif /* RNC_GAMEPLAY_ENTITIES_PROBE_GROUND_HEIGHT_TYPES_H */
