#ifndef RNC_GAMEPLAY_STATE_TRANSITION_DEFAULT_DRAW_TYPES_H
#define RNC_GAMEPLAY_STATE_TRANSITION_DEFAULT_DRAW_TYPES_H

#include "types.h"

struct M2c_D_0016045C
{
  u8 pad_0[0x4];
  s16 unk4;
  u8 pad_6[0x2];
};

#endif /* RNC_GAMEPLAY_STATE_TRANSITION_DEFAULT_DRAW_TYPES_H */
