#ifndef RNC_GAMEPLAY_ENTITIES_PRUNE_MOBY_REFERENCES_TYPES_H
#define RNC_GAMEPLAY_ENTITIES_PRUNE_MOBY_REFERENCES_TYPES_H

#include "types.h"

struct M2c_temp_3_10 {
    u8 pad_0[0x20];
    s32 unk20;
    u8 pad_24[0x2E];
    s32 unk52;
};

#endif /* RNC_GAMEPLAY_ENTITIES_PRUNE_MOBY_REFERENCES_TYPES_H */
