#ifndef RNC_GAMEPLAY_STATE_IS_VALUE_WITHIN_INTERPOLATED_WINDOW_TYPES_H
#define RNC_GAMEPLAY_STATE_IS_VALUE_WITHIN_INTERPOLATED_WINDOW_TYPES_H

#include "types.h"

struct M2c_arg0 {
    u8 pad_0[0x58];
    s32 unk58;
    s32 unk5C;
};

#endif /* RNC_GAMEPLAY_STATE_IS_VALUE_WITHIN_INTERPOLATED_WINDOW_TYPES_H */
