#ifndef RNC_GAMEPLAY_ANIMATION_FIND_ANIMATION_DEFINITION_INDEX_TYPES_H
#define RNC_GAMEPLAY_ANIMATION_FIND_ANIMATION_DEFINITION_INDEX_TYPES_H

#include "types.h"

typedef struct { char b[0x20]; } T32;

#endif /* RNC_GAMEPLAY_ANIMATION_FIND_ANIMATION_DEFINITION_INDEX_TYPES_H */
