#ifndef RNC_MATH_ROTATIONS_ROTATE_VECTOR_BY_QUATERNION_TYPES_H
#define RNC_MATH_ROTATIONS_ROTATE_VECTOR_BY_QUATERNION_TYPES_H

#include "types.h"

struct M2c_arg2 {
    u8 pad_0[0xC];
    s32 unkC;
};

#endif /* RNC_MATH_ROTATIONS_ROTATE_VECTOR_BY_QUATERNION_TYPES_H */
