#ifndef RNC_MATH_ROTATIONS_BUILD_QUATERNION_FROM_AXIS_ANGLE_TYPES_H
#define RNC_MATH_ROTATIONS_BUILD_QUATERNION_FROM_AXIS_ANGLE_TYPES_H

#include "types.h"

struct M2c_arg0 {
    u8 pad_0[0xC];
    s32 unkC;
};

#endif /* RNC_MATH_ROTATIONS_BUILD_QUATERNION_FROM_AXIS_ANGLE_TYPES_H */
