#ifndef RNC_RENDERING_PACKETS_APPEND_DRAW_BUFFER_PACKET_TYPES_H
#define RNC_RENDERING_PACKETS_APPEND_DRAW_BUFFER_PACKET_TYPES_H

#include "types.h"

struct M2c_D_00160F00 {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    s32 unkC;
};

#endif /* RNC_RENDERING_PACKETS_APPEND_DRAW_BUFFER_PACKET_TYPES_H */
