#ifndef RNC_RENDERING_EFFECTS_DRAW_FOGGED_FULLSCREEN_SPRITE_TYPES_H
#define RNC_RENDERING_EFFECTS_DRAW_FOGGED_FULLSCREEN_SPRITE_TYPES_H

#include "types.h"

struct M2c_D_00151780 {
    u8 pad_0[0x150];
    s16 unk150;
    s32 unk152;
};

struct M2c_arg0 {
    u8 pad_0[0x4];
    s32 unk4;
    s32 unk8;
};

#endif /* RNC_RENDERING_EFFECTS_DRAW_FOGGED_FULLSCREEN_SPRITE_TYPES_H */
