#ifndef RNC_RENDERING_GEOMETRY_TRANSFORM_SCALED_VERTEX_BATCH_TYPES_H
#define RNC_RENDERING_GEOMETRY_TRANSFORM_SCALED_VERTEX_BATCH_TYPES_H

#include "types.h"

struct M2c_arg0 {
    u8 pad_0[0x2C];
    s32 unk2C;
};

#endif /* RNC_RENDERING_GEOMETRY_TRANSFORM_SCALED_VERTEX_BATCH_TYPES_H */
