#ifndef RNC_RUNTIME_MEMORY_CALCULATE_RING_BUFFER_BOUNDS_TYPES_H
#define RNC_RUNTIME_MEMORY_CALCULATE_RING_BUFFER_BOUNDS_TYPES_H

#include "types.h"

struct M2c_D_001940C0 {
    u8 pad_0[0x4];
    s32 unk4;
    s32 unk8;
};

#endif /* RNC_RUNTIME_MEMORY_CALCULATE_RING_BUFFER_BOUNDS_TYPES_H */
