#ifndef RNC_STORAGE_MEMORY_CARD_MEMCARD_MAKE_WHOLE_SAVE_TYPES_H
#define RNC_STORAGE_MEMORY_CARD_MEMCARD_MAKE_WHOLE_SAVE_TYPES_H

#include "types.h"

struct M2c_arg0 {
    s32 unk0;
    s32 unk4;
};

#endif /* RNC_STORAGE_MEMORY_CARD_MEMCARD_MAKE_WHOLE_SAVE_TYPES_H */
