#ifndef RNC_UI_MENUS_FORMAT_SCALED_DISPLAY_VALUE_TYPES_H
#define RNC_UI_MENUS_FORMAT_SCALED_DISPLAY_VALUE_TYPES_H

#include "types.h"

typedef struct ADXF_PTINFO { char _pad[8]; Sint32 nfile; } ADXF_PTINFO;

#endif /* RNC_UI_MENUS_FORMAT_SCALED_DISPLAY_VALUE_TYPES_H */
