#ifndef RNC_UI_MENUS_WEAPONS_OBTAIN_ALL_GOLD_WEAPONS_MENU_TYPES_H
#define RNC_UI_MENUS_WEAPONS_OBTAIN_ALL_GOLD_WEAPONS_MENU_TYPES_H

#include "types.h"

struct M2c_arg0 {
    u8 pad_0[0x20];
    s32 unk20;
    s32 unk24;
};

#endif /* RNC_UI_MENUS_WEAPONS_OBTAIN_ALL_GOLD_WEAPONS_MENU_TYPES_H */
