#ifndef RNC_UI_TEXT_UPDATE_SCROLLING_STATUS_MESSAGE_TYPES_H
#define RNC_UI_TEXT_UPDATE_SCROLLING_STATUS_MESSAGE_TYPES_H

#include "types.h"

struct M2c_D_001E63C0 {
    u8 pad_0[0x2C];
    s32 unk2C;
    u8 pad_30[0x14];
    s32 unk44;
};

#endif /* RNC_UI_TEXT_UPDATE_SCROLLING_STATUS_MESSAGE_TYPES_H */
