#ifndef RNC_VIDEO_DECODER_RUN_VIDEO_DECODER_TYPES_H
#define RNC_VIDEO_DECODER_RUN_VIDEO_DECODER_TYPES_H

#include "types.h"

struct M2c_temp_2_25 {
    u8 pad_0[0xD9174];
    s32 unkD9174;
};

#endif /* RNC_VIDEO_DECODER_RUN_VIDEO_DECODER_TYPES_H */
