#ifndef RNC_WORLD_STREAMING_LOAD_LEVEL_CHUNK_FROM_DISC_TYPES_H
#define RNC_WORLD_STREAMING_LOAD_LEVEL_CHUNK_FROM_DISC_TYPES_H

#include "types.h"

typedef struct ADXF_PTINFO { char _pad[8]; Sint32 nfile; } ADXF_PTINFO;

#endif /* RNC_WORLD_STREAMING_LOAD_LEVEL_CHUNK_FROM_DISC_TYPES_H */
