/* Level overlay code after rendering/view; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/gameplay/hero.h"
#include "rnc/globals.h"
#include "asm.h"

#include "qcopy.h"
#include "qzero.h"
extern struct Hero hero_data __asm__("D_0013F350") __attribute__((section(".data")));
extern short D_L00_001B0830_25fcb8[] __asm__("D_L00_001B0830") __attribute__((section(".data")));
extern char *D_L00_0015FFD8_25fcb8 __asm__("D_L00_0015FFD8");
extern char *D_L00_001DD100_25fcb8[] __asm__("D_L00_001DD100") __attribute__((section(".data")));
extern float FUN_001f9b80_25fcb8(void *, void *) __asm__("FUN_001f9b80");

int FUN_L00_0025fcb8(char *a, char *o, float best) {
    struct Hero *g = &hero_data;
    char *m;
    char *p;
    int res;
    int i;
    int j;
    float d;

    m = ((char *)g->moby);
    res = 0;
    if (g->state.control_mode == 0x18 || g->state.current == 0x72) {
        m = 0;
        res = 2;
    }
    for (i = 1; i <= D_L00_001B0830_25fcb8[0]; i++) {
        p = D_L00_0015FFD8_25fcb8 + (D_L00_001B0830_25fcb8[i] << 8);
        if (p == 0)
            continue;
        if (*(short *)(p + 0xA6) != 0xCB && *(short *)(p + 0xA6) != 0x76C)
            continue;
        if (*(unsigned char *)(p + 0x20) == 0xFE)
            continue;
        if (*(unsigned char *)(p + 0x20) == 0xFD)
            continue;
        if (*(unsigned char *)(p + 0x20) != 3)
            continue;
        d = FUN_001f9b80_25fcb8(a + 0x10, p + 0x10);
        if (d < best) {
            m = p;
            best = d;
            res = 1;
        }
    }
    for (j = 0; j < 20; j++) {
        p = D_L00_001DD100_25fcb8[j];
        if (p == 0)
            continue;
        if (*(short *)(p + 0xA6) != 0x10E)
            continue;
        if (*(unsigned char *)(p + 0x20) == 0xFE)
            continue;
        if (*(unsigned char *)(p + 0x20) == 0xFD)
            continue;
        if (*(unsigned char *)(p + 0xBC) == 0)
            continue;
        d = FUN_001f9b80_25fcb8(a + 0x10, p + 0x10);
        if (d < best) {
            m = p;
            best = d;
            res = 1;
        }
    }
    if (m != 0) {
        *(char **)(o + 0x40) = m;
        qcopy(o, m + 0x10);
        qcopy(o + 0x10, m + 0x40);
        g = &hero_data;
        if (m == ((char *)g->moby)) {
            qcopy(o + 0x20, &g->motion.unkC0);
            qcopy(o + 0x30, &g->motion.unkD0);
        } else {
            qcopy(o + 0x30, o);
            *(float *)(o + 0x38) += 0.6f;
            qcopy(o + 0x20, o + 0x30);
        }
    } else {
        *(char **)(o + 0x40) = 0;
        qzero(o);
        qzero(o + 0x10);
        qzero(o + 0x30);
        qzero(o + 0x20);
    }
    *(int *)(o + 0x44) = res;
    return res;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0025ff38.s", FUN_L00_0025ff38);
typedef float M4_260400[16] __attribute__((aligned(16)));
extern char *c338_p(char *) __asm__("FUN_L00_002603d0");
void FUN_001fa050(void *, void *);
void FUN_001f9a10(void *, void *, void *);
void FUN_001f9a28(void *, void *, void *);
void FUN_001f9cf8(void *, void *, void *);
void FUN_001fa378(void *, void *, void *);
void FUN_00214598(void *, void *);
int FUN_L00_00260400(int u0, char *a, void *b, void *c, float *v, void *out) {
    M4_260400 m, n;
    char *o = c338_p(a);
    if (o == 0)
        return 0;
    FUN_001fa050(m, o);
    FUN_001f9a10(v, b, o + 0x10);
    FUN_001f9a28(v, v, a + 0x10);
    FUN_001f9cf8(v, v, m);
    FUN_001f9a10(v, v, a + 0x10);
    FUN_001fa050(n, c);
    FUN_001fa378(n, m, n);
    FUN_00214598(n, out);
    return 1;
}
#include "qcopy.h"
#include "rnc/overlay/quad.h"
typedef float V4_2604f0[4] __attribute__((aligned(16)));
u8 *FUN_L00_002603d0_002604f0(void *) __asm__("FUN_L00_002603d0");
void FUN_001f9cf8_002604f0(void *, void *, void *) __asm__("FUN_001f9cf8");
void FUN_001f9a10_002604f0(void *, void *, void *) __asm__("FUN_001f9a10");
void FUN_001fa050_002604f0(void *, void *) __asm__("FUN_001fa050");
void FUN_001fa298_002604f0(void *, void *) __asm__("FUN_001fa298");
void FUN_001fa378_002604f0(void *, void *, void *) __asm__("FUN_001fa378");
void FUN_00214598_002604f0(void *, void *) __asm__("FUN_00214598");
void FUN_L00_00260668_002604f0(void *, void *, void *, void *, void *,
                               void *) __asm__("FUN_L00_00260668");
void FUN_L00_0025f730_002604f0(void *, float) __asm__("FUN_L00_0025f730");
int FUN_L00_002604f0(u8 *a, u8 *b, void *c, void *d, void *e, void *f) {
    float m2[16] __attribute__((aligned(16)));
    float m[16] __attribute__((aligned(16)));
    V4_2604f0 t;
    u8 *r = FUN_L00_002603d0_002604f0(b);
    if (!r)
        return 0;
    FUN_001f9cf8_002604f0(e, c, b + 0xC0);
    FUN_001f9a10_002604f0(e, e, b + 0x10);
    FUN_001fa050_002604f0(m, d);
    FUN_001fa298_002604f0(m2, b + 0xC0);
    FUN_001fa378_002604f0(m, m2, m);
    FUN_00214598_002604f0(m, f);
    if (*(int *)(r + 0x3C) & 4) {
        FUN_001f9a10_002604f0(e, e, r + 0x10);
        FUN_L00_00260668_002604f0(a, b, e, f, c, d);
        return 1;
    }
    if (a[0x22] && a[0x22] < b[0x22]) {
        qcopy(t, r + 0x10);
        FUN_L00_0025f730_002604f0(t, 1.0f);
        FUN_001f9a10_002604f0(e, e, t);
    }
    return 1;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/mobyutil_00258BC8.c: func_L00_002616E0), where it is exact; names translated to the US level program. */

extern int FUN_L00_002603d0(char *);
extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_001f9d20(void *, void *, void *);
extern void FUN_001fa050(void *, void *);
extern void FUN_001fa2d8(void *, void *);
extern void FUN_001fa378(void *, void *, void *);
extern void FUN_00214598(void *, void *);

int FUN_L00_00260668(int x, char *o, float *a, float *c, float *b, float *d) {
    float m[16];
    float v[4];
    float w[4];
    float pad[12];
    if (FUN_L00_002603d0(o) == 0)
        return 0;
    FUN_001f9a28(v, a, o + 0x10);
    FUN_001fa2d8(m, o + 0xC0);
    FUN_001f9d20(b, v, m);
    FUN_001fa050(w, c);
    FUN_001fa378(w, m, w);
    FUN_00214598(w, d);
    return 1;
}
typedef float M4[16] __attribute__((aligned(16)));
void FUN_001fa050(void *, void *);
void FUN_001fa2d8(void *, void *);
void FUN_001fa378(void *, void *, void *);
void FUN_00214598(void *, void *);
#include "qcopy.h"
void FUN_L00_00260738(char *out, OvlQuad *pos, void *m1, void *m2) {
    M4 a, b, c;
    FUN_001fa050(a, m1);
    FUN_001fa2d8(a, a);
    FUN_001fa050(b, m2);
    FUN_001fa378(c, a, b);
    FUN_00214598(c, out);
    qcopy(out + 0x10, pos);
}
extern u8 D_0013DD40_2607d0[] __asm__("D_0013DD40");
extern s32 D_0013D510_2607d0[] __asm__("D_0013D510");
void FUN_L00_00262d38(s32);
void FUN_L00_002607d0(s32 id) {
    s32 n, i;
    n = 0;
    if (D_0013DD40_2607d0[id] == 0) {
        for (i = 0; i < 20; i++) {
            if (D_0013DD40_2607d0[i])
                n++;
        }
        D_0013DD40_2607d0[id] = 1;
        D_0013D510_2607d0[n] = id;
        if (id != *(volatile s32 *)&current_level_index)
            FUN_L00_00262d38(id);
    }
}
/* Gives item ID to the player: plays its sound, raises its count and records it in the slot lists. */
/* Ported from rac1-decomp (src/overlays/shared/mobyutil_00258BC8.c: func_L00_002618D8), where it is exact; names translated to the US level program. */

typedef struct {
    char pad[8];
    unsigned short a;
    char pad2[8];
    unsigned short b;
    char pad3[4];
} ItemRec;

typedef struct {
    char pad[8];
    int t;
    char pad2[0x40];
} ItemDef;

extern ItemDef D_L00_00179AC0[] __attribute__((section(".data")));
extern ItemRec D_L00_001C40B0[] __attribute__((section(".data")));
extern int D_0013D428[];
extern int D_00141EA0[];
extern int D_L00_001B0340[] __attribute__((section(".data")));
extern int D_L00_001C3E98[] __attribute__((section(".data")));
extern int scale_game_frames(int) __asm__("FUN_001f96f8");
extern unsigned char D_0013D4C0[];
extern unsigned char D_0013D4E8[];
extern int D_00141408 __attribute__((section(".data")));
extern int D_00141410 __attribute__((section(".data")));
extern int D_00141414 __attribute__((section(".data")));
extern unsigned char D_0015EDD0[] __attribute__((section(".sdata")));
extern void FUN_L00_00263d40(int arg0, int arg1);

void FUN_L00_00260860(int id, int flag) {
    unsigned char *pa = &D_0013D4C0[id];
    unsigned char *pb = &D_0013D4E8[id];
    int idx = id + 0x25;
    int *p;
    int i;

    if (*pa == 0) {
        idx = id;
    }
    p = &D_L00_001B0340[idx];
    *pb = 1;
    if (*p != -1) {
        FUN_L00_00263d40(*p, scale_game_frames(0x12C));
    }
    if (*pa == 0) {
        ItemRec *r;
        *pa = 1;
        r = &D_L00_001C40B0[id];
        *pb = 1;
        if (r->a != 0) {
            int *q = &D_0013D428[id];
            int v = r->b;
            if (v < *q) {
                v = *q;
            }
            *q = v;
        }
        for (i = 0; i < 20; i++) {
            if (id != 0 && D_L00_001C3E98[i] == id) {
                int j;
                for (j = 0;; j++) {
                    unsigned char b = D_0015EDD0[j];
                    if ((b & 0x3F) == id || b == 0xFF) {
                        D_0015EDD0[j] = id | 0x40;
                        break;
                    }
                }
                break;
            }
        }
        if (flag != 0) {
            int t = D_L00_00179AC0[id].t;
            if (t == 0) {
                D_00141408 = id;
            } else if (t == 3) {
                D_00141414 = id;
            } else if (t == 2) {
                D_00141410 = id;
            }
        }
        if (D_L00_00179AC0[id].t == 0) {
            for (i = 0; i < 8 && D_00141EA0[i] != 0; i++) {
            }
            if (i < 8) {
                D_00141EA0[i] = id;
            }
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00260a88.s", FUN_L00_00260a88);
