/* Level overlay code after rendering/view; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

/* Returns the pointer at +8 of the moby data when flag 0x20 at 0x34 is set, else 0. */
char *FUN_L00_002603d0(char *m) {
    if (m == 0)
        return 0;
    if ((*(u16 *)(m + 0x34) & 0x20) == 0)
        return 0;
    return *(char **)(*(char **)(m + 0x78) + 8);
}
