/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/gameplay/hero.h"
#include "rnc/globals.h"
#include "rnc/math_consts.h"
#include "asm.h"
#include "rnc/gameplay/entities/moby.h"
#include "rnc/gameplay/state/item_state.h"
#include "rnc/gameplay/state/usage_stats.h"
#include "rnc/overlay/moby_anim.h"
#define MOBY(p) ((struct Moby *)(p))

#define NOT_SDA

#define MACRO_ADDR

/* Per-frame update of a pickup moby: waits for the player to come near, then grants the item. */
/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002CC828), where it is exact; names translated to the US level program. */

extern char D_0013E533[];
extern float FUN_001f9b80(void *, void *);
extern float fast_add_rotations(float, float) __asm__("FUN_001fa580");
extern int FUN_L00_00203908(int, int);
extern unsigned char D_0013D4C2[];
extern unsigned char D_0013D4E3[];
int memcard_save_data(int slot, int flags) __asm__("FUN_0020b178");
void mark_moby_for_removal(struct Moby *obj) __asm__("FUN_0020c828");

void FUN_L11_002cb668(struct Moby *moby) {
    switch (moby->state) {
    case 0:
        if (D_0013D4C2[4] != 0) {
            mark_moby_for_removal(moby);
        } else {
            moby->pos.z += 0.75f;
            moby->flags |= 1;
            moby->state = 1;
        }
        break;
    case 1:
        break;
    case 2:
        fast_add_rotations(moby->rot.z, frame_time * 4.7123890f);
        if (FUN_001f9b80(&moby->pos, D_0013E533 + 0xE9D) < 2.0f) {
            D_0013D4C2[4] = 1;
            D_0013D4E3[0xB] = 1;
            memcard_save_data(0, -1);
            FUN_L00_00203908(0x2AF8, 0x3A);
            mark_moby_for_removal(moby);
        }
        break;
    }
}
#include "qcopy.h"

/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002CC9D0), where it is exact; names translated to the US level program. */

extern char *func_0020D348_m(int);
extern f32 fast_subtract_rotations(f32, f32) __asm__("func_001FA5C8");
extern float FUN_L00_0025be00(float *p, float a, float *v, float b, float c, float d);
extern float fast_add_rotations_c(float, float) __asm__("func_001FA580");

void FUN_L11_002cb810(struct Moby *moby) {
    char *data = (char *)moby->pvars;
    int state = (unsigned char)MOBY(moby)->state;
    switch (state) {
    case 0:
        MOBY(moby)->state = 1;
        *(float *)(data + 4) = moby->rot.z;
        if ((moby->flags & 0x8000) == 0) {
            char *c = func_0020D348_m(0x41);
            *(short *)(c + 0x32) = moby->unk32;
            c[0x30] = moby->unk30;
            *(unsigned short *)(c + 0x34) = moby->flags | 0x8000;
            qcopy(c + 0x10, &moby->pos);
            qcopy(c + 0x40, &moby->rot);
            *(char **)(data + 8) = c;
            *(float *)(*(char **)(c + 0x78) + 4) = moby->rot.z;
        }
        break;
    case 1:
        break;
    case 2: {
        float f;
        if ((moby->flags & 0x8000) == 0)
            f = fast_add_rotations_c(*(float *)(data + 4), 0.20769417f);
        else
            f = fast_subtract_rotations(*(float *)(data + 4), 0.20769417f);
        if (FUN_L00_0025be00(&moby->rot.z, f, (float *)data, frame_time_sq * 0.34906584f, frame_time_sq * 0.34906584f, frame_time * 0.7853982f) == 0.0f)
            MOBY(moby)->state = 3;
        break;
    }
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002CCB50), where it is exact; names translated to the US level program. */

extern unsigned char D_0013D3E2[];

void FUN_L11_002cb990(struct Moby *moby) {
    char *state = (char *)moby->pvars;
    if (moby->oclass == 0x41 && moby->state == 1) {
        char *child;
        D_0013D3E2[0] = moby->state;
        moby->state = 2;
        child = *(char **)(state + 8);
        if (child)
            child[0x20] = 2;
    }
}

typedef struct {
    char pad00[0x10];
    float position[4];
    unsigned char state;
    char pad21[0x27];
    float yaw;
    char pad4C[7];
    unsigned char animation;
    char pad54[0x24];
    char *data;
} WM11;

typedef struct {
    char pad00[0x80];
    float position[4];
    char pad90[0x40];
    float aim[4];
} WP11;

typedef struct {
    float target[4];
    float eye[4];
    float delta[4];
} WS11;

typedef struct {
    char pad00[4];
    short h04;
    char pad06[6];
    float f0C;
    char pad10[0x30];
    int region;
    char pad44[0x2C];
    char body[0x64];
    float pitch;
    float yaw;
    char padDC[4];
    float height;
    char padE4[0xC];
    char head[0x68];
    float head_yaw;
    char pad15C[0x14];
    float target[4];
    char pad180[4];
    int moving_timer;
    int target_timer;
} WD11;

extern void FUN_L05_00317398(void *);
extern int FUN_00214720(void *, int);
extern int FUN_L00_00266448(void *, void *);
extern int FUN_L00_002668a0(void *, void *);
extern void FUN_L01_002783a8(void *, float);
extern void FUN_L00_00260860(int, int);
extern void FUN_L00_00284e50(void *, void *);
extern void memcard_save_data_d0710(int, int) __asm__("FUN_0020b178");
extern void FUN_L00_002039a0(void);
extern int FUN_L00_00203908(int, int);
extern unsigned char D_0013D4C3 __attribute__((section(".data")));
extern int D_L11_0015F5C4;
extern char D_0013E533[];
extern float FUN_001f9b80(void *, void *);
extern float FUN_001f9e90(float, float);
extern float fast_difference_between_rotations(float, float) __asm__("FUN_001fa688");
extern float FUN_001fa5c8(float, float);
extern float fast_add_rotations(float, float) __asm__("FUN_001fa580");
extern float FUN_001f9af0(void *);
extern float FUN_001f9b20(void *);
extern int scale_game_frames(int) __asm__("FUN_001f96f8");
extern int FUN_001f9740(int *);
extern float random_float_between(float, float) __asm__("FUN_002132a8");
extern float FUN_001f96b0(float);
extern int truncate_float_to_s32(float) __asm__("FUN_001fa6d0");
extern void FUN_00214db0(void *, float, float, float);
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a28(void *, void *, void *);
extern unsigned char D_0015EDB0;
extern void FUN_L00_002628d8(float, float, void *, void *, int);

/* Watcher update, same routine as FUN_L08_00302ce8 with this level's states and data layout. */
void FUN_L11_002d0710(WM11 *m) {
    WS11 scratch;
    WD11 *d = (WD11 *)m->data;
    float rate;
    float head_rate;
    int tracking;
    FUN_L05_00317398(m);
    switch (m->state) {
    case 0:
        if (D_0013D4C3) {
            m->state = 3;
        } else {
            m->state = 1;
        }
        FUN_L00_002668a0(m, d);
        d->f0C = 3.7f;
        break;
    case 1:
        if (FUN_00214720(hero.motion.pos.f, d->region)) {
            if (FUN_L00_00266448(m, d)) {
                FUN_L01_002783a8(m, 2.7f);
                m->state = 2;
            }
        }
        break;
    case 2:
        if (D_L11_0015F5C4 != 2) {
            m->state = 1;
            if (d->h04 == 2) {
                FUN_L00_00260860(3, 1);
                FUN_L00_00284e50(hero.motion.pos.f, hero.motion.pos.f + 4);
                memcard_save_data_d0710(0, -1);
                FUN_L00_002039a0();
                FUN_L00_00203908(0x2AFB, 0x3D);
            }
        }
        break;
    }
    rate = 0.02f;
    head_rate = 0.3f;
    tracking = 0;
    if (m->animation == 0) {
        char *player = D_0013E533 + 0xE9D;
        tracking = 1;
        if (FUN_001f9b80(m->position, player) < 8.0f &&
            fast_difference_between_rotations(
                m->yaw, FUN_001f9e90(((WP11 *)(D_0013E533 + 0xE1D))->aim[0] - m->position[0],
                                     ((WP11 *)(D_0013E533 + 0xE1D))->aim[1] - m->position[1])) <
                1.5707964f) {
            if (FUN_001f9af0(player + 0x80) > 0.01f)
                d->moving_timer = scale_game_frames(120);
            else
                FUN_001f9740(&d->moving_timer);
        } else if (d->moving_timer) {
            d->moving_timer = 0;
            qcopy(d->target, hero.motion.unkD0.f);
        }
        if (FUN_001f9740(&d->target_timer)) {
            float heading;
            d->target_timer =
                truncate_float_to_s32(FUN_001f96b0(random_float_between(180.0f, 300.0f)));
            heading = fast_add_rotations(m->yaw, random_float_between(-90.0f, 90.0f) * DEG_TO_RAD);
            FUN_00214db0(d->target, 6.0f, heading, random_float_between(0.0f, 30.0f) * DEG_TO_RAD);
            FUN_001f9a10(d->target, d->target, m->position);
        }
        if (d->moving_timer) {
            qcopy(scratch.target, hero.motion.unkD0.f);
            rate = 0.04f;
            head_rate = 0.3f;
        } else {
            qcopy(scratch.target, d->target);
        }
    }
    if (tracking) {
        float yaw;
        float pitch;
        qcopy(scratch.eye, m->position);
        scratch.eye[2] += 1.0f;
        FUN_001f9a28(scratch.delta, scratch.target, scratch.eye);
        yaw = FUN_001fa5c8(FUN_001f9e90(scratch.delta[0], scratch.delta[1]), m->yaw);
        pitch = -FUN_001f9e90(FUN_001f9b20(scratch.delta), scratch.delta[2]);
        if (yaw > 1.5707964f)
            yaw = 1.5707964f;
        else if (yaw < -1.5707964f)
            yaw = -1.5707964f;
        if (pitch > 0.5235988f)
            pitch = 0.5235988f;
        else if (pitch < -0.5235988f)
            pitch = -0.5235988f;
        d->pitch = pitch;
        d->head_yaw = d->yaw = yaw * 0.5f;
    }
    if (D_0015EDB0)
        d->height = 2.75f;
    FUN_L00_002628d8(rate * frame_scale_sq, head_rate * frame_scale_sq, m, d->body, 0);
    FUN_L00_002628d8(rate * frame_scale_sq, head_rate * frame_scale_sq, m, d->head, 1);
}

extern float FastVecDist(void *, void *) __asm__("FUN_001f9b48");

/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002D2168), where it is exact; names translated to the US level program. */

extern float D_L11_001677C0[];
extern void FUN_L00_0025a120(void *);
extern void FUN_L02_002e0cd8(void *);
extern void FUN_L11_002d1030(void *);
extern void FUN_L11_002d1340(void *);
extern void FUN_L11_002d14b0(void *);
void FUN_L11_002d27b0(WM11 *m);

void FUN_L11_002d0fa8(struct Moby *moby) {
    FUN_L02_002e0cd8(moby);
    if (moby->unk31 && FastVecDist(&moby->pos, D_L11_001677C0) < 38.0f) {
        FUN_L00_0025a120(moby);
        moby->unk7F = 30;
    }
    FUN_L11_002d1030(moby);
    FUN_L11_002d1340(moby);
    FUN_L11_002d14b0(moby);
    FUN_L11_002d27b0(moby);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L11_002d1030.s", FUN_L11_002d1030);
#include "qcopy.h"

/* moves the parts' positions and stores the moby's displacement since last frame */
/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002D2500), where it is exact; names translated to the US level program. */

extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_L00_00258830(int, int, float, float, float, int);
extern void FUN_L00_00261d78(float, void *, void *, void *);

void FUN_L11_002d1340(void *mp) {
    unsigned char *moby = mp;
    char *d = *(char **)(moby + 0x78);
    float A[4];
    float B[4];
    qcopy(A, moby + 0x10);
    qcopy(B, d + 0x130);
    FUN_L00_00258830((int)moby, (int)B, 0.5f, 0.3f, 0.0f, 0x10);
    if ((moby[0x20] >= 4 && moby[0x20] <= 6) || (moby[0x20] == 7 && *(int *)(d + 0x15C) == 3)) {
        FUN_L00_00261d78(0.3f, *(void **)(d + 0x60 - -(*(int *)(d + 0x158) * 4)), moby + 0x10,
                         moby + 0x10);
        switch (*(int *)(d + 0x158)) {
        case 2:
            FUN_L00_00261d78(0.3f, *(void **)(d + 0x80), moby + 0x10, moby + 0x10);
            FUN_L00_00261d78(0.3f, *(void **)(d + 0x84), moby + 0x10, moby + 0x10);
            FUN_L00_00261d78(0.3f, *(void **)(d + 0x88), moby + 0x10, moby + 0x10);
            break;
        case 3:
            FUN_L00_00261d78(0.3f, *(void **)(d + 0x80), moby + 0x10, moby + 0x10);
            FUN_L00_00261d78(0.3f, *(void **)(d + 0x84), moby + 0x10, moby + 0x10);
            break;
        }
    }
    FUN_001f9a28(d + 0x140, moby + 0x10, A);
}
extern int FUN_L11_002d2460(struct Moby *moby);
extern int FUN_L11_002d2340(struct Moby *moby, char *other);
extern int FUN_L11_002d25e8(struct Moby *m, float *out);
extern void set_state_14b0(struct Moby *moby, int state) __asm__("FUN_L11_002d2088");
extern float ground_height_14b0(void *) __asm__("FUN_L00_00259710");
extern void scale_vector_14b0(void *out, void *a, f32 s) __asm__("FUN_001f9bf8");
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f99f8(void *);
extern void FUN_001fa030(void *, void *);
extern void FUN_L05_0028be78(void *, int, int);
extern void FUN_L00_002502a0(int);
extern void FUN_L00_00266858(void *, int);
extern int FUN_L11_0030a830(struct Moby *arg);
extern void FUN_L11_0030a840(unsigned char *arg);
extern unsigned char D_0013D4EE __attribute__((section(".data")));
extern unsigned char D_0013D3DC __attribute__((section(".data")));
extern int D_0015ED84;
extern unsigned char D_0014C050[];
/* One of the level's path/spawn points (D_L11_001600EC, 0x80 bytes each). */
struct PokPathPoint {
    u8 pad00[0x30];
    Vec4f pos;
    u8 pad40[0x30];
    Vec4f rot;
};
extern struct PokPathPoint *path_points_14b0 __asm__("D_L11_001600EC");
extern int D_L11_0015FFD8;
extern int D_001413D4_14b0 __asm__("D_001413D4") __attribute__((section(".data")));
extern char D_L11_0016D270[];
extern float D_L11_00161410 __attribute__((sda));
extern float D_L11_00161414 __attribute__((sda));
extern float D_L11_00161418 __attribute__((sda));

/* Pvars of the path-walking NPC run by FUN_L11_002d0fa8. */
struct PokKeeperVars {
    u8 pad00[0x20];
    u8 talk[0xC];                     /* 0x20: talk prompt (FUN_L00_002668a0 / FUN_L00_00266448) */
    f32 talk_range;                   /* 0x2C */
    u8 pad30[0x26];
    s16 unk56;
    u8 pad58[8];
    s32 unk60[3];                     /* 0x60: FUN_L05_0028be78 handles, set from unk70[] */
    u8 pad6C[4];
    s32 unk70[3];
    u8 pad7C[0x54];
    s32 unkD0[4];
    s32 points[4];                    /* 0xE0: path point of each leg */
    s32 gates[2];                     /* 0xF0: gate mobys */
    s32 volumes[2];                   /* 0xF8 */
    s32 unk100;
    s32 unk104;
    s32 unk108;
    s32 unk10C;
    s32 unk110;
    s32 unk114;
    s32 unk118;
    u8 pad11C[4];
    Vec4f target;                     /* 0x120 */
    Vec4f unk130;
    Vec4f unk140;
    u8 pad150[8];
    s32 leg;                          /* 0x158 */
    s32 next_state;                   /* 0x15C: state entered once the walk animation ends */
};

/* NPC that talks to the hero, then walks a chain of level path points ahead of him, opening the
   gate mobys (FUN_L11_0030a840) and moving path points as it goes. */
void FUN_L11_002d14b0(void *arg) {
    struct Moby *moby = arg;
    struct PokKeeperVars *d = (struct PokKeeperVars *)moby->pvars;
    int proximity = FUN_L11_002d2460(moby);
    float v[4];
    float r[4];

    if (moby->state >= 3 && moby->state <= 5 && proximity == 0) {
        set_state_14b0(moby, 6);
        return;
    }
    if (moby->state >= 4 && moby->state <= 6) {
        scale_vector_14b0(v, &moby->unkC0, 3.0f);
        FUN_001f9a10(v, v, &moby->pos);
        if (FUN_L11_002d25e8(moby, v)) {
            qcopy(&d->target, v);
            d->target.z = ground_height_14b0(&d->target);
            d->next_state = 3;
            set_state_14b0(moby, 7);
        }
    }
    switch (moby->state) {
    case 0:
        FUN_L00_002668a0(moby, d->talk);
        moby->unk30 = 0xFF;
        FUN_L05_0028be78(&d->unk60[0], 1, d->unk70[0]);
        FUN_L05_0028be78(&d->unk60[1], 1, d->unk70[1]);
        FUN_L05_0028be78(&d->unk60[2], 1, d->unk70[2]);
        FUN_001f99f8(&d->unk130);
        FUN_001f99f8(&d->unk140);
        if (D_0013D4EE) {
            if (D_0014C050[d->unk10C + D_0015ED84 * 16] == 0xFF) {
                FUN_L11_0030a840((unsigned char *)(D_L11_0015FFD8 + (d->gates[0] << 8)));
                FUN_L11_0030a840((unsigned char *)(D_L11_0015FFD8 + (d->gates[1] << 8)));
                FUN_L11_002cb990((struct Moby *)(D_L11_0015FFD8 + (d->unk104 << 8)));
                mark_moby_for_removal(moby);
                break;
            }
        } else {
            if (D_0014C050[d->unk10C + D_0015ED84 * 16] == 0xFF) {
                d->leg = 3;
                qcopy_nc(&moby->pos, &path_points_14b0[d->points[3]].pos);
                qcopy_nc(&moby->rot, &path_points_14b0[d->points[3]].rot);
                FUN_L11_002cb990((struct Moby *)(D_L11_0015FFD8 + (d->unk104 << 8)));
                set_state_14b0(moby, 0xE);
                d->talk_range = 10.0f;
                FUN_L11_0030a840((unsigned char *)(D_L11_0015FFD8 + (d->gates[0] << 8)));
                FUN_L11_0030a840((unsigned char *)(D_L11_0015FFD8 + (d->gates[1] << 8)));
                break;
            }
        }
        if (D_0014C050[d->unk108 + D_0015ED84 * 16] == 0xFF &&
            FastVecDist(&hero.motion.pos, &path_points_14b0[d->points[1]].pos) < 12.0f) {
            d->leg = 1;
            qcopy_nc(&moby->pos, &path_points_14b0[d->points[1]].pos);
            qcopy_nc(&moby->rot, &path_points_14b0[d->points[1]].rot);
            set_state_14b0(moby, 6);
            path_points_14b0[d->unk114].pos.z -= 500.0f;
            FUN_L11_0030a840((unsigned char *)(D_L11_0015FFD8 + (d->gates[0] << 8)));
            break;
        }
        path_points_14b0[d->unk110].pos.z -= 500.0f;
        path_points_14b0[d->unk114].pos.z -= 500.0f;
        d->leg = 0;
        d->talk_range = 5.0f;
        set_state_14b0(moby, 1);
        break;
    case 1:
        if (d->unk56 == 0) {
            if (hero.air_frames.s == 0 && FUN_L00_00266448(moby, d->talk)) {
                FUN_L01_002783a8(moby, 2.5f);
                set_state_14b0(moby, 2);
            }
        } else if (FUN_001f9b80(&moby->pos, &hero.motion.pos) < 6.0f) {
            set_state_14b0(moby, 3);
        }
        break;
    case 2:
        if (D_L11_0015F5C4 != 2)
            set_state_14b0(moby, 3);
        break;
    case 3:
        if (FUN_001f9b80(&moby->pos, &hero.motion.pos) > 6.0f &&
            FUN_L11_002d2340(moby, (char *)&hero.motion.pos) && proximity == 1)
            set_state_14b0(moby, 4);
        break;
    case 4:
        if (FUN_001f9b80(&moby->pos, &hero.motion.pos) < 3.0f ||
            !FUN_L11_002d2340(moby, (char *)&hero.motion.pos) || proximity == 2)
            set_state_14b0(moby, 3);
        else if (FUN_001f9b80(&moby->pos, &hero.motion.pos) > 8.0f)
            set_state_14b0(moby, 5);
        break;
    case 5:
        if (FUN_001f9b80(&moby->pos, &hero.motion.pos) < 3.0f ||
            !FUN_L11_002d2340(moby, (char *)&hero.motion.pos) || proximity == 2)
            set_state_14b0(moby, 3);
        else if (FUN_001f9b80(&moby->pos, &hero.motion.pos) < 4.0f)
            set_state_14b0(moby, 4);
        break;
    case 6:
        FUN_L11_002d2340(moby, (char *)&path_points_14b0[d->points[d->leg]].pos);
        if (FUN_001f9b80(&moby->pos, &d->target) < 1.0f) {
            switch (d->leg) {
            case 0: {
                struct Moby *o = (struct Moby *)(D_L11_0015FFD8 + (d->gates[0] << 8));
                qcopy(&d->target, &o->pos);
                scale_vector_14b0(v, &o->unkC0, D_L11_00161418);
                FUN_001f9a10(&d->target, &d->target, v);
                scale_vector_14b0(v, &o->unkD0, D_L11_00161414);
                FUN_001f9a10(&d->target, &d->target, v);
                scale_vector_14b0(v, &o->unkE0, D_L11_00161410);
                FUN_001f9a10(&d->target, &d->target, v);
                d->next_state = 8;
                set_state_14b0(moby, 7);
                break;
            }
            case 1: {
                struct Moby *o = (struct Moby *)(D_L11_0015FFD8 + (d->gates[1] << 8));
                qcopy(&d->target, &o->pos);
                scale_vector_14b0(v, &o->unkC0, D_L11_00161418);
                FUN_001f9a10(&d->target, &d->target, v);
                scale_vector_14b0(v, &o->unkD0, -D_L11_00161414);
                FUN_001f9a10(&d->target, &d->target, v);
                scale_vector_14b0(v, &o->unkE0, D_L11_00161410);
                FUN_001f9a10(&d->target, &d->target, v);
                path_points_14b0[d->unk110].pos.z += 500.0f;
                d->next_state = 8;
                set_state_14b0(moby, 7);
                break;
            }
            case 2:
                set_state_14b0(moby, 0xB);
                break;
            case 3:
                path_points_14b0[d->unk114].pos.z += 500.0f;
                set_state_14b0(moby, 0xC);
                break;
            }
        }
        break;
    case 12:
        d->talk_range = 255.0f;
        if (FUN_L00_00266448(moby, d->talk)) {
            FUN_L00_002502a0(d->unk10C);
            D_0013D3DC = 1;
            FUN_L00_00266858(moby, 2);
            qcopy_nc(&moby->pos, &path_points_14b0[d->points[d->leg]].pos);
            qcopy_nc(&moby->rot, &path_points_14b0[d->points[d->leg]].rot);
            FUN_001fa030(&moby->unkC0, &moby->rot);
            scale_vector_14b0(v, &moby->unkC0, 2.0f);
            FUN_001f9a10(v, v, &moby->pos);
            qcopy(r, &moby->rot);
            r[2] = fast_add_rotations(r[2], 3.14159f);
            qcopy(D_L11_0016D270, v);
            qcopy(D_L11_0016D270 + 0x10, r);
            *(short *)(D_L11_0016D270 + 0x36) = 1;
            FUN_L01_002783a8(moby, 2.5f);
            set_state_14b0(moby, 0xD);
        }
        break;
    case 13:
        if (D_L11_0015F5C4 != 2) {
            FUN_L11_002cb990((struct Moby *)(D_L11_0015FFD8 + (d->unk104 << 8)));
            set_state_14b0(moby, 0xE);
        }
        break;
    case 7:
        if (moby->unk70 & 2)
            set_state_14b0(moby, d->next_state);
        break;
    case 8:
        if (FUN_001f9b80(&moby->pos, &d->target) < 0.5f)
            set_state_14b0(moby, 9);
        break;
    case 9:
        {
            int i = d->leg != 0;
            if (FUN_L11_0030a830((struct Moby *)(D_L11_0015FFD8 + (d->gates[i] << 8))))
                set_state_14b0(moby, 0xA);
        }
        break;
    case 10:
        if (FUN_001f9b80(&moby->pos, &d->target) < 0.5f) {
            int n = ++d->leg;
            qcopy(&d->target, &path_points_14b0[d->unkD0[n]].pos);
            d->next_state = 4;
            set_state_14b0(moby, 7);
        }
        break;
    case 11:
        if (FUN_L11_0030a830((struct Moby *)(D_L11_0015FFD8 + (d->unk100 << 8)))) {
            d->leg += 1;
            set_state_14b0(moby, 3);
        }
        break;
    case 14:
        if (D_0014C050[d->unk118 + D_0015ED84 * 16] == 0xFF && D_001413D4_14b0 != 0x32 &&
            FUN_L00_00266448(moby, d->talk)) {
            FUN_L01_002783a8(moby, 2.5f);
            set_state_14b0(moby, 0xF);
        }
        break;
    case 15:
        if (D_L11_0015F5C4 != 2) {
            FUN_L00_00260860(6, 1);
            memcard_save_data(0, -1);
            FUN_L00_00203908(0x2AF8, 0x3A);
            mark_moby_for_removal(moby);
        }
        break;
    }
}
extern int FUN_001f96f8(int);
extern void FUN_00212f90(void *, int, int, int);
extern void FUN_001f99f8(void *);
extern void FUN_001f9cf8(void *, void *, void *);
extern void FUN_001f9a10(void *, void *, void *);
extern float D_L11_001613D0 __attribute__((sda));
extern float D_L11_001613D4 __attribute__((sda));
extern float D_L11_001613E0 __attribute__((sda));
extern float D_L11_00161400 __attribute__((sda));
extern int D_L11_0015FFD8;

void FUN_L11_002d2088(struct Moby *moby, unsigned char state) {
    char *d = (char *)moby->pvars;
    float tmp[4];

    moby->state = state;
    switch (moby->state) {
    case 1:
    case 3:
    case 11:
    case 12:
    case 14:
        if (moby->prev_seq != 0)
            FUN_00212f90(moby, 0, 0, FUN_001f96f8(0x14));
        if (moby->state == 14)
            *(float *)(d + 0x2C) = 10.0f;
        FUN_001f99f8(d + 0x130);
        if (moby->state == 14)
            *(short *)(d + 0x56) = 2;
        break;
    case 4:
        if (moby->prev_seq != 2)
            FUN_00212f90(moby, 2, 0, FUN_001f96f8(0x14));
        *(float *)(d + 0x154) = D_L11_001613D0 * frame_time;
        break;
    case 5:
    case 6:
        if (moby->prev_seq != 3)
            FUN_00212f90(moby, 3, 0, FUN_001f96f8(0x14));
        *(float *)(d + 0x154) = D_L11_001613D4 * frame_time;
        break;
    case 7:
        if (moby->prev_seq != 4)
            FUN_00212f90(moby, 4, 0, FUN_001f96f8(0x14));
        FUN_001f99f8(d + 0x130);
        break;
    case 8:
        if (moby->prev_seq != 3)
            FUN_00212f90(moby, 3, 0, FUN_001f96f8(0x14));
        {
            int *tbl = (int *)(d + 0xF0);
            unsigned int idx = 0U < *(unsigned int *)(d + 0x158);
            int p;
            char *o;
            tbl += idx;
            p = *tbl;
            o = (char *)D_L11_0015FFD8;
            o += p << 8;
            qcopy(d + 0x120, o + 0x10);
            FUN_001f9cf8(tmp, &D_L11_001613E0, o + 0xC0);
            FUN_001f9a10(d + 0x120, d + 0x120, tmp);
        }
        break;
    case 9:
    case 16:
        if (moby->prev_seq != 0)
            FUN_00212f90(moby, 0, 0, FUN_001f96f8(0x14));
        FUN_001f99f8(d + 0x130);
        break;
    case 10:
        if (moby->prev_seq != 3)
            FUN_00212f90(moby, 3, 0, FUN_001f96f8(0x14));
        {
            int *tbl = (int *)(d + 0xF0);
            unsigned int idx = 0U < *(unsigned int *)(d + 0x158);
            int p;
            char *o;
            tbl += idx;
            p = *tbl;
            o = (char *)D_L11_0015FFD8;
            o += p << 8;
            qcopy(d + 0x120, o + 0x10);
            FUN_001f9cf8(tmp, &D_L11_00161400, o + 0xC0);
            FUN_001f9a10(d + 0x120, d + 0x120, tmp);
        }
        break;
    default:
        break;
    }
}
/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002D3500), where it is exact; names translated to the US level program. */

struct TgtData {
    char pad0[0x60];
    int a[4];
    int b[4];
    int c[4];
    char pad1[0x90];
    char e[0x38];
    int idx;
};

extern int *D_L11_001B0EB0[];
extern int FUN_L00_00259740(void *, void *, int);
extern int FUN_L01_00276fe8(int *, int, int, void *, void *, void *, float);

int FUN_L11_002d2340(struct Moby *moby, char *other) {
    struct TgtData *d = (struct TgtData *)moby->pvars;
    int *p = d->a;
    int *ent = D_L11_001B0EB0[*(int *)((char *)p - (-(d->idx * 4)))];
    int buf[8];
    int n;
    if (FUN_L00_00259740(other, ent + 4, *ent) == 0)
        return 0;
    buf[0] = *(int *)((char *)p - (-(d->idx * 4)));
    n = 1;
    switch (d->idx) {
    case 2:
        n = 4;
        buf[1] = d->c[0];
        buf[2] = d->c[1];
        buf[3] = d->c[2];
        break;
    case 3:
        n = 3;
        buf[1] = d->c[0];
        buf[2] = d->c[1];
        break;
    default:
        break;
    }
    return FUN_L01_00276fe8(buf, n, d->b[d->idx], &moby->pos, other, d->e, 0.2f) != 0;
}
extern int D_L11_0015FFD8;
extern int FUN_L11_00316128(char *);
extern short *D_L11_001AC240[];
extern int D_L11_0015FFF4_i __asm__("D_L11_0015FFF4");
extern float FUN_001f9b48(void *, void *);

struct TargetSets {
    char pad0[0x90];
    struct {
        short group;
        short pad;
    } sets[9][4];
    char pad120[0x38];
    int set;
};

/* 2 when a live moby of the current target groups is within 10 units, 1 when one is alive, else 0. */
int FUN_L11_002d2460(struct Moby *moby) {
    struct TargetSets *d = (struct TargetSets *)moby->pvars;
    int found = 0;
    int i;
    int group;
    short *p;

    for (i = 0; i < 4; i++) {
        group = d->sets[d->set][i].group;
        if (group < 0 || group > D_L11_0015FFF4_i)
            break;
        p = D_L11_001AC240[group];
        if (p == 0)
            continue;
        do {
            int offset = (*p & 0x7fff) << 8;
            struct Moby *other = (struct Moby *)(offset + D_L11_0015FFD8);
            if ((signed char)other->state >= 0) {
                if (other->oclass != 0x4de || FUN_L11_00316128((char *)other) == 0) {
                    found = 1;
                    if (FUN_001f9b48(&moby->pos, &((struct Moby *)(D_L11_0015FFD8 + offset))->pos) < 10.0f)
                        return 2;
                }
            }
        } while (*p++ >= 0);
    }
    return found;
}
/* Tests whether a moby can drop onto the ground, writing the landing point. */
/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002D37A8), where it is exact; names translated to the US level program. */

extern f32 vector_length_xyz(void *a) __asm__("FUN_001f9af0");
extern int FUN_001efa68(void *, void *, int, void *, int);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void normalize_vector_xyz(void *out, void *a, f32 len) __asm__("FUN_001f9bf8");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
float AbsoluteFloat(float input) __asm__("func_001F99C0");
s32 is_point_inside_clip_volume(s32 arg0, s32 arg1) __asm__("FUN_00214720");
void FUN_L00_00259710(void *a);
extern float func_L00_0025A748_f(void *) __asm__("FUN_L00_00259710");

int FUN_L11_002d25e8(struct Moby *m, float *out) {
    char *s = (char *)m->pvars;
    int *p = (int *)(s + 0xF8);
    int i;
    int found = 0;
    float a[4];
    float b[4];
    float g;
    for (i = 0; i < 2; i++) {
        if (is_point_inside_clip_volume(&m->pos, *p)) {
            found = 1;
            break;
        }
        p++;
    }
    if (found) {
        float *pos = &m->pos.x;
        subtract_vector_xyz(a, out, pos);
        if (vector_length_xyz(a) > 4.0f)
            normalize_vector_xyz(a, a, 4.0f);
        add_vector_xyz(a, a, pos);
        {
            int *q = D_L11_001B0EB0[*(int *)(s - (-(*(int *)(s + 0x158) * 4)) + 0x60)];
            if (FUN_L00_00259740(a, q + 4, *q)) {
                a[2] += 5.0f;
                g = func_L00_0025A748_f(a);
                if (AbsoluteFloat(g - m->pos.z) > 0.5f) {
                    qcopy(b, pos);
                    b[2] += 0.15f;
                    a[2] = g + 0.15f;
                    if (FUN_001efa68(b, a, 2, m, 0)) {
                        a[2] = g;
                        qcopy(out, a);
                        return 1;
                    }
                }
            }
        }
    }
    return 0;
}
typedef struct {
    char pad000[0x160];
    char body[0x64];
    float pitch;
    float yaw;
    char pad1CC[4];
    float height;
    char pad1D4[0xC];
    char head[0x68];
    float head_yaw;
} WD11b;


/* Guard head update: in its watching states it turns its body and head toward the hero. */
void FUN_L11_002d27b0(WM11 *m) {
    WS11 scratch;
    WD11b *d = (WD11b *)m->data;
    float rate;
    float head_rate;
    int tracking;
    rate = 0.02f;
    head_rate = 0.3f;
    switch (m->state) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 11:
    case 12:
    case 14:
    case 16:
        tracking = 1;
        qcopy(scratch.target, &hero.motion.pos);
        break;
    default:
        tracking = 0;
        break;
    }
    if (tracking) {
        float yaw;
        float pitch;
        qcopy(scratch.eye, m->position);
        scratch.eye[2] += 1.0f;
        FUN_001f9a28(scratch.delta, scratch.target, scratch.eye);
        yaw = FUN_001fa5c8(FUN_001f9e90(scratch.delta[0], scratch.delta[1]), m->yaw);
        pitch = -FUN_001f9e90(FUN_001f9b20(scratch.delta), scratch.delta[2]);
        if (yaw > 1.2217305f)
            yaw = 1.2217305f;
        else if (yaw < -1.2217305f)
            yaw = -1.2217305f;
        if (pitch > 0.2617994f)
            pitch = 0.2617994f;
        else if (pitch < -0.5235988f)
            pitch = -0.5235988f;
        d->pitch = pitch;
        d->yaw = yaw * 0.7f;
        d->head_yaw = yaw * 0.3f;
    }
    if (D_0015EDB0)
        d->height = 2.75f;
    FUN_L00_002628d8(rate * frame_scale_sq, head_rate * frame_scale_sq, m, d->body, 0);
    FUN_L00_002628d8(rate * frame_scale_sq, head_rate * frame_scale_sq, m, d->head, 1);
}
/* Pokitaru sentry pvars (class of FUN_L11_002f0e40). */
struct PokSentryVars {
    char pad00[4];
    short h04;
    char pad06[6];
    float f0C;
    char pad10[0x38];
    int slot;
    char pad4C[4];
    char body[0x64];
    float pitch;
    float yaw;
    char padBC[4];
    float height;
    char padC4[0xC];
    char head[0x68];
    float head_yaw;
    char pad13C[0x14];
    float target[4];
    int moving_timer;
    int target_timer;
};

extern unsigned char D_0013D50B __attribute__((section(".data")));
extern int D_0015EEA4;
extern int D_0015ED84;
extern unsigned char D_0014C050[];
extern char *D_L11_001600EC;
extern struct UsageStat usage_stats_f0e40[] __asm__("D_00141968") __attribute__((section(".data")));
extern void DeleteMoby_f0e40(void *) __asm__("FUN_0020c828");
extern float AbsoluteFloat_f0e40(float) __asm__("FUN_001f99c0");
extern void FUN_L00_002502a0(int);
extern void FUN_L00_00263d40(int, int);

void FUN_L11_002f0e40(struct Moby *moby) {
    WS11 scratch;
    struct PokSentryVars *d = (struct PokSentryVars *)moby->pvars;
    float rate;
    float head_rate;
    int tracking;

    FUN_L02_002e0cd8(moby);
    if (moby->unk31 && FastVecDist(&moby->pos, D_L11_001677C0) < 30.0f) {
        FUN_L00_0025a120(moby);
        moby->unk7F = 24;
    }
    switch (moby->state) {
    case 0:
        moby->state = 1;
        if (moby->prev_seq != 1)
            FUN_00212f90(moby, 1, 0, scale_game_frames(20));
        if (D_0013D50B) {
            DeleteMoby_f0e40(moby);
            return;
        }
        FUN_L00_002668a0(moby, d);
        d->f0C = 4.0f;
        break;
    case 1:
        if (FUN_L00_00266448(moby, d)) {
            FUN_L01_002783a8(moby, 3.0f);
            moby->state = 2;
        }
        if (alternate_item_available[1] == 0 && discount_purchase_pricing[0] == 0) {
            if (FastVecDist(&moby->pos, hero.motion.pos.f) < 4.0f) {
                int t = scale_game_frames(D_0015EEA4) - usage_stats_f0e40[0x86].unk2 * 600;
                if ((int)(scale_game_frames(18) * 60.0f) < t || usage_stats_f0e40[0x86].unk2 * 600 == 0) {
                    FUN_L00_00203908(0x2B03, 0x86);
                } else if (scale_game_frames(D_0015EEA4) / 600 > usage_stats_f0e40[0x86].unk2) {
                    usage_stats_f0e40[0x86].unk2 = scale_game_frames(D_0015EEA4) / 600;
                }
            }
        }
        if (D_0014C050[moby->unkB0 + D_0015ED84 * 16] != 0xFF &&
            FastVecDist(hero.motion.pos.f, &moby->pos) < 4.0f &&
            AbsoluteFloat_f0e40(hero.motion.pos.f[2] - moby->pos.z) < 4.0f) {
            char *entry;
            FUN_L00_002502a0(moby->unkB0);
            entry = D_L11_001600EC + d->slot * 128;
            FUN_L00_00284e50(entry + 0x30, entry + 0x70);
        }
        break;
    case 2:
        if (D_L11_0015F5C4 != 2) {
            moby->state = 1;
            if (d->h04 == 2) {
                alternate_item_available[1] = 0;
                discount_purchase_pricing[0] = 1;
                D_0013D50B = 1;
                FUN_L00_00263d40(0x2B06, scale_game_frames(300));
                memcard_save_data_d0710(0, -1);
                FUN_L00_00203908(0x2AF9, 0x3B);
            }
        }
        break;
    }
    rate = 0.02f;
    head_rate = 0.3f;
    tracking = 0;
    if (moby->prev_seq == 1) {
        char *player = D_0013E533 + 0xE9D;
        tracking = 1;
        if (FUN_001f9b80(&moby->pos, player) < 8.0f &&
            fast_difference_between_rotations(
                moby->rot.z, FUN_001f9e90(((WP11 *)(D_0013E533 + 0xE1D))->aim[0] - moby->pos.x,
                                          ((WP11 *)(D_0013E533 + 0xE1D))->aim[1] - moby->pos.y)) <
                1.5707964f) {
            if (FUN_001f9af0(player + 0x80) > 0.01f)
                d->moving_timer = scale_game_frames(120);
            else
                FUN_001f9740(&d->moving_timer);
        } else if (d->moving_timer) {
            d->moving_timer = 0;
            qcopy(d->target, hero.motion.unkD0.f);
        }
        if (FUN_001f9740(&d->target_timer)) {
            float heading;
            d->target_timer =
                truncate_float_to_s32(FUN_001f96b0(random_float_between(180.0f, 300.0f)));
            heading = fast_add_rotations(moby->rot.z, random_float_between(-90.0f, 90.0f) * DEG_TO_RAD);
            FUN_00214db0(d->target, 6.0f, heading, random_float_between(0.0f, 30.0f) * DEG_TO_RAD);
            FUN_001f9a10(d->target, d->target, &moby->pos);
        }
        if (d->moving_timer) {
            qcopy(scratch.target, hero.motion.unkD0.f);
            rate = 0.04f;
            head_rate = 0.3f;
        } else {
            qcopy(scratch.target, d->target);
        }
    }
    if (tracking) {
        float yaw;
        float pitch;
        qcopy(scratch.eye, &moby->pos);
        scratch.eye[2] += 1.0f;
        FUN_001f9a28(scratch.delta, scratch.target, scratch.eye);
        yaw = FUN_001fa5c8(FUN_001f9e90(scratch.delta[0], scratch.delta[1]), moby->rot.z);
        pitch = -FUN_001f9e90(FUN_001f9b20(scratch.delta), scratch.delta[2]);
        if (yaw > 1.5707964f)
            yaw = 1.5707964f;
        else if (yaw < -1.5707964f)
            yaw = -1.5707964f;
        if (pitch > 0.5235988f)
            pitch = 0.5235988f;
        else if (pitch < -0.5235988f)
            pitch = -0.5235988f;
        d->pitch = pitch;
        d->head_yaw = d->yaw = yaw * 0.5f;
    }
    if (D_0015EDB0)
        d->height = 2.75f;
    FUN_L00_002628d8(rate * frame_scale_sq, head_rate * frame_scale_sq, moby, d->body, 0);
    FUN_L00_002628d8(rate * frame_scale_sq, head_rate * frame_scale_sq, moby, d->head, 1);
}
#include "qcopy.h"

extern float D_0013F3D8_2518 __asm__("D_0013F3D8") __attribute__((section(".data")));          /* hero z */
extern int D_0015ED84_2518 __asm__("D_0015ED84");
extern unsigned char D_0014C050_2518[] __asm__("D_0014C050");
extern int D_0013CAE4_2518 __asm__("D_0013CAE4") __attribute__((section(".data")));
extern int D_L11_0015F594_2518 __asm__("D_L11_0015F594");
extern char *D_L11_0015FFD8_2518 __asm__("D_L11_0015FFD8");
extern unsigned char D_001413F5_2518 __asm__("D_001413F5") __attribute__((section(".data")));
extern unsigned char D_0013D3DD_2518 __asm__("D_0013D3DD") __attribute__((section(".data")));
extern float D_0015ED6C_2518 __asm__("D_0015ED6C");
extern float D_0015ED70_2518 __asm__("D_0015ED70");
extern float D_L11_00161910_2518 __asm__("D_L11_00161910") __attribute__((sda));
extern float D_L11_00161914_2518 __asm__("D_L11_00161914") __attribute__((sda));
extern float D_L11_00161918_2518 __asm__("D_L11_00161918") __attribute__((sda));
extern char *create_moby_2518(int) __asm__("FUN_0020c4f8");
extern float fast_add_rotations_2518(float, float) __asm__("FUN_001fa580");
extern void FUN_L11_002f3040_2518(char *) __asm__("FUN_L11_002f3040");
extern void FUN_L11_002f2cd0_2518(char *) __asm__("FUN_L11_002f2cd0");
extern void FUN_L11_002f2d58_2518(char *) __asm__("FUN_L11_002f2d58");
extern void FUN_L01_003092d0_2518(char *) __asm__("FUN_L01_003092d0");
extern int allocate_voice_2518(int, int, void *) __asm__("FUN_0022da68");
extern void FUN_L00_00233ee8_2518(float *, int, float) __asm__("FUN_L00_00233ee8");
extern void FUN_L00_002598b0_2518(int, float, void *, int, float, float, int, int, int) __asm__("FUN_L00_002598b0");
extern int FUN_L00_00233f38_2518(void) __asm__("FUN_L00_00233f38");
extern void advance_accelerated_scalar_2518(float *, float *, float, float, float, float) __asm__("FUN_00213f38");
extern void approach_value_2518(float *, float, float) __asm__("FUN_00213ed8");
extern void FUN_L00_00216f90_2518(void *, void *, int, int) __asm__("FUN_L00_00216f90");
extern void FUN_L01_0027a248_2518(int, int) __asm__("FUN_L01_0027a248");
extern int enqueue_callback_2518(void (*)(char *), char *) __asm__("FUN_001f4600");

/* L11 twin of FUN_L01_00308bd8: a three-part switch moby that, once the hero
 * stands on it in mission state 0xB and presses the button, swings its parts
 * open and moves the linked moby (or its fallback) along. */
void FUN_L11_002f2518(struct Moby *moby) {
    char *data = (char *)moby->pvars;

    switch (moby->state) {
    case 0: {
        char **slots = (char **)(data + 0x14);
        int i;
        int j;
        moby->state = 1;
        for (i = 0; i < 3; i++) {
            struct Hero *g = &hero;
            char *c;
            slots[i] = create_moby_2518(0x13B);
            *(short *)(slots[i] + 0x32) = 0x40;
            slots[i][0x31] = 1;
            *(long *)(slots[i] + 0x38) = *(long *)(((char *)g->moby) + 0x38);
            *(unsigned short *)(slots[i] + 0x34) = moby->flags;
            c = slots[i];
            qcopy(c + 0x10, &moby->pos);
            qcopy(c + 0x40, &moby->rot);
            *(float *)(slots[i] + 0x48) =
                fast_add_rotations_2518(*(float *)(c + 0x48), (float)i * 2.0943952f);
        }
        if (*(int *)(data + 8) >= 0 && D_0014C050_2518[*(int *)(data + 8) + D_0015ED84_2518 * 16] != 0xFF) {
            moby->unk31 = 0;
            moby->flags |= 1;
            moby->unk94 = 0;
            for (j = 0; j < 3; j++) {
                *(unsigned short *)(slots[j] + 0x34) |= 1;
                slots[j][0x31] = 0;
                *(int *)(slots[j] + 0x94) = 0;
            }
        }
        FUN_L01_003092d0_2518(moby);
        break;
    }
    case 1: {
        struct Hero *g;
        if (*(int *)data == -1)
            break;
        if ((moby->flags & 1) && *(int *)(data + 8) >= 0 &&
            D_0014C050_2518[*(int *)(data + 8) + D_0015ED84_2518 * 16] == 0xFF)
            FUN_L11_002f3040_2518(moby);
        g = &hero;
        if (((char *)g->ground_moby) != moby)
            break;
        if (g->air_frames.s != 0)
            break;
        FUN_L11_002f2cd0_2518(moby);
        if (!(D_0013CAE4_2518 & 0x10))
            break;
        if (D_L11_0015F594_2518 != 0xB)
            break;
        allocate_voice_2518(0, 0, (void *)moby);
        moby->state = 2;
        *(int *)(data + 0x28) = 0;
        *(int *)(data + 0x2C) = 0;
        FUN_L00_00233ee8_2518(&moby->pos.x, 0, moby->rot.z);
        FUN_L00_002598b0_2518((int)moby, 1.5f, &moby->pos, 0x10000, 20.0f, 1.0f, 0, 1, 0);
        break;
    }
    case 2: {
        int r = FUN_L00_00233f38_2518();
        if (*(float *)(data + 0x20) < 1.0f) {
            advance_accelerated_scalar_2518((float *)(data + 0x20), (float *)(data + 0x28), 1.0f,
                                            D_L11_00161910_2518 * D_0015ED70_2518,
                                            D_L11_00161914_2518 * D_0015ED70_2518,
                                            D_L11_00161918_2518 * D_0015ED6C_2518);
        } else if (*(float *)(data + 0x24) < 1.0f) {
            advance_accelerated_scalar_2518((float *)(data + 0x24), (float *)(data + 0x2C), 1.0f,
                                            D_L11_00161910_2518 * D_0015ED70_2518,
                                            D_L11_00161914_2518 * D_0015ED70_2518,
                                            D_L11_00161918_2518 * D_0015ED6C_2518);
        } else if (D_L11_0015F594_2518 != 0xB || !(*(float *)(data + 0x20) > 0.25f)) {
            if (r == 2) {
                *(float *)(data + 0x3C) = 1.95f;
                moby->state = 3;
            } else if (r == 0) {
                moby->state = 4;
            }
        }
        FUN_L01_003092d0_2518(moby);
        break;
    }
    case 3:
        if (*(float *)(data + 0x3C) != 0.0f) {
            enqueue_callback_2518(FUN_L11_002f2d58_2518, moby);
            approach_value_2518((float *)(data + 0x3C), 0.0f, D_0015ED6C_2518 * 4.0f);
        } else {
            char *t = D_L11_0015FFD8_2518 + (*(int *)data << 8);
            char *td;
            float v[4];
            if (*(int *)(data + 4) != -1 &&
                D_0014C050_2518[*(int *)(data + 0xC) + D_0015ED84_2518 * 16] == 0xFF)
                t = D_L11_0015FFD8_2518 + (*(int *)(data + 4) << 8);
            td = *(char **)(t + 0x78);
            qcopy(v, t + 0x10);
            v[2] += 0.2f;
            FUN_L00_00216f90_2518(v, t + 0x40, 0, 1);
            D_001413F5_2518 = 1;
            if (*(int *)(data + 0x30) != -1 && *(int *)(data + 0x34) != -1) {
                FUN_L01_0027a248_2518(*(int *)(data + 0x30), *(int *)(data + 0x34));
            }
            FUN_L11_002f3040_2518(t);
            *(unsigned char *)(t + 0x20) = 4;
            *(float *)(td + 0x3C) = 0.0f;
            *(float *)(td + 0x28) = 0.0f;
            *(float *)(td + 0x2C) = 0.0f;
            *(float *)(td + 0x20) = 1.0f;
            *(float *)(td + 0x24) = 1.0f;
            allocate_voice_2518(1, 0, (void *)t);
            moby->state = 1;
            *(float *)(data + 0x20) = 0.0f;
            *(float *)(data + 0x24) = 0.0f;
            *(float *)(data + 0x28) = 0.0f;
            *(float *)(data + 0x2C) = 0.0f;
            *(float *)(data + 0x3C) = 1.95f;
            FUN_L01_003092d0_2518(moby);
        }
        break;
    case 4:
        if (D_0013F3D8_2518 < 138.0f)
            D_0013D3DD_2518 = 1;
        if (*(float *)(data + 0x3C) < 1.95f) {
            enqueue_callback_2518(FUN_L11_002f2d58_2518, moby);
            approach_value_2518((float *)(data + 0x3C), 1.95f, D_0015ED6C_2518 * 4.0f);
        } else if (0.0f < *(float *)(data + 0x24)) {
            advance_accelerated_scalar_2518((float *)(data + 0x24), (float *)(data + 0x28), 0.0f,
                                            D_L11_00161910_2518 * D_0015ED70_2518,
                                            D_L11_00161914_2518 * D_0015ED70_2518,
                                            D_L11_00161918_2518 * D_0015ED6C_2518);
        } else if (0.0f < *(float *)(data + 0x20)) {
            advance_accelerated_scalar_2518((float *)(data + 0x20), (float *)(data + 0x2C), 0.0f,
                                            D_L11_00161910_2518 * D_0015ED70_2518,
                                            D_L11_00161914_2518 * D_0015ED70_2518,
                                            D_L11_00161918_2518 * D_0015ED6C_2518);
        } else {
            moby->state = 1;
        }
        FUN_L01_003092d0_2518(moby);
        break;
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002F4040), where it is exact; names translated to the US level program. */

void FUN_L11_002f2cd0(struct Moby *moby) {
    char *data = (char *)moby->pvars;
    switch (*(int *)(data + 0x10)) {
    case 0:
        try_set_help_message(0xB, 0x2B0D);
        break;
    case 3:
        try_set_help_message(0xB, 0x2B0B);
        break;
    case 1:
    case 2:
    case 4:
        try_set_help_message(0xB, 0x2B0C);
        break;
    default:
        try_set_help_message(0xB, 0);
        break;
    }
}
typedef struct {
    float corner[4][4];
    unsigned int color[4];
    float uv[4][2];
    unsigned long long tag[4];
} QuadPacket_2f2d58;

extern void FUN_001fa298(void *, void *);
extern unsigned long long get_effect_texture_2f2d58(int) __asm__("FUN_001f44b8");
extern float fast_cos_2f2d58(float) __asm__("FUN_001f9dc8");
extern float fast_sin_2f2d58(float) __asm__("FUN_001f9de0");
extern void draw_quad_2f2d58(void *, void *, int) __asm__("FUN_001f7d30");
extern int D_L11_00161920_2f2d58 __asm__("D_L11_00161920") __attribute__((sda));
extern int D_L11_00161924_2f2d58 __asm__("D_L11_00161924") __attribute__((sda));
extern int D_L11_00161928_2f2d58 __asm__("D_L11_00161928") __attribute__((sda));
extern int D_L11_0016192C_2f2d58 __asm__("D_L11_0016192C") __attribute__((sda));
extern int D_L11_00161930_2f2d58 __asm__("D_L11_00161930") __attribute__((sda));
extern unsigned int D_L11_00161934_2f2d58 __asm__("D_L11_00161934") __attribute__((sda));
extern float D_L11_00161938_2f2d58 __asm__("D_L11_00161938") __attribute__((sda));

extern float D_L11_001D3530[];

/* Draws a ring of 32 textured quads around the moby; the band widens as the radius at pvars+0x3C shrinks below 1.15. */
void FUN_L11_002f2d58(struct Moby *moby) {
    QuadPacket_2f2d58 quad;
    float matrix[16];
    char *data = (char *)moby->pvars;
    float width;
    float angle;
    int i, j;

    FUN_001fa298(matrix, &moby->unkC0);
    qcopy(matrix + 12, &moby->pos);
    quad.tag[1] = get_effect_texture_2f2d58(D_L11_00161930_2f2d58);
    quad.tag[3] = (unsigned long long)D_L11_00161920_2f2d58 |
                  (unsigned long long)D_L11_00161924_2f2d58 << 2 |
                  (unsigned long long)D_L11_00161928_2f2d58 << 4 |
                  (unsigned long long)D_L11_0016192C_2f2d58 << 6 | 0x8000000000ULL;
    quad.tag[2] = 0xff9000000260ULL;
    quad.tag[0] = 0;
    {
        float *uv = D_L11_001D3530;
        unsigned int *colors = quad.color;
        float *dest1 = &quad.uv[0][1];
        float *dest0 = &quad.uv[0][0];
        int k = 3;
        do {
            float u = uv[0];
            float v = uv[1];
            *dest0 = u;
            uv += 2;
            *dest1 = v;
            dest0 += 2;
            *colors++ = D_L11_00161934_2f2d58;
            dest1 += 2;
            k--;
        } while (k >= 0);
    }
    width = 0.1f;
    if (*(float *)(data + 0x3c) < 1.15f) {
        float v = (1.15f - *(float *)(data + 0x3c)) + (1.15f - *(float *)(data + 0x3c));
        if (v > 1.0f)
            v = 1.0f;
        else if (v < 0.0f)
            v = 0.0f;
        width = v + 0.1f;
        if (*(float *)(data + 0x3c) < 0.65f)
            D_001413F5_2518 = 1;
        else
            D_001413F5_2518 = 0;
    }
    i = 0;
    do {
        j = 0;
        do {
            float *corner = quad.corner[j];
            angle = (float)(i + j / 2) * 6.28318f * 0.03125f - 3.14159f;
            corner[0] = fast_cos_2f2d58(angle) * *(float *)(data + 0x3c);
            corner[1] = fast_sin_2f2d58(angle) * *(float *)(data + 0x3c);
            corner[2] = 0.0f;
            if (j & 1) corner[2] = D_L11_00161938_2f2d58 + width + 0.0f;
            else corner[2] = D_L11_00161938_2f2d58 - width + 0.0f;
            corner[3] = 1.0f;
            j++;
        } while (j < 4);
        draw_quad_2f2d58(&quad, matrix, 0);
        i++;
    } while (i < 32);
}
/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002F43B0), where it is exact; names translated to the US level program. */

void FUN_L11_002f3040(struct Moby *moby) {
    char *data = (char *)moby->pvars;
    char **child = (char **)(data + 0x14);
    int count;
    int on;
    moby->unk31 = 1;
    moby->flags &= 0xFFFE;
    moby->unk94 = moby->pclass->unk10;
    on = 1;
    count = 2;
    do {
        if (*child) {
            *(unsigned short *)(*child + 0x34) &= 0xFFFE;
            (*child)[0x31] = on;
            *(int *)(*child + 0x94) = *(int *)(*(char **)(*child + 0x24) + 0x10);
        }
        child++;
        count--;
    } while (count >= 0);
}
extern void DeleteMoby(void *) __asm__("FUN_0020c828");

/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_002F46C0), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x88];
    float timer;
    char pad1[0x2FC - 0x8C];
    char *current;
    char pad2[0x30E - 0x300];
    short active;
    char pad3[0x2084 - 0x310];
    int mode;
    char pad4[0x22DA - 0x2088];
    unsigned short index;
} Globals;


void FUN_L11_002f3350(struct Moby *moby) {
    char *state = (char *)moby->pvars;
    switch (moby->state) {
    case 0:
        moby->unk30 = 0xFF;
        moby->state = 1;
        if (*(int *)state == -1)
            DeleteMoby(moby);
        break;
    case 1:
        if (hero.motion.pos.f[2] > 194.0f && hero.state.current != 0x32) {
            *(short unsigned int *)&hero.unk22DA = *(unsigned short *)state;
        }
        break;
    }
}
/* Same source as the exact FUN_L13_002e6a58, spawning class 0x40A, without the target class store and the closing effect. */
typedef struct {
    char _pad00[0x10];
    unsigned char nframes;
} AnimSeq_309378;

typedef struct {
    char _pad00[0x48];
    AnimSeq_309378 *seqs[1];
} AnimClass_309378;

typedef struct {
    char _pad00[0x24];
    AnimClass_309378 *pClass;
    char _pad28[0x50 - 0x28];
    unsigned char frame;
    unsigned char nextFrame;
    unsigned char seq;
    unsigned char prevSeq;
    char _pad54[0x5C - 0x54];
    float unk5C;
    char _pad60[0x68 - 0x60];
    float *frameData;
    char _pad6C[4];
    unsigned char unk70;
} MobyAnim_309378;

extern char *FUN_L00_0026daa0(char *, int, int, int, float);
extern void *FUN_002141f8(char *);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
void blend_moby_animation_309378(MobyAnim_309378 *arg0, int arg1, int arg2,
                                 int arg3) __asm__("FUN_00212f90");
void build_spherical_offset(f32 *out, f32 scale, f32 a, f32 b) __asm__("FUN_00214db0");

unsigned char *FUN_L11_00309378(char *src, char *pos, char *target, char *vec, int arg,
                                float scale) {
    unsigned char *moby = func_0020D348_m(0x40A);
    if (moby != 0) {
        char *data = *(char **)(moby + 0x78);
        moby[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        moby[0x20] = 0;
        *(char **)(data + 0x20) = src;
        *(char **)(data + 0x24) = target;
        qcopy(moby + 0x10, pos);
        qcopy(moby + 0x40, vec);
        if (target != 0) {
            char *e;
            e = FUN_002141f8(target);
            if (e != 0) {
                *(unsigned short *)(e + 0x1E) |= 0x80;
            }
        }
        *(int *)(data + 0x28) = arg;
        *(float *)(data + 0x2C) = scale;
        *(int *)(data + 0x30) = 0;
        *(int *)(data + 0x34) = 0;
        build_spherical_offset(data, scale, *(float *)(vec + 8), -*(float *)(vec + 4));
        if (moby[0x53] != 1) {
            blend_moby_animation_309378(moby, 1, 0, 10);
        }
        add_vector_xyz(moby + 0x10, moby + 0x10, data);
        if (*(char **)(data + 0x24) != 0) {
            qcopy(data + 0x10, *(char **)(data + 0x24) + 0x10);
        }
        *(float *)(moby + 0x2C) =
            *(float *)(*(char **)(moby + 0x24) + 0x24) *
            (*(float *)(src + 0x2C) / *(float *)(*(char **)(src + 0x24) + 0x24));
        FUN_L00_00250df8(moby);
    }
    return moby;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L11_00309ac0.s", FUN_L11_00309ac0);
extern int scale_ticks(int) __asm__("FUN_001f96f8");

/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_0030B850), where it is exact; names translated to the US level program. */

void blend_moby_animation(MobyAnim *arg0, int arg1, int arg2, int arg3) __asm__("FUN_00212f90");

int FUN_L11_0030a480(struct Moby *moby) {
    char *current;
    if (moby->state != 1)
        return 0;
    current = (char *)hero.ground_moby;
    if (current != (char *)moby || hero.air_frames.s)
        return 0;
    current[0x20] = 2;
    if (((unsigned char *)current)[0x53]) {
        int value = scale_ticks(0x14);
        blend_moby_animation(current, 0, 0, value);
    }
    return 1;
}
extern void FUN_0020cb10(struct Moby *, int, void *);
extern void FUN_L00_001fff28(void *, int, float);
extern void FUN_L00_0024f7c8(struct Moby *, int, float *);
extern float FUN_L00_00257c48(float, float);
extern void FUN_L00_0026f080(float *, float *, float, float);
extern float fast_cos_a500(float) __asm__("FUN_001f9dc8");
extern float fast_sin_a500(float) __asm__("FUN_001f9de0");
extern int D_L11_0015F5CC;

struct PartA500 {
    u8 unk0;
    u8 active;
    u8 pad2[0xE];
    u8 joint[0x30];
};

struct DataA500 {
    u8 pad0[0xF0];
    float angle[4];
    struct PartA500 parts[4];
};

void FUN_L11_0030a500(struct Moby *moby) {
    struct DataA500 *d = (struct DataA500 *)moby->pvars;
    float base[4];
    float pos[4];
    float vel[4];
    float speed;
    float step;
    float heading;
    int i;
    int n;
    int j;
    int k;
    float life;

    for (i = 0; i < 4; i++) {
        if (!((u8 *)d)[i * 0x40 + 0x101])
            FUN_0020cb10(moby, i, &d->parts[i]);
        step = frame_time * 12.217304f;
        if (moby->state == 1)
            step = frame_time * 2.6179938f;
        if (((u8 *)d)[i * 0x40 + 0x101]) {
            d->angle[i] = fast_add_rotations(d->angle[i], step);
            FUN_L00_001fff28(d->parts[i].joint, 0, d->angle[i]);
        }
    }
    if (FUN_001f9b80(&moby->pos, D_L11_001677C0) > 38.0f)
        return;
    if (moby->state == 1 && (D_L11_0015F5CC & 1))
        return;
    if (!(moby->pos.z < 224.5f))
        return;
    for (j = 0; j < 4; j++) {
        FUN_L00_0024f7c8(moby, j, base);
        n = moby->state == 1 ? 1 : 2;
        for (k = 0; k < n; k++) {
            pos[0] = base[0] + FUN_L00_00257c48(0.0f, 0.3f);
            pos[1] = base[1] + FUN_L00_00257c48(0.0f, 0.3f);
            pos[2] = base[2] + FUN_L00_00257c48(0.0f, 0.3f);
            heading = fast_add_rotations(moby->rot.z, FUN_L00_00257c48(0.0f, 0.122173049f) + 3.1415927f);
            speed = random_float_between(2.0f, 5.0f) * frame_time;
            if (moby->state == 1)
                speed *= 0.4f;
            vel[0] = fast_cos_a500(heading) * speed;
            vel[1] = fast_sin_a500(heading) * speed;
            vel[2] = 0.0f;
            vel[2] = random_float_between(-2.0f, 2.0f) * frame_time;
            life = random_float_between(6300.0f, 14700.0f);
            FUN_L00_0026f080(pos, vel, life, 222.5f);
        }
    }
}
/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_0030BC00), where it is exact; names translated to the US level program. */

int FUN_L11_0030a830(struct Moby *arg) {
    return arg->state == 5;
}
/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_0030BC10), where it is exact; names translated to the US level program. */

void FUN_L11_0030a840(unsigned char *arg) {
    *(int *)(*(int *)(arg + 0x78) + 0xB8) = 1;
}
/* Ported from rac1-decomp (src/overlays/l11_pokitaru/vendor_002CC828.c: func_L11_0030BC20), where it is exact; names translated to the US level program. */

extern int D_L11_0015FFD8; /* no foreign declaration */
extern int FUN_L11_00316128(char *);
extern short *D_L11_001AC240[];
extern short D_L11_0015FFF4;

int FUN_L11_0030a850(struct Moby *m) {
    int idx = *(short *)((char *)m->pvars + 0xB4);
    short *p;
    if (idx < 0 || *(int *)&D_L11_0015FFF4 < idx)
        return 1;
    p = D_L11_001AC240[idx];
    if (p == 0)
        return 1;
    do {
        char *o = (char *)(((*p & 0x7FFF) << 8) + D_L11_0015FFD8);
        if (o[0x20] >= 0 && *(short *)(o + 0xA6) == 0x4DE) {
            if (FUN_L11_00316128(o) == 0)
                return 0;
        }
    } while (*p++ >= 0);
    return 1;
}
