/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L10_002ea1f0.s", FUN_L10_002ea1f0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L10_002ea4e8.s", FUN_L10_002ea4e8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L10_002ea7b0.s", FUN_L10_002ea7b0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L10_002eaa08.s", FUN_L10_002eaa08);
INCLUDE_ASM("config/us/overlays/asm/FUN_L10_002eacd8.s", FUN_L10_002eacd8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L10_002eb6f0.s", FUN_L10_002eb6f0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L10_002eb7e0.s", FUN_L10_002eb7e0);
