/* Level overlay code after runtime/dma; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002922d0.s", FUN_L04_002922d0);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/l04_eudora/vuchain_00293490.c: func_L04_00293530), where it is exact; names translated to the US level program. */

void FUN_L04_00292370(void *unused, char *arg) {
    *(float *)(arg + 0x10C) = -0.19634955f;
    *(float *)(arg + 0x110) = 1.5707964f;
    *(float *)(arg + 0x1BC) = -1.5707964f;
    *(float *)(arg + 0x1C0) = 0.19634955f;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002923b8.s", FUN_L04_002923b8);
/* Ported from rac1-decomp (PAL, src/overlays/l04_eudora/vuchain_00293490.c: func_L04_00293990), where it is exact; names translated to the US level program. */

extern int FUN_L00_002a13f0(int *a, char *b);

int FUN_L04_002927d0(char *arg0, char *arg1) {
    int **p = (int **)(arg1 + 0x70);
    int *found = 0;
    int i;
    for (i = 12; i >= 0; i--) {
        int *e = *p++;
        if (*e == (int)(unsigned char)arg0[0x52]) found = e;
    }
    if (found == 0) return (unsigned char)arg1[0xB6];
    return FUN_L00_002a13f0(found, arg1);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_00292828.s", FUN_L04_00292828);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_00292d48.s", FUN_L04_00292d48);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_00295778.s", FUN_L04_00295778);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_00295de8.s", FUN_L04_00295de8);

INCLUDE_ASM("config/us/overlays/asm/FUN_L04_0029eb20.s", FUN_L04_0029eb20);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_0029ecf8.s", FUN_L04_0029ecf8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002ba448.s", FUN_L04_002ba448);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002ba520.s", FUN_L04_002ba520);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002c1b80.s", FUN_L04_002c1b80);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002c1d70.s", FUN_L04_002c1d70);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002c1fb8.s", FUN_L04_002c1fb8);
