/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

#define NOT_SDA

#define MACRO_ADDR

#include "qcopy.h"

/* UpdateMoby_584 */
/* Ported from rac1-decomp (PAL, src/overlays/l04_eudora/vendor_002CB800.c: func_L04_002D4960), where it is exact; names translated to the US level program. */

extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_L00_0025d1b8(void *);
extern void FUN_L00_00260738(char *, void *, void *, void *);

void FUN_L04_002d3580(char *m) {
    char *d = *(char **)(m + 0x78);
    float v[4];
    FUN_001f9a28(v, m + 0x10, d + 0xA0);
    FUN_L00_00260738(d + 0x60, v, m + 0x40, m + 0x40);
    qcopy(d + 0xA0, m + 0x10);
    if (*(unsigned char *)(m + 0x20) == 0) {
        *(int *)(d + 0x20) = 0;
        *(short *)(d + 0x24) = 0;
        d[0x28] = 4;
        *(short *)(d + 0x3E) = 0xD;
        FUN_L00_0025d1b8(m);
        m[0x20] = 1;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002ca420.s", FUN_L04_002ca420);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002cdda0.s", FUN_L04_002cdda0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002ce060.s", FUN_L04_002ce060);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002d1418.s", FUN_L04_002d1418);
#include "sda.h"

/* Ported from rac1-decomp (PAL, src/overlays/l04_eudora/vendor_002CB800.c: func_L04_002D29E8), where it is exact; names translated to the US level program. */

extern void func_L00_0025F4A8_alt(void*,void*,void*,float,float,int,int,int,float,float,float,float,int,float,int,int,int,int) __asm__("FUN_L00_0025e450");
extern void FUN_L00_0024f7c8(void *, int, void *);
extern void clear_vector(void *) __asm__("FUN_001f99f8");

void FUN_L04_002d1608(void *m) {
    char pos[16];
    char vec[16];
    clear_vector(vec);
    FUN_L00_0024f7c8(m, 12, pos);
    func_L00_0025F4A8_alt(m, vec, pos, 0.0f, 0.0f, 10, 3, 4,
                          2.0f, 1.0f, 100000.0f, 1.0f, -1, 15.0f, 1, 1, -1, 0);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002d16b8.s", FUN_L04_002d16b8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002d6f68.s", FUN_L04_002d6f68);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002d7e90.s", FUN_L04_002d7e90);
float FUN_L04_002e1768(char *moby) {
    switch (*(short *)(moby + 0xA6)) {
    case 0x44D:
    case 0x5FC:
        return 1.3f;
    case 0x5FB:
        return -2.55f;
    }
    return -2.05f;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002e17d8.s", FUN_L04_002e17d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L04_002e1a10.s", FUN_L04_002e1a10);
/* Same source as the exact FUN_L10_00298940, with a 0.25 lift and the draw skipped in mode 2. */
typedef struct {
    float pad0[4];
    float a[4];
    float b[4];
    int c[4];
    float d[4];
} L10SpriteData_298940;
extern void func_001F9BF0_298940(void *, void *, void *) __asm__("FUN_001f9a28");
extern void func_L00_001FF4B0_298940(void *, void *, float) __asm__("FUN_001f9bf8");
extern void func_001F9BD8_298940(void *, void *, void *) __asm__("FUN_001f9a10");
extern int func_001F9908_298940(int *) __asm__("FUN_001f9740");
extern int func_001F9850_298940(int) __asm__("FUN_001f96f8");
extern float func_001FA888_298940(int) __asm__("FUN_001fa6c0");
extern int func_001FA8A8_298940(int, int, float) __asm__("FUN_001fa6e0");
extern float func_001F9B88_298940(float) __asm__("FUN_001f99c0");
extern unsigned char *func_L00_00273E08_298940(void *, int, unsigned char, int, int, int, int, float) __asm__("FUN_L00_00272f68");
extern int func_001FA898_298940(float) __asm__("FUN_001fa6d0");
extern char D_L10_00167240_298940[] __asm__("D_L04_00166F40");
extern int D_L04_0015F5C4_t __asm__("D_L04_0015F5C4");
void FUN_L04_002e1d00(char *m) {
    L10SpriteData_298940 *p = *(L10SpriteData_298940 **)(m + 0x78);
    float d[4] __attribute__((aligned(16)));
    float e[4] __attribute__((aligned(16)));
    int i, col;
    float f;

    *(float *)(m + 0x18) += 0.25f;
    func_001F9BF0_298940(d, D_L10_00167240_298940, m + 0x10);
    func_L00_001FF4B0_298940(d, d, -0.3f);
    func_L00_001FF4B0_298940(e, d, 0.1f);
    func_001F9BD8_298940(d, d, m + 0x10);
    *(float *)(m + 0x18) -= 0.25f;
    for (i = 0; i < 4; i++) {
        float h = p->a[i] + p->b[i];
        p->a[i] = h;
        if (255.0f <= h) {
            p->a[i] = h - 255.0f;
        } else if (h <= 0.0f) {
            p->a[i] = h + 255.0f;
        }
        if (func_001F9908_298940(&p->c[i])) {
            p->c[i] = func_001F9850_298940(0xFF);
        }
        f = func_001FA888_298940(func_001F9850_298940(0xFF) - p->c[i]);
        f = f / (float)func_001F9850_298940(0xFF);
        col = func_001FA8A8_298940(0x4040FFFF, 0x1040FFFF, func_001F9B88_298940(0.5f - f));
        if (D_L04_0015F5C4_t != 2)
            func_L00_00273E08_298940(d, col, func_001FA898_298940(p->a[i]) & 0xFF, 0x35, 1, 2, 0, p->d[i]);
        func_001F9BD8_298940(d, d, e);
    }
}
