/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002df520.s", FUN_L03_002df520);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002e01d0.s", FUN_L03_002e01d0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002eb7e0.s", FUN_L03_002eb7e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002eb978.s", FUN_L03_002eb978);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002ebb00.s", FUN_L03_002ebb00);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002ebc58.s", FUN_L03_002ebc58);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002ebd70.s", FUN_L03_002ebd70);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002ebdb0.s", FUN_L03_002ebdb0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002ebde8.s", FUN_L03_002ebde8);
