/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002df520.s", FUN_L03_002df520);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002e01d0.s", FUN_L03_002e01d0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002eb7e0.s", FUN_L03_002eb7e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002eb978.s", FUN_L03_002eb978);
#include "sda.h"
extern void func_L00_001FF4B0_ebb00(void *, void *, float) __asm__("FUN_001f9bf8");
extern float func_001EC120_ebb00(void *, float, float, float, float, float) __asm__("FUN_001ebd78");
extern void func_001F9BD8_ebb00(void *, void *, void *) __asm__("FUN_001f9a10");
extern char D_0013E633_ebb00[] __asm__("D_0013F350");
void FUN_L03_002ebb00(void *arg) {
    char *m = arg;
    char *d = *(char **)(m + 0x70);
    char *a = d + 0xD0;
    char *b = d + 0xF0;
    char *g = D_0013E633_ebb00;
    float v3[4];
    float v1[4];
    float v2[4];
    char *h;
    if (*(int *)(g + 0x2284) != 0x50 || *(int *)(g + 0x2084) == 0x11) {
        *(float *)(b + 0x34) = *(float *)(g + 0x88);
    }
    func_L00_001FF4B0_ebb00(v1, D_0013E633_ebb00 + 0x290, -*(float *)(a + 0x10));
    func_L00_001FF4B0_ebb00(v3, b, -*(float *)a);
    h = D_0013E633_ebb00;
    *(float *)d =
        func_001EC120_ebb00(d + 0x10, *(float *)d, *(float *)(h + 0x80), *(float *)(d + 0x20),
                            *(float *)(d + 0x24), *(float *)(d + 0x28));
    *(float *)(d + 4) =
        func_001EC120_ebb00(d + 0x14, *(float *)(d + 4), *(float *)(h + 0x84), *(float *)(d + 0x20),
                            *(float *)(d + 0x24), *(float *)(d + 0x28));
    *(float *)(d + 8) =
        func_001EC120_ebb00(d + 0x18, *(float *)(d + 8), *(float *)(b + 0x34), *(float *)(d + 0x20),
                            *(float *)(d + 0x24), *(float *)(d + 0x28));
    func_001F9BD8_ebb00(v2, d, v1);
    func_001F9BD8_ebb00(v2, v2, v3);
    *(float *)(m + 0x30) = v2[0];
    *(float *)(m + 0x34) = v2[1];
    *(float *)(m + 0x38) = v2[2];
}
#include "qcopy.h"

/* smooths the moby's data floats and rebuilds its orientation axes */
/* Ported from rac1-decomp (src/overlays/l03_kerwan/vendor_002CB280.c: func_L03_002ED020), where it is exact; names translated to the US level program. */

extern char D_0013E633[] __asm__("D_0013F3D0");
extern char D_L03_00166F40[];
extern short D_L03_00161E70 __attribute__((sda));
extern short D_L03_00161E74 __attribute__((sda));
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void cross_vectors_xyz(void *, void *, void *) __asm__("FUN_001f9ad8");
extern void normalize_vector_xyz(void *out, void *a, f32 len) __asm__("FUN_001f9bf8");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
f32 cam_interp_values(void *p, f32 to, f32 stiffness, f32 damping, f32 max,
                      f32 vel) __asm__("FUN_001ebd78");

void FUN_L03_002ebc58(void *arg) {
    char *m = arg;
    char *d = *(char **)(m + 0x70);
    float *p = (float *)(d + 0xB0);
    float a[4];
    float b[4];
    float c[4];
    qcopy(b, d);
    p[2] = cam_interp_values(d + 0xBC, p[2], *(float *)(D_0013E633 + 0x8),
                             *(float *)&D_L03_00161E70, *(float *)&D_L03_00161E74, 0.0f);
    normalize_vector_xyz(c, D_L03_00166F40, p[5]);
    add_vector_xyz(b, c, b);
    subtract_vector_xyz(a, b, m + 0x30);
    normalize_vector_xyz(m, a, 1.0f);
    qcopy(m + 0x40, m);
    cross_vectors_xyz(m + 0x10, m, D_L03_00166F40 - 0x10);
    normalize_vector_xyz(m + 0x10, m + 0x10, 1.0f);
    cross_vectors_xyz(m + 0x20, m + 0x10, m);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L03_002ebd70.s", FUN_L03_002ebd70);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l03_kerwan/vendor_002CB280.c: func_L03_002ED178), where it is exact; names translated to the US level program. */

extern void FUN_L03_002ebb00_u(void *) __asm__("FUN_L03_002ebb00");
extern void FUN_L03_002ebc58_u(void *) __asm__("FUN_L03_002ebc58");
void NoOpMainCallback(void *) __asm__("FUN_001e93e8");

void FUN_L03_002ebdb0(void *arg) {
    FUN_L03_002ebb00_u(arg);
    NoOpMainCallback(arg);
    FUN_L03_002ebc58_u(arg);
}
/* Ported from rac1-decomp (src/overlays/l03_kerwan/vendor_002CB280.c: func_L03_002ED1B0), where it is exact; names translated to the US level program. */

extern char D_0013E533[];
extern int D_L03_0015EF50;
extern int is_point_inside_clip_volume_alt(void *, int) __asm__("FUN_00214720");

void FUN_L03_002ebde8(char *moby) {
    char *entry = (char *)((*(short *)(moby + 0x84) << 5) + D_L03_0015EF50);
    char *sub = *(char **)(entry + 0x1C);
    int value = *(int *)(sub + 0xC);
    if (value >= 0 && is_point_inside_clip_volume_alt(D_0013E533 + 0xE9D, value) == 0) {
        *(short *)(moby + 0x7E) = 3;
    }
}
